<?php
include_once "access_control.php";
define("_LOGIN", "LOGG INN");
define("_USERNAME", "Brukernavn:");
define("_PASSWORD", "Passord:");
define("_CHANGEPASSWORD", "Skifte passord");
define("_CURRENTPASSWORD", "Gjeldende passord:");
define("_NEWPASSWORD", "Nytt passord:");
define("_CONFIRMNEWPASSWORD", "Bekreft nytt passord:");
define("_SUBMIT", "Send inn");
define("_CURRENTPASSWORDREQUIRED", "Gjeldende passord kreves");
define("_PASSWORDREQUIRED", "Passord kreves");
define("_USERNAMEREQUIRED", "Brukernavn kreves");
define("_USERAUTHFAILED", "Brukerautentisering mislyktes!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Brukernavn eller gjeldende passord er feil!");
define("_DBACCESSFAILURE", "Får ikke tilgang til databasen!");
define("_CHANGEPASSWORDERROR", "Du må først endre passordet ditt!");
define("_SAMEPASSWORDERROR", "Gjeldende og nytt passord skal være ulike!");
define("_PASSWORDMATCHERROR", "Passord samsvarer ikke!");
define("_CURRENTPASSWORDWRONG", "Gjeldende passord er feil!");
define("_PASSWORDERRORLEVEL2", "Passordet er ugyldig, tegnlengden må være 20 og inneholde minst to bokstaver [A-Za-z], to sifre [0-9] og to spesialtegn [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Passordet er ugyldig, tegnlengden må være minst 12, maksimalt 32 tegn og inneholde minst to små bokstaver [a-z] og to store bokstaver [A-Z], to tall [0-9] og minst to spesialtegn [!%&/()=?*#+-_].");
define("_LOGINLOCKOUT", "For mange mislykkede forsøk. Vennligst prøv etter 1800 sekunder.");

define("_MAINPAGE", "Hovedside");
define("_GENERAL", "Generelle innstillinger");
define("_OCPPSETTINGS", "OCPP-innstillinger");
define("_NETWORKINTERFACES", "Nettverksgrensesnitt");

define("_OCPPCONNINTERFACE", "Grensesnitt for OCPP-tilkobling : ");
define("_CONNECTIONSTATE", "Tilkoblingstilstand : ");
define("_DISCONNECTED", "Koblet fra");
define("_NEEDTOLOGINFIRST", "Du må logge inn først!");
define("_CONNECTED", "Tilkoblet");
define("_CPSERIALNUMBER", "CP-serienummer : ");
define("_HMISOFTWAREVERSION", "HMI-programvareversjon : ");
define("_OCPPSOFTWAREVERSION", "OCPP-programvareversjon : ");
define("_POWERBOARDSOFTWAREVERSION", "Tilkoblingskort-programvareversjon : ");
define("_OCPPDEVICEID", "OCCP-enhets-ID : ");
define("_DURATIONAFTERPOWERON", "Varighet etter påslåing : ");
define("_LOGOUT", "Logg ut");
define("_PRESET", "Forhåndsinnstillinger:");

define("_OCPPCONNECTION", "OCPP-tilkobling");
define("_ENABLED", "Aktivert");
define("_DISABLED", "Deaktivert");
define("_CONNECTIONSETTINGS", "Tilkoblingsinnstillinger");
define("_CENTRALSYSTEMADDRESS", "Sentralsystemadresse ");
define("_CHARGEPOINTID", "Ladepunkt-ID ");
define("_OCPPVERSION", "OCPP-versjon");
define("_SAVE", "Lagre");
define("_SAVESUCCESSFUL", "Lagret.");
define("_CENTRALSYSTEMADDRESSERROR", "Sentralsystemadresse kreves!");
define("_CHARGEPOINTIDERROR", "Ladepunkt-ID kreves!");
define("_SECONDS", "Sekunder");
define("_ADD", "Legg til");
define("_REMOVE", "Fjern");
define("_SAVECAPITAL", "LAGRE");
define("_CANCEL", "Avbryt");

define("_CELLULAR", "Mobil");
define("_INTERFACEIPADDRESS", "IP-adresse, grensesnitt: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "APN-navn: ");
define("_APNUSERNAME", "APN-brukernavn: ");
define("_APNPASSWORD", "APN-passord: ");
define("_IPSETTING", "IP-innstilling: ");
define("_IPADDRESS", "IP Adresse: ");
define("_NETWORKMASK", "Nettverksmaske: ");
define("_DEFAULTGATEWAY", "Standard gateway: ");
define("_PRIMARYDNS", "Primær DNS: ");
define("_SECONDARYDNS", "Sekundær DNS: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Sikkerhet: ");
define("_SECURITYTYPE", "Velg sikkerhetstype");
define("_NONE", "Ingen");
define("_SELECTMODE", "Velg modus!");
define("_RFIDLOCALLIST", "RFID lokal liste");
define("_ACCEPTALLRFIDS", "Godta alle RFID-er");
define("_MANAGERFIDLOCALLIST", "Administrer RFID lokal liste:");
define("_AUTOSTART", "Autostart");
define("_PROCESSING", "Behandler ... Vennligst vent...");
define("_MACADDRESS", "MAC-adresse: ");
define("_WIFIHOTSPOT", "Wi-Fi-hotspot");
define("_TURNONDURINGBOOT", "Slå på under oppstart: ");
define("_AUTOTURNOFFTIMEOUT", "Slå av tidsavbrudd automatisk: ");
define("_AUTOTURNOFF", "Slå av automatisk: ");
define("_HOTSPOTALERTMESSAGE", "Innstillinger for hotspot-innstillinger vil tre i kraft neste gang enheten slås på. ");
define("_HOTSPOTREBOOTMESSAGE", "Vil du starte maskinen på nytt nå? ");

define("_DOWNLOADACLOGS", "Last ned AC-logger");
define("_DOWNLOADCELLULARLOGS", "Last ned mobilmodullogger");
define("_DOWNLOADPOWERBOARDLOGS", "Last ned tilkoblingskort-logger");
define("_PASSWORDRESETSUCCESSFUL", "Passordet ditt ble tilbakestilt.");
define("_DBOPENEDSUCCESSFULLY", "Åpnet database\n");
define("_WSSCERTSSETTINGS", "WSS-sertifikatinnstillinger ");
define("_CONFKEYS", "Konfigurasjonstaster");
define("_KEY", "Tast");
define("_STATIC", "Statisk");
define("_TIMEZONE", "Tidssone");
define("_PLEASESELECTTIMEZONE", "Velg tidssone");
define("_DISPLAYSETTINGS", "Skjerminnstillinger");
define("_DISPLAYLANGUAGE", "Vise språk");
define("_BACKLIGHTDIMMING", "Dimming av bakgrunnsbelysning : ");
define("_PLEASESELECT", "Vennligst velg");
define("_TIMEBASED", "Tidsbasert");
define("_SENSORBASED", "Sensorbasert");
define("_BACKLIGHTDIMMINGLEVEL", "Bakgrunnsbelysningens dimmingsnivå : ");
define("_BACKLIGHTTHRESHOLD", "Terskel for bakgrunnsbelysning : ");
define("_SETMIDTHRESHOLD", "SetMidThreshold");
define("_SETHIGHTHRESHOLD", "SetHighThresold");
define("_LOCALLOADMANAGEMENT", "Lokal lasthåndtering");
define("_MINIMUMCURRENT", "Minimum strøm: ");
define("_FIFOPERCENTAGE", "FIFO-prosent: ");
define("_GRIDMAXCURRENT", "Rutenett, maksimal strøm: ");
define("_MASTERIPADDRESS", "IP-adresse til master: ");
define("_BACKLIGHTTIMESETTINGS", "Tidsinnstillinger for bakgrunnsbelysning: ");
define("_SHOULDSELECTTIMEZONE", "* Du må velge tidssone!");
define("_MINIMUMCURRENTREQUIRED", "* Minimum strøm er nødvendig!");
define("_CURRENTMUSTBENUMERIC", "* Strømmen må være numerisk!");
define("_FIFOPERCREQUIRED", "* FIFO-prosent kreves!");
define("_FIFOPERCSHOULDBETWEEN", "* FIFO-prosenten må være mellom 0 og 100!");
define("_PERCMUSTBENUMERIC", "* Prosentandelen må være numerisk!");
define("_GRIDMAXCURRENTREQUIRED", "* Nettstrøm kreves!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Nettstrømmen må være numerisk!");
define("_IPADDRESSOFMASTERREQUIRED", "* IP-adresse til master kreves!");
define("_INVALIDIPADDRESS", "* Du har angitt en ugyldig IP-adresse!");
define("_SAMENETWORKLAN", "* Du har lagt inn en IP-adresse i samme nettverk med LAN!");
define("_SAMENETWORKWLAN", "* Du har lagt inn en IP-adresse i samme nettverk med WLAN!");
define("_APNISREQUIRED", "APN kreves!");
define("_IPADDRESSREQUIRED", "IP-adresse kreves!");
define("_NETWORKMASKREQUIRED", "Nettverksmaske kreves!");
define("_INVALIDNETWORKMASK", "* Du har angitt en ugyldig nettverksmaske!");
define("_DEFAULTGATEWAYREQUIRED", "Standard gateway kreves!");
define("_INVALIDGATEWAY", "Du har angitt en ugyldig standard gateway!");
define("_PRIMARYDNSREQUIRED", "Primær dns kreves!");
define("_INVALIDDNS", "Du har angitt ugyldig dns!");
define("_SELECTIPSETTING", "Velg IP-innstilling.");
define("_SSIDREQUIRED", "SSID kreves!");
define("_PASSWORDISREQUIRED", "Passord kreves!");
define("_WIFIPASSWORDERROR", "Passordet er ugyldig, tegnlengden må være minimum 8 og maksimalt 63 <br> gyldige tegn a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Passordet er ugyldig, tegnlengden må være 20,<br>&#8226; Passordet må inneholde minst to bokstaver [A-Za-z],<br>&#8226; Passordet må inneholde minst to sifre [0-9],<br>&#8226; Passordet må inneholde minst to spesialtegn [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Passordet er ugyldig, tegnlengden må være minst 12, maksimalt 32,<br>&#8226; Passordet må inneholde minst to små bokstaver [a-z], <br>&#8226; Passordet må inneholde minst to store bokstaver [A-Z], <br>&#8226; Passordet må inneholde minst to sifre [0-9],<br>&#8226; Passordet må inneholde minst to spesialtegn [!%&/()=?*#+-_]");
define("_WIFISSIDERROR", "SSID er ugyldig, gyldige tegn a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Velg sikkerhetstype");
define("_HOSTIPREQUIRED", "* Vert-IP kreves!");
define("_CERTMANREQUIRED", "* Sertifiseringsadministrasjon kreves!");
define("_OCPPENABLEALERT", "Hvis du vil bruke ladestasjonen din i frittstående modus,<br>må du først deaktivere OCPP-tilkobling fra OCPP-innstillingsmenyen.");
define("_NOTSAVEDALERT", "Siden ble ikke lagret.");
define("_SAVEQUESTION", "Vil du lagre endringene?");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Mobiltilkobling blir deaktivert. Vil du bekrefte?");
define("_WIFICONNECTIONCONFIRM", "Wi-Fi-tilkobling vil bli deaktivert. Vil du bekrefte?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Hvis du vil aktivere LAN DHCP-server,<br>må du først deaktivere Wi-Fi-sone<br>fra &#39Wi-Fi-sone&#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Hvis du vil aktivere Wi-Fi Hotspot,<br>må du først deaktivere LAN DHCP-server<br>fra &#39LAN IP Setting&#39.");

define("_DYNAMIC", "Dynamisk");
define("_DIAGNOSTICS", "Diagnostik");
define("_LOCALLOAD", "Lokal lasthåndtering");
define("_DOWNLOAD", "Last ned");
define("_STARTDATE", "Startdato");
define("_ENDDATE", "Sluttdato");
define("_CLEAREVENTLOGS", "Tøm alle hendelseslogger");
define("_CLEAREVENTLOGSINFO", "Dette vil tømme alle hendelseslogger!");
define("_DOWNLOADEVENTLOGSINFO", "Last ned enhets hendelseslogger for maksimalt 5 dager");
define("_DEVICEEVENTLOGS", "Enhets hendelseslogger");
define("_DEVICECHANGELOGS", "Enhets endringslogger");
define("_LOGSDATEERROR", "Vennligst velg datoer for en maksimal periode på 5 dager.");
define("_DOWNLOACHANGELOGS", "Last ned enhets endringslogger");
define("_VPNFUNCTIONALITY", "VPN-funksjonalitet: ");
define("_CERTMANAGEMENT", "Sertifiseringsledelse: ");
define("_NAME", "Navn: ");
define("_CONNECTIONINTERFACE", "Tilkoblingsgrensesnitt ");
define("_ANY", "Hvilke som helst");
define("_OCPPCONNPARAMETERS", "OCPP-konfigurasjonsparametere");
define("_SETDEFAULT", "Sett til Standard ");
define("_STANDALONEMODE", "Frittstående modus");
define("_STANDALONEMODETITLE", "Frittstående modus:");
define("_STANDALONEMODENOTSELECTED", "* Frittstående modus kan ikke velges siden OCPP er aktivert.");
define("_CHARGERWEBUI", "Lader nettbrukergrensesnitt");
define("_SYSTEMMAINTENANCE", "Systemvedlikehold");
define("_HOSTIP", "Vert-IP: ");
define("_PASSWORDERRORLEVEL1", "Passordet er ugyldig, tegnlengden må være minimum 6 tegn og inneholde minst 1 liten bokstav, 1 stor bokstav og 1 numerisk tegn!");
define("_SELECTBACKLIGHTDIMMING", "* Du må velge bakgrunnsbelysning!");
define("_ISREQUIRED", "kreves!");
define("_ISNOTVALID", "er ikke gyldig!");
define("_ISDUPLICATED", "er duplisert!");
define("_MUSTBENUMERIC", "må være numerisk!");
define("_VPNFUNCTIONALITYREQUIRED", "* VPN-funksjonalitet kreves!");
define("_VPNNAMEREQUIRED", "* VPN-navn kreves!");
define("_VPNPASSWORDREQUIRED", "* VPN-passord kreves!");
define("_EXPLANATION", "Indikerer obligatorisk felt.");
define("_FIRMWAREUPDATE", "Firmware-oppdateringer");
define("_BACKUPRESTORE", "Sikkerhetskopiering og gjenoppretting av konfigurasjon");
define("_CHANGEADMINPASSWORD", "Administrasjonspassord");
define("_SYSTEMRESET", "Systemnullstilling");
define("_FACTORYRESET", "Fabrikkstandard");
define("_FACTORYRESETBUTTON", "Fabrikknullstilling");
define("_FACTORYDEFAULTCONFIGURATION", "Fabrikkstandardkonfigurasjon");
define("_LOGFILES", "Loggfiler");
define("_BACKUPFILE", "Sikkerhetskopifil");
define("_RESTOREFILE", "Gjenopprett konfigurasjonsfil");
define("_FREEMODEMAXCHARACTER", "må være maks 32 tegn!");
define("_RESTOREMESSAGE", "Bekrefter du å bruke endringene og starte på nytt nå?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "Passordet ditt må bestå av seks tegn, og må inneholder minst én stor
bokstav, én liten bokstav og ett tall.");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Passordet ditt må bestå av 20 tegn og det må inneholde minst to bokstaver,
to tall og to spesialtegn.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Passordet ditt må være på minimum 12, maksimalt 32 tegn, og det må inneholde
minst to store bokstaver, to små bokstaver, to tall og to spesialtegn.");

define("_BACKTOLOGIN", "Tilbake til innlogging");
define("_CHANGE", "Skifte");
define("_SYSTEMADMINISTRATION", "Systemadministrasjon");
define("_UPDATE", "Oppdater");
define("_CONFIRM", "Bekreft");
define("_FACTORYDEFAULTCONFIRM", "Er du sikker på å tilbakestille til fabrikkinnstillingene?");
define("_FILENAME", "Filnavn");
define("_UPLOAD", "Lasteopp");
define("_SELECTFIRMWARE", "Velg firmwareoppdateringsfil fra PC");
define("_FIRMWAREFILESIZE", "Kontroller størrelsen på firmwarefilen.");
define("_FIRMWAREFILETYPE", "Kontroller typen firmwarefil.");

define("_LESSTHANOREQUAL4", "må være mellom 1 og 4");
define("_LESSTHANOREQUAL20", "må være mindre enn eller lik 20");
define("_LESSTHANOREQUAL65000", "må være mindre enn eller lik 65000");
define("_LESSTHANOREQUAL300", "må være mindre enn eller lik 300");
define("_LESSTHANOREQUAL86500", "må være mindre enn eller lik 86500");
define("_LESSTHANOREQUAL10000", "må være mindre enn eller lik 10000");
define("_LESSTHANOREQUAL22", "må være mindre enn eller lik 22");
define("_LESSTHANOREQUAL10", "må være mindre enn eller lik 10");
define("_LESSTHANOREQUAL600", "må være mindre enn eller lik 600");
define("_LESSTHANOREQUAL120", "må være mindre enn eller lik 120");
define("_HIGHTHANOREQUAL0", "må være høyere enn eller lik 0");
define("_CHANGEPASSWORDSUGGESTION", "Vi anbefaler å endre standardpassordet fra systemvedlikeholdsmenyen");

define("_FILESIZE", "Sjekk størrelsen på filen.");
define("_FILETYPE", "Kontroller filtypen.");

define("_BACKUPVERSIONCHECK", "Denne filens versjon passer ikke for enheten.");
define("_HARDRESETCONFIRM", "Er du sikker på at du vil utføre hard tilbakestilling?");
define("_SOFTRESETCONFIRM", "Er du sikker på at du vil utføre myk tilbakestilling?");
define("_NEWSETUP", "Bruk brukerhåndboken for det nye oppsettet.");

define("_LOGOSETTINGS", "Logoinnstillinger");
define("_USELOGO", "Velg logofil fra PC");
define("_LOGOTYPE", "Velg en logo med png-format.");
define("_LOGODIMENSION", "Maksimal tillatt logostørrelse er 80x80. Velg en logo med riktig størrelse.");

define("_SERVICECONTACTINFO", "Kontaktinfo for skjermservice");
define("_SERVICECONTACTINFOCHARACTER", "Kontaktinfo for skjermservice må være maks 25 tegn!<br>Gyldige tegn a..z 0..9 .+@*");

define("_SCREENTHEME", "Vise tema");
define("_DARKBLUE", "Mørkeblå");
define("_ORANGE", "Oransje");
define("_PLEASEENTERRFIDLOCALLIST", "Skriv inn RFID lokal liste!");

define("_LOADMANAGEMENT", "Lastadministrasjon");
define("_CPROLE", "Ladepunktrolle");
define("_GRIDSETTINGS", "Rutenettinnstillinger");
define("_LOADMANAGEMENTMODE", "Lastadministrasjonsmodus");
define("_LOADMANAGEMENTGROUP", "Lastadministrasjonsgruppe");
define("_LOADMANAGEMENTOPTION", "Laststyringsalternativ");
define("_ALARMS", "Alarmer");

define("_MASTER", "Master");
define("_SLAVE", "Slave");
define("_TOTALCURRENTLIMIT", "Total nåværende grense per fase");
define("_SUPPLYTYPE", "Forsyningstype");
define("_FIFOPERCANTAGE", "FIFO-prosent");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Delt likt");
define("_COMBINED", "Kombinert");
define("_TOTALCURRENTLIMITERROR", "Total nåværende grense per fase kreves!");
define("_LESSTHAN1024", "må være mindre enn 1024");
define("_ATLEAST0","må være minst 0");
define("_MORETHAN12", "må være mer enn 12");
define("_CHOOSEONE", "Velg én");
define("_SLAVEMINCHCURRENT", "Frakoblet feilsikker ladestrøminnstilling");
define("_SERIALNO", "Serienummer");
define("_CONNECTORSTATE", "Kontaktstatus");
define("_NUMBEROFPHASES", "Antall faser");
define("_PHASECONSEQUENCE", "Fasetilkoblingssekvens");
define("_VIP", "VIP-lading");
define("_CPMODE", "CP-modus");
define("_VIPERROR", "VIP-lading kreves");
define("_PHASECONSEQUENCEERROR", "Fasetilkoblingssekvens kreves!");
define("_CPMODEERROR", "CP-modus kreves!");
define("_SUPPORTEDCURRENT", "Støttet strøm");
define("_INSTANTCURPERPHASE", "Øyeblikkelig nåværende fase");
define("_FIFOCHARGINGPERCENTAGE", "FIFO-ladeprosent");
define("_MINIMUMCURRENT1P", "Minimum ladestrøm 1-fase");
define("_MINIMUMCURRENT3P", "Minimum ladestrøm 3-fase");
define("_MAXIMUMCURRENT", "Maksimal ladestrøm");
define("_STEP", "Steg");
define("_UPDATEDLMGROUP", "Oppdater DLM-gruppe");
define("_MAINCIRCUITCURRENT", "Maksimal nettstrøm");
define("_MAINCIRCUITCURRENTERROR", "Maksimal nettstrøm er nødvendig!");
define("_DLMMAXCURRENT", "DLM total strømgrense per fase");
define("_DLMMAXCURRENTERROR", "DLM total strømgrense per fase er påkrevd!");
define("_DLMMAXCURRENTMORETHANMAIN", "DLM total strømgrense bør være mer enn halvparten av hovedkretsbryterstrømmen");
define("_DLMMAXCURRENTLESSTHANMAIN", "DLM total strømgrense skal være mindre enn hovedkretsbryterstrøm");

define("_DHCPSERVER", "DHCP-server");
define("_DHCPCLIENT", "DHCP-klient");

define("_MAXDHCPADDRRANGE", "DHCP-serverens ende-IP-adresse");
define("_MINDHCPADDRRANGE", "DHCP-serverens start-IP-adresse");

define("_MAXDHCPADDRRANGEERROR", "DHCP-serverens ende-IP-adresse kreves!");
define("_MINDHCPADDRRANGEERROR", "DHCP-serverens start-IP-adresse kreves!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "DHCP-serverens ende-IP-adresse skal være større enn DHCP-serverens start-IP-adresse");
define("_IPADDRESSRANGE", "IP-adresse kan ikke ta en verdi mellom DHCP-serverens start- og ende-IP-adresser");
define("_INVALIDSUBNET", "IP-adresse er ikke i det sanne delnettet");

define("_CONNECTIONSTATUS", "Tilkoblingsstatus");

define("_INSTALLATIONSETTINGS", "Installasjons innstillinger");
define("_EARTHINGSYSTEM", "Jordingssystem");
define("_CURRENTLIMITERSETTINGS", "Nåværende begrenserinnstilling");
define("_CURRENTLIMITERPHASE", "Nåværende begrenserfase");
define("_CURRENTLIMITERVALUE", "Nåværende begrenserverdi");
define("_UNBALANCEDLOADDETECTION", "Ubalansert lastdeteksjon");
define("_EXTERNALENABLEINPUT", "Ekstern klarinngang");
define("_LOCKABLECABLE", "Låsbar kabel");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Total strømgrensen for strømoptimaliserer");
define("_POWEROPTIMIZER", "Strømoptimaliserer");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "Énfase");
define("_THREEPHASE", "Trefase");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Strømoptimaliseringens <br> totale strømgrense må være <br> mer enn eller lik 16");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Strømoptimaliseringens <br> totale strømgrense må mindre <br> mer enn eller lik 100");
define("_FOLLOWTHESUN", "Følg solen");
define("_FOLLOWTHESUNMODE", "Følg solmodusen");
define("_AUTOPHASESWITCHING", "Automatisk faseveksling");
define("_MAXHYBRID", "Max hybrid");
define("_SUNONLY", "Kun sol");
define("_SUNHYBRID", "Solhybrid");

define("_DISPLAYBACKLIGHTSETTINGS", "Vise satellittinnstillinger");
define("_BACKLIGHTLEVEL", "Bakgrunnsbelysningsnivå");
define("_SUNRISETIME", "Soloppgangstid ");
define("_SUNSETTIME", "Solnedgangstid");

define("_HIGH", "Høy");
define("_MID", "Mid");
define("_LOW", "Lav");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Når EVReadySupport er på og gjeldende grensefase er én fase, kan ikke gjeldende grenseverdi være mindre enn 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Når EVReadySupport er på og gjeldende grensefase er trefaset, kan ikke gjeldende grenseverdi være mindre enn 14!");
define("_LEDDIMMINGSETTINGS", "Innstillinger for lysdimming");
define("_LEDDIMMINGLEVEL", "ledd dimningsnivå");
define("_VERYLOW", "Veldig lav");

define("_CELLULARGATEWAYCONFIRM", "Cellular Gateway blir deaktivert.");

define("_ETHERNETIP", "Ethernet grensesnitt IP:");
define("_WLANIP", "WLAN-grensesnitt IP:");
define("_STRENGTH", "Styrke");
define("_WIFIFREQ", "Frekvens");
define("_WIFILEVEL", "Nivå");
define("_CELLULARIP", "Mobilgrensesnitt IP:");
define("_CELLULAROPERCODE" , "Operatør");
define("_CELLULARTECH" , "Teknologi");
define("_APPLICATIONRESTART", "Diese Änderung erfordert einen Neustart der Anwendung.");
define("_ACCEPTQUESTION", "Godtar du endringene?");
define("_SCANNETWORKS", "Skann Nettverk");
define("_AVAILABLENETWORKS", "Tilgjengelige Nettverk");
define("_NETWORKSTATUS", "Nettverksstatus");
define("_PLEASEWAITMSG", "Vennligst vent...");
define("_SCANNINGWIFIMSG", "Skanner Wi-Fi Nettverk");
define("_NOWIFIFOUNDMSG", "Ingen Wi-Fi Nettverk Funnet");
define("_PLEASECHECKWIFICONNMSG", "Vennligst sjekk Wi-Fi tilkoblingen og prøv igjen.");

define("_QRCODE", "Vis QR -kode");
define("_QRCODEONSCREEN", "QR -kode på skjermen");
define("_QRCODEDELIMITER", "QR -kode avgrensning");
define("_INVALIDDELIMITERCHARACTER", "QR-kodeskilletegn er ugyldig, blanktegn er ikke akseptabelt, tegnlengden må være minimum 1 og maksimalt 3 tegn, gyldige tegn 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");

define("_LOCATION", "Plassering");
define("_INDOOR", "Innendørs");
define("_OUTDOOR", "Utendørs");
define("_POWEROPTIMIZEREXTERNALMETER", "Ekstern Måler");
define("_OPERATIONMODE", "Driftsmodus");
define("_AUTOSELECTED", "Auto valgt");
define("_NOTSELECTED", "Ikke valgt");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "Lademodusvalg og Power Optimizer-konfigurasjon");

define("_USERINTERACTION", "Interakcja z użytkownikiem");
define("_STANDBYLEDBEHAVIOUR", "Standby LED-oppførsel");
define("_OFF", "Av");
define("_ON", "På");

define("_LOADSHEDDINGMINIMUMCURRENT", "Minimum strøm for belastningsreduksjon");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Ubalansert lastdeteksjon Maks strøm");

define("_SCHEDULEDCHARGING", "Planlagt lading");
define("_OFFPEAKCHARGING", "Off Peak Charging");
define("_OFFPEAKCHARGINGWEEKENDS", "Ladehelger utenfor peak");
define("_OFFPEAKCHARGINGPERIODS", "Ladeperioder utenfor peak");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Fortsett lading etter at toppintervallet er over");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Fortsett lading uten reautentisering etter strømtap");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Randomisert forsinkelse maksimal <br>-varighet (sekunder)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Randomisert forsinkelse Maksimal varighet er nødvendig!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Randomisert forsinkelse Maksimal varighet må være heltall!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Maksimal varighet for randomisert forsinkelse bør være mellom 0 og 1800");
define("_OFFPEAKCHARGINGPERIODSERROR", "* Ladeperioder utenfor peak er påkrevd!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Off Peak Charging Start- og sluttid kan ikke være det samme!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Lade under høye belastninger Andre tidsperiode");
define("_OFFPEAKDISABLEDCONFIRM", "Off-Peak Charging vil bli deaktivert. Vil du bekrefte?");
define("_SHOWSERVICECONTACTINFO", "Vis ekstra servicekontaktinfo");
define("_EXTRASERVICECONTACTINFORMATION", "Tjenestekontaktinformasjon vises på Connect ladekabel, Forbereder for lading, Initialiserer og venter på tilkoblingsskjermer");

define("_LOADSHEDDINGSTATUS", "Belastningsutkoblingsstatus:");
define("_ACTIVE", "Aktiv");
define("_INACTIVE", "Inaktiv");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Hvis du vil bruke alternativet Load Management i Modbus,<br>må du først deaktivere Power Optimizer Total Current Limit<br>fra &#39Lademodusvalg og Power Optimizer Configuration&#39.");
define("_MODBUSALERT", "Hvis du vil aktivere Power Optimizer External Meter,<br>må du først deaktivere Modbus<br>fra &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Hvis du vil bruke Lasthåndteringsalternativet i Master/Slave,<br>må du først deaktivere Kraftoptimalisatoren<br>fra &#39Ladningsmodusvalg og Kraftoptimalisatorkonfigurasjon&#39.");
define("_DLMALERT", "Hvis du vil aktivere Kraftoptimalisatoren din,<br>må du først deaktivere Master/Slave<br>fra &#39Lokal Laststyring&#39.");

define("_FOLLOWTHESUNDLMENABLEALERT", "Hvis du vil bruke Lasthåndteringsalternativet i Master/Slave,<br>må du først deaktivere Følg solen<br>fra &#39Ladningsmodusvalg og Kraftoptimalisatorkonfigurasjon&#39.");
define("_DLMALERTFOLLOWTHESUN", "Hvis du vil aktivere Følg solen din,<br>må du først deaktivere Master/Slave<br>fra &#39Lokal Laststyring&#39.");

define("_RESETUSERPASSWORD", "Tilbakestill <br> brukerpassord");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Hvis du vil deaktivere Installasjonsfeilaktivering,<br>må du først sette jordingssystem fra &#39Installasjonsinnstillinger&#39 til IT/delt fase.");
define("_EARTHINGSYSTEMCONFIRM", "Hvis du vil sette Earthing System til TN/TT,<br>må du først aktivere Installasjonsfeilaktivering fra &#39OCPP Settings&#39.");

define("_AUTHKEYMAXLIMIT", "lengden skal være maksimalt 40 tegn.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Authorization Key-feltet er tomt.<br>Bekrefter du endringene?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Randomisert forsinkelse ved off Peak End");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Feilsikker strøm");
define("_FAILSAFECURRENTERROR", "Feilsikker strøm er påkrevd!");
define("_FAILSAFECURRENTLESSTHAN0", "* Failsafe Gjeldende verdi må ikke være mindre enn 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Failsafe Gjeldende verdi må ikke være mer enn 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Failsafe Gjeldende verdi må ikke være mer enn 50!");

define("_LOCALCHARGESESSION", "lokale ladeokter");
define("_ROWNUMBER", "Rad No");
define("_SESSIONUUID", "lade-ID");
define("_AUTHORIZATIONUID", "RFID-kode");
define("_STARTTIME", "Starttid");
define("_STOPTIME", "Stoppetid");
define("_TOTALTIME", "Totaltid");
define("_STATUS", "Status");
define("_CHARGEPOINTIDS", "Stikkontaktnummer");
define("_INITIALENERGY", "Startenergi(kWh)");
define("_LASTENERGY", "Siste Energi(kWh)");
define("_TOTALENERGY", "Total energi(kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Full sesjonslogg på CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Sammendrag Logg inn CSV");
define("_STARTDATE", "startdato");
define("_ENDDATE", "sluttdato");
define("_RFIDSELECTION", "RFID valg");
define("_CLEAR", "klar");

define("_FALLBACKCURRENT", "Reservestrøm");
define("_FALLBACKRANGE", "Reservestrøm må være 0 eller innenfor området for ");
define("_DOWNLOADEEBUSLOGS", "EEBUS-logger");
define("_PAIRINGENERGYMANAGER", "Aktivert for sammenkobling");
define("_PAIR", "Paraktivering");
define("_UNPAIR", "Unpair");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Fastvareversjon");
define("_EEBUSDISCOVERY", "Oppdagede enheter");
define("_REFRESH", "Oppdater");
define("_CPROLEMASTERREQUIREDFIELD", "Hvis du ønsker å oppdatere innstillinger for laststyringsgruppe, må ladepunktrollen lagres som &#39Master&#39 fra generelle innstillinger for laststyring.");

define("_LISTOFSLAVES", "Liste over slaver");
define("_NUMBEROFSLAVES", "Antall slaver");
define("_LISTOFCONNECTOR", "Liste over koblinger");
define("_AVAILABLECURRENT", "Tilgjengelig gjeldende fase");

define("_DLMINTERFACE", "DLM-grensesnitt");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "Aktiver WiFi fra nettverksgrensesnitt!");

define("_MUSTBEINTEGER", "må være heltall!");
define("_GRIDBUFFER", "Nettbeskyttelsesmarginprosent");
define("_CHARGINGSTATUSALERT", "I ladestatus kan ikke verdien oppdateres!");
define("_READUNDERSTAND", "Jeg har lest, jeg forstår");

define("_MORETHAN10", "Du må øke den maksimale nettstrømmen eller redusere grensen for nettbeskyttelsesmarginen før du lagrer disse innstillingene. Grensen for maksimal nettstrøm kan ikke være lavere enn 10A når du bruker marginprosenten for nettbeskyttelse.");

define("_CLUSTERMAXCURRENT", "Cluster Max Current");
define("_CLUSTERFAILSAFECURRENT", "Cluster Failsafe Current");
define("_CLUSTERMAXCURRENTERROR", "Cluster Max Current er påkrevd!");
define("_CLUSTERFAILSAFECURRENTERROR", "Cluster Failsafe Current kreves!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Cluster Failsafe Gjeldende verdi må ikke være mindre enn 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Cluster Failsafe Current-verdi må være mindre enn Maksimal Grid Current!");
define("_CLUSTERFAILSAFE", "Cluster Failsafe Mode");

define("_CLUSTERMAXCURRENTLESSTHAN10", "Cluster Max Current verdi må ikke være mindre enn 10");
define("_CLUSTERMAXCURRENTMORETHAN", "Cluster Max Current verdi må være lik eller mindre enn denne verdien:");