<?php
include_once "access_control.php";
define("_LOGIN", "CONECTARE");
define("_USERNAME", "Nume utilizator:");
define("_PASSWORD", "Parolă:");
define("_CHANGEPASSWORD", "Schimbarea parolei");
define("_CURRENTPASSWORD", "Parola actuală:");
define("_NEWPASSWORD", "Parola nouă:");
define("_CONFIRMNEWPASSWORD", "Confirmați parola nouă:");
define("_SUBMIT", "Trimitere");
define("_CURRENTPASSWORDREQUIRED", "Parola actuală este obligatorie");
define("_PASSWORDREQUIRED", "Parola este obligatorie");
define("_USERNAMEREQUIRED", "Numele de utilizator este obligatoriu");
define("_USERAUTHFAILED", "Autentificarea utilizatorului nu a reușit!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Numele de utilizator sau parola actuală este greșită!");
define("_DBACCESSFAILURE", "Nu se poate accesa baza de date!");
define("_CHANGEPASSWORDERROR", "Mai întâi trebuie să vă schimbați parola!");
define("_SAMEPASSWORDERROR", "Parola nouă trebuie să fie diferită de parola actuală!");
define("_PASSWORDMATCHERROR", "Parolele nu corespund!");
define("_CURRENTPASSWORDWRONG", "Parola actuală este incorectă!");
define("_PASSWORDERRORLEVEL2", "Parola este nevalidă, lungimea caracterelor trebuie să fie de 20 și să conțină cel puțin două litere [A-Za-z], două cifre [0-9] și două caractere speciale [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Parola este invalidă, lungimea caracterelor trebuie să fie de cel puțin 12, maximum 32 de caractere și să conțină cel puțin două  minuscule [a-z] și două litere mari [A-Z], două numere [0-9] și cel puțin două caractere speciale [!%&/()=?*#+-_].");
define("_LOGINLOCKOUT", "Prea multe încercări nereușite. Vă rugăm să încercați după 1800 de secunde.");

define("_MAINPAGE", "Pagina Principală");
define("_GENERAL", "Setări Generale");
define("_OCPPSETTINGS", "Setări OCPP");
define("_NETWORKINTERFACES", "Interfețe de Rețea ");

define("_OCPPCONNINTERFACE", "Interfață conexiune OCPP:  ");
define("_CONNECTIONSTATE", "Stare conexiune  : ");
define("_DISCONNECTED", "Deconectat");
define("_NEEDTOLOGINFIRST", "Mai întâi trebuie să vă conectați!");
define("_CONNECTED", "Conectat");
define("_CPSERIALNUMBER", "Număr de serie CP : ");
define("_HMISOFTWAREVERSION", "Versiune software HMI : ");
define("_OCPPSOFTWAREVERSION", "Versiune software OCPP : ");
define("_POWERBOARDSOFTWAREVERSION", "Versiune software placă de alimentare  : ");
define("_OCPPDEVICEID", "ID dispozitiv OCPP  : ");
define("_DURATIONAFTERPOWERON", "Durată după pornire  : ");
define("_LOGOUT", "Deconectare");
define("_PRESET", "Pre configurări:");

define("_OCPPCONNECTION", "Conexiune OCPP");
define("_ENABLED", "Activat");
define("_DISABLED", "Dezactivat");
define("_CONNECTIONSETTINGS", "Setări conexiune");
define("_CENTRALSYSTEMADDRESS", "Adresă sistem central ");
define("_CHARGEPOINTID", "ID punct de încărcare ");
define("_OCPPVERSION", "Versiune OCPP");
define("_SAVE", "Salvare");
define("_SAVESUCCESSFUL", "Salvat cu succes.");
define("_CENTRALSYSTEMADDRESSERROR", "Adresa sistemului central este obligatorie!");
define("_CHARGEPOINTIDERROR", "ID-ul punctului de încărcare este obligatoriu!");
define("_SECONDS", "Secunde");
define("_ADD", "Adăugare");
define("_REMOVE", "Eliminare");
define("_SAVECAPITAL", "SALVARE");
define("_CANCEL", "Anulare");

define("_CELLULAR", "Celular");
define("_INTERFACEIPADDRESS", "Interfață Adresă IP: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "Nume APN: ");
define("_APNUSERNAME", "Nume utilizator APN: ");
define("_APNPASSWORD", "Parolă APN: ");
define("_IPSETTING", "Setări IP: ");
define("_IPADDRESS", "Adresa IP: ");
define("_NETWORKMASK", "Mască de rețea: ");
define("_DEFAULTGATEWAY", "Gateway implicit: ");
define("_PRIMARYDNS", "DNS primar: ");
define("_SECONDARYDNS", "DNS secundar: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Securitate: ");
define("_SECURITYTYPE", "Selectare tip securitate");
define("_NONE", "Niciunul");
define("_SELECTMODE", "Vă rugăm să selectați modul!");
define("_RFIDLOCALLIST", "Listă locală RFID");
define("_ACCEPTALLRFIDS", "Acceptați toate dispozitivele RFID");
define("_MANAGERFIDLOCALLIST", "Gestionați lista locală RFID:");
define("_AUTOSTART", "Autostart");
define("_PROCESSING", "În curs de procesare... Vă rugăm să așteptați");
define("_MACADDRESS", "Adresa MAC: ");
define("_WIFIHOTSPOT", "Hotspot Wi-Fi");
define("_TURNONDURINGBOOT", "Porniți în timpul pornirii: ");
define("_AUTOTURNOFFTIMEOUT", "Expirarea automată a opririi: ");
define("_AUTOTURNOFF", "Oprire automată: ");
define("_HOTSPOTALERTMESSAGE", "Modificările setărilor Hotspot vor intra în vigoare la următoarea pornire a dispozitivului. ");
define("_HOTSPOTREBOOTMESSAGE", "Doriți să reporniți acum? ");

define("_DOWNLOADACLOGS", "Descărcare jurnale AC");
define("_DOWNLOADCELLULARLOGS", "Descărcare jurnale modul celular");
define("_DOWNLOADPOWERBOARDLOGS", "Descărcare jurnale placă de alimentare");
define("_PASSWORDRESETSUCCESSFUL", "Parola dvs. a fost resetată cu succes.");
define("_DBOPENEDSUCCESSFULLY", "Baza de date a fost deschisă cu succes\n");
define("_WSSCERTSSETTINGS", "Setări certificate WSS ");
define("_CONFKEYS", "Taste de configurație");
define("_KEY", "Tastă");
define("_STATIC", "Static");
define("_TIMEZONE", "Fus orar");
define("_PLEASESELECTTIMEZONE", "Selectați fusul orar");
define("_DISPLAYSETTINGS", "Setări de afișare");
define("_DISPLAYLANGUAGE", "Limbă de afișare");
define("_BACKLIGHTDIMMING", "Intensitate fundal : ");
define("_PLEASESELECT", "Vă rugăm selectați");
define("_TIMEBASED", "Pe bază de timp");
define("_SENSORBASED", "Pe bază de senzor");
define("_BACKLIGHTDIMMINGLEVEL", "Nivel intensitate fundal : ");
define("_BACKLIGHTTHRESHOLD", "Prag iluminare fundal  : ");
define("_SETMIDTHRESHOLD", "SetMidThreshold");
define("_SETHIGHTHRESHOLD", "SetHighThresold");
define("_LOCALLOADMANAGEMENT", "Gestionare sarcini local");
define("_MINIMUMCURRENT", "Curent minim: ");
define("_FIFOPERCENTAGE", "Procentaj FIFO ");
define("_GRIDMAXCURRENT", "Curent maxim grilă:: ");
define("_MASTERIPADDRESS", "Adresa IP a matriței: ");
define("_BACKLIGHTTIMESETTINGS", "Setări timp lumină de fundal: ");
define("_SHOULDSELECTTIMEZONE", "* Trebuie să selectați fusul orar!");
define("_MINIMUMCURRENTREQUIRED", "* Curentul minim este obligatoriu!");
define("_CURRENTMUSTBENUMERIC", "*  Curentul trebuie să fie numeric!");
define("_FIFOPERCREQUIRED", "* Procentajul FIFO este obligatoriu!");
define("_FIFOPERCSHOULDBETWEEN", "* Procentajul FIFO trebuie să fie cuprins între 0 și 100!");
define("_PERCMUSTBENUMERIC", "* Procentajul trebuie să fie numeric!");
define("_GRIDMAXCURRENTREQUIRED", "* Curentul maxim al grilei este obligatoriu!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Curentul grilei trebuie să fie numeric!");
define("_IPADDRESSOFMASTERREQUIRED", "* Adresa IP a matriței este obligatorie!");
define("_INVALIDIPADDRESS", "* Ați introdus o adresă IP nevalidă!");
define("_SAMENETWORKLAN", "* Ați introdus o adresă IP în aceeași rețea cu LAN!");
define("_SAMENETWORKWLAN", "* Ați introdus o adresă IP în aceeași rețea cu WLAN!");
define("_APNISREQUIRED", "APN este obligatoriu!");
define("_IPADDRESSREQUIRED", "Adresa IP este obligatorie!");
define("_NETWORKMASKREQUIRED", "Masca de rețea este obligatorie!");
define("_INVALIDNETWORKMASK", "* Ați introdus o mască de rețea nevalidă!");
define("_DEFAULTGATEWAYREQUIRED", "Gateway implicit este obligatoriu!");
define("_INVALIDGATEWAY", "Ați introdus un gateway implicit nevalid!");
define("_PRIMARYDNSREQUIRED", "DNS-ul primar este obligatoriu!");
define("_INVALIDDNS", "Ați introdus un DNS nevalid!");
define("_SELECTIPSETTING", "Selectați setările IP.");
define("_SSIDREQUIRED", "SSID este obligatoriu!");
define("_PASSWORDISREQUIRED", "Parola este obligatorie!");
define("_WIFIPASSWORDERROR", "Parola este nevalidă, lungimea caracterelor trebuie să fie de minim 8 și maxim 63 <br> caractere valide a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Parola este nevalidă, lungimea caracterelor trebuie să fie de 20,<br>&#8226; Parola trebuie să conțină cel puțin două litere [A-Za-z],<br>&#8226; Parola trebuie să conțină cel puțin două cifre [0-9],<br>&#8226; Parola trebuie să conțină cel puțin două caractere speciale [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Parola este nevalidă, lungimea caracterelor trebuie să fie de cel puțin 12, maxim 32,<br>&#8226; Parola trebuie să conțină cel puțin două litere mici [a-z], <br>&#8226; Parola trebuie să conțină cel puțin două litere mari [A-Z], <br>&#8226; Parola trebuie să conțină cel puțin două cifre [0-9],<br>&#8226; Parola trebuie să conțină cel puțin două caractere speciale [!%&/()=?*#+-_]");
define("_WIFISSIDERROR", "SSID este invalid, caractere valide a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Selectați tipul de securitate");
define("_HOSTIPREQUIRED", "* IP-ul gazdă este obligatoriu!");
define("_CERTMANREQUIRED", "* Gestionarea certificării este obligatorie!");
define("_OCPPENABLEALERT", "Dacă doriți să utilizați Stația de încărcare în Modul Independent ,<br>mai întâi trebuie să dezactivați conexiunea OCPP<br>din meniul Setări OCPP");
define("_NOTSAVEDALERT", "Pagina nu a fost salvată..");
define("_SAVEQUESTION", "Doriți să salvați modificările?");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Conexiunea celulară va fi dezactivată.  Confirmați?");
define("_WIFICONNECTIONCONFIRM", "Conexiunea Wi-Fi va fi dezactivată.  Confirmați?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Dacă doriți să activați serverul LAN DHCP,<br>mai întâi trebuie să dezactivați Wi-Fi Hotspot<br>din &#39Wi-Fi Hotspot&#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Dacă doriți să activați Hotspot Wi-Fi,<br>mai întâi trebuie să dezactivați LAN DHCP Server<br>din &#39Setarea IP LAN&#39.");

define("_DYNAMIC", "Dinamic");
define("_DIAGNOSTICS", "Diagnosticare");
define("_LOCALLOAD", "Gestionare sarcini locale");
define("_DOWNLOAD", "Descarcă");
define("_STARTDATE", "Data Începerii");
define("_ENDDATE", "Data Sfârșitului");
define("_CLEAREVENTLOGS", "Ștergeți toate jurnalele de evenimente");
define("_CLEAREVENTLOGSINFO", "Aceasta va șterge toate jurnalele de evenimente!");
define("_DOWNLOADEVENTLOGSINFO", "Descarcă jurnalele de evenimente ale dispozitivului pentru o perioadă maximă de 5 zile");
define("_DEVICEEVENTLOGS", "Jurnalele de evenimente ale dispozitivului");
define("_DEVICECHANGELOGS", "Jurnalele modificărilor dispozitivului");
define("_LOGSDATEERROR", "Vă rugăm să selectați date pentru o perioadă maximă de 5 zile.");
define("_DOWNLOACHANGELOGS", "Descarcă jurnalele modificărilor dispozitivului");
define("_VPNFUNCTIONALITY", "Funcționalitate VPN: ");
define("_CERTMANAGEMENT", "Management de certificare: ");
define("_NAME", "Nume: ");
define("_CONNECTIONINTERFACE", "Interfață conexiune");
define("_ANY", "Orice");
define("_OCPPCONNPARAMETERS", "Parametri de configurație OCPP");
define("_SETDEFAULT", "Setare la Implicit  ");
define("_STANDALONEMODE", "Mod independent");
define("_STANDALONEMODETITLE", "Mod independent:");
define("_STANDALONEMODENOTSELECTED", "* Modul Independent nu poate fi selectat deoarece OCPP este activat.");
define("_CHARGERWEBUI", "Interfață utilizator web a stației de încărcare");
define("_SYSTEMMAINTENANCE", "Întreținere sistem");
define("_HOSTIP", "IP-ul gazdă: ");
define("_PASSWORDERRORLEVEL1", "Parola este nevalidă, lungimea caracterelor trebuie să fie de minim 6 caractere și să conțină cel puțin 1 literă minusculă, 1 literă mare și 1 caracter numeric!");
define("_SELECTBACKLIGHTDIMMING", "* Trebuie să selectați intensitatea de fundal!");
define("_ISREQUIRED", "este obligatoriu!");
define("_ISNOTVALID", "nu este valid!");
define("_ISDUPLICATED", "jest zduplikowany!");
define("_MUSTBENUMERIC", "trebuie să fie numeric!");
define("_VPNFUNCTIONALITYREQUIRED", "* Funcționalitatea VPN este obligatorie!");
define("_VPNNAMEREQUIRED", "* Numele VPN este obligatoriu!");
define("_VPNPASSWORDREQUIRED", "* Parola VPN este obligatorie!");
define("_EXPLANATION", "Indică câmpul necesar.");
define("_FIRMWAREUPDATE", "Actualizări firmware");
define("_BACKUPRESTORE", "Backup & Restaurare configurație");
define("_SYSTEMRESET", "Resetare sistem");
define("_CHANGEADMINPASSWORD", "Parolă de administrare");
define("_FACTORYRESET", "Implicit din fabrică");
define("_FACTORYRESETBUTTON", "Resetare la setările din fabrică");
define("_FACTORYDEFAULTCONFIGURATION", "Configurare setări implicite din fabrică");
define("_LOGFILES", "Fișiere jurnal");
define("_BACKUPFILE", "Fișier de backup");
define("_RESTOREFILE", "Restaurare fișier de configurare");
define("_FREEMODEMAXCHARACTER", "trebuie să aibă maximum 32 caractere!");
define("_RESTOREMESSAGE", "Confirmați că aplicați modificările și reporniți acum?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "Parola dvs. trebuie să aibă 6 caractere și să conțină cel puțin o majusculă,
o literă mică și o cifră.");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Parola dvs. trebuie să aibă 20 de caractere și să conțină cel puțin două litere,
două cifre numerice și două caractere speciale.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Parola dvs. trebuie să aibă minimum 12, maximum 32 de caractere și conține cel puțin două
litere mari, două litere mici, două cifre și două caractere speciale.");

define("_BACKTOLOGIN", "Înapoi la conectare");
define("_CHANGE", "Schimbare");
define("_SYSTEMADMINISTRATION", "Administrare sistem");
define("_UPDATE", "Actualizare");
define("_CONFIRM", "Confirmare");
define("_FACTORYDEFAULTCONFIRM", "Sunteți sigur că doriți să resetați la valorile implicite din fabrică?");
define("_FILENAME", "Nume fișier");
define("_UPLOAD", "Încărcare");
define("_SELECTFIRMWARE", "Selectați fișierul Actualizare firmware din calculator");
define("_FIRMWAREFILESIZE", "Verificați dimensiunea fișierului firmware.");
define("_FIRMWAREFILETYPE", "Verificați tipul fișierului firmware.");

define("_LESSTHANOREQUAL4", "trebuie să fie între 1 și 4");
define("_LESSTHANOREQUAL20", "trebuie să fie mai mic sau egal cu 20");
define("_LESSTHANOREQUAL65000", "trebuie să fie mai mic sau egal cu 65000");
define("_LESSTHANOREQUAL300", "trebuie să fie mai mic sau egal cu 300");
define("_LESSTHANOREQUAL86500", "trebuie să fie mai mic sau egal cu 86500");
define("_LESSTHANOREQUAL10000", "trebuie să fie mai mic sau egal cu 10000");
define("_LESSTHANOREQUAL22", "trebuie să fie mai mic sau egal cu 22");
define("_LESSTHANOREQUAL10", "trebuie să fie mai mic sau egal cu 10");
define("_LESSTHANOREQUAL600", "trebuie să fie mai mic sau egal cu 600");
define("_LESSTHANOREQUAL120", "trebuie să fie mai mic sau egal cu 120");
define("_HIGHTHANOREQUAL0", "trebuie să fie mai mare sau egală cu 0");
define("_CHANGEPASSWORDSUGGESTION", "Vă recomandăm să schimbați parola implicită din meniul Întreținere sistem");

define("_FILESIZE", "Verificați dimensiunea fișierului.");
define("_FILETYPE", "Verificați tipul fișierului.");

define("_BACKUPVERSIONCHECK", "Versiunea acestui fișier nu este adecvată pentru dispozitiv..");
define("_HARDRESETCONFIRM", "Sigur doriți Resetare hardware?");
define("_SOFTRESETCONFIRM", "Sigur doriți Resetare software?");
define("_NEWSETUP", "Utilizați manualul utilizatorului pentru noua configurare.");

define("_LOADMANAGEMENT", "Gestionare sarcini");
define("_CPROLE", "Rol Cp");
define("_GRIDSETTINGS", "Setări grilă");
define("_LOADMANAGEMENTMODE", "Mod Gestionare sarcini");
define("_LOADMANAGEMENTGROUP", "Grup Gestionare sarcini");
define("_LOADMANAGEMENTOPTION", "Opțiunea de Gestionare a încărcării");
define("_ALARMS", "Alarme");

define("_LOGOSETTINGS", "Setări siglă");
define("_USELOGO", "Selectați fișierul logo din Pc");
define("_LOGOTYPE", "Vă rugăm să selectați o siglă cu format png.");
define("_LOGODIMENSION", "Dimensiunea maximă admisibilă pentru logo este de 80 x 80, vă rugăm să selectați un logo de dimensiuni adecvate.");

define("_SERVICECONTACTINFO", "Afișați informațiile de contact ale serviciului");
define("_SERVICECONTACTINFOCHARACTER", "Informațiile de contact ale serviciului afișat trebuie să aibă maximum 25 de caractere!<br>Caractere valide a..z 0..9 .+@*");

define("_SCREENTHEME", "Tema Ecranului");
define("_DARKBLUE", "Albastru Inchis");
define("_ORANGE", "Portocale");
define("_PLEASEENTERRFIDLOCALLIST", "Vă rugăm să introduceți lista locală RFID!");

define("_MASTER", "Master (Principal)");
define("_SLAVE", "Slave (Receptor)");
define("_TOTALCURRENTLIMIT", "Limita tensiunii totale per fază");
define("_SUPPLYTYPE", "Tip de alimentare");
define("_FIFOPERCANTAGE", "FIFO Percentage");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Distribuită egal");
define("_COMBINED", "Combinat");
define("_TOTALCURRENTLIMITERROR", "Se solicită limita tensiunii totale per fază!");
define("_LESSTHAN1024", "trebuie să fie mai puțin de 1024");
define("_ATLEAST0","trebuie să fie cel puțin 0");
define("_MORETHAN12", "trebuie să fie mai mult de 12");
define("_CHOOSEONE", "Alegeți o opțiune");
define("_SLAVEMINCHCURRENT", "Setare curentă de încărcare offline pentru siguranță");
define("_SERIALNO", "Număr de serie");
define("_CONNECTORSTATE", "Starea conectorului");
define("_NUMBEROFPHASES", "Număr de faze");
define("_PHASECONSEQUENCE", "Secvența fazei de conectare");
define("_VIP", "Încărcare VIP");
define("_CPMODE", "CP Mode");
define("_VIPERROR", "Se solicită încărcare VIP");
define("_PHASECONSEQUENCEERROR", "Se solicită secvența fazei de conectare!");
define("_CPMODEERROR", "Se solicită modul CP!");
define("_SUPPORTEDCURRENT", "Tensiune suportată");
define("_INSTANTCURPERPHASE", "Faza tensiunii instantanee");
define("_FIFOCHARGINGPERCENTAGE", "Procent de încărcare FIFO");
define("_MINIMUMCURRENT1P", "Nivel minim al tensiunii de încărcare pe 1 fază");
define("_MINIMUMCURRENT3P", "Nivel minim al tensiunii de încărcare pe 3 faze");
define("_MAXIMUMCURRENT", "Tensiunea maximă de încărcare");
define("_STEP", "Etapă");
define("_UPDATEDLMGROUP", "Actualizarea grupului DLM");
define("_MAINCIRCUITCURRENT", "Curentul maxim al rețelei");
define("_MAINCIRCUITCURRENTERROR", "Este necesar curentul maxim al rețelei!");
define("_DLMMAXCURRENT", "Limita de curent total DLM pe fază");
define("_DLMMAXCURRENTERROR", "Limita totală de curent DLM pe fază este necesară!");
define("_DLMMAXCURRENTMORETHANMAIN", "Limita de curent total DLM ar trebui să fie mai mult de jumătate din curentul întreruptorului principal");
define("_DLMMAXCURRENTLESSTHANMAIN", "Limita de curent total DLM ar trebui să fie mai mică decât curentul întreruptorului principal");

define("_DHCPSERVER", "Server DHCP");
define("_DHCPCLIENT", "Client DHCP");

define("_MAXDHCPADDRRANGE", "Adresa IP finală a serverului DHCP");
define("_MINDHCPADDRRANGE", "Adresa IP de pornire a serverului DHCP");

define("_MAXDHCPADDRRANGEERROR", "Se solicită adresa IP finală a serverului DHCP!");
define("_MINDHCPADDRRANGEERROR", "Se solicită adresa IP de început a serverului DHCP!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "Adresa IP finală a serverului DHCP trebuie să fie mai mare decât adresa IP de început a serverului DHCP");
define("_IPADDRESSRANGE", "Adresa IP nu poate lua o valoare între adresele IP de început și finală a serverului DHCP");
define("_INVALIDSUBNET", "Adresa IP nu se regăsește în subrețea validă");
define("_CELLULARGATEWAY", "Gateway Celular");
define("_CONNECTIONSTATUS", "Starea Conexiunii");

define("_INSTALLATIONSETTINGS", "Configurări de instalare");
define("_EARTHINGSYSTEM", "Sistem de pământare");
define("_CURRENTLIMITERSETTINGS", "Configurarea limitei de tensiune");
define("_CURRENTLIMITERPHASE", "Faza limitei de tensiune");
define("_CURRENTLIMITERVALUE", "Valoarea limitei de tensiune");
define("_UNBALANCEDLOADDETECTION", "Detecția încărcării dezechilibrate");
define("_EXTERNALENABLEINPUT", "Intrare pentru activare externă");
define("_LOCKABLECABLE", "Cablu blocabil");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Limita totală de tensiune a optimizatorului de putere");
define("_POWEROPTIMIZER", "Optimizator de putere");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "Monofazat");
define("_THREEPHASE", "Trifazat");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Limita totală de tensiune a <br> optimizatorului de putere trebuie <br> să fie mai mare sau egală cu 16");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Limita totală de tensiune a <br> optimizatorului de putere trebuie <br> să fie mai mică sau egală cu 100");
define("_FOLLOWTHESUN", "Urmaresc soarele");
define("_FOLLOWTHESUNMODE", "Urmați modul soare");
define("_AUTOPHASESWITCHING", "Comutare automată de fază");
define("_MAXHYBRID", "Hibrid maxim");
define("_SUNONLY", "Doar soarele");
define("_SUNHYBRID", "Hibrid de soare");

define("_DISPLAYBACKLIGHTSETTINGS", "Configurarea iluminării de fundal a ecranului");
define("_BACKLIGHTLEVEL", "Nivelul iluminării de fundal");
define("_SUNRISETIME", "Ora răsăritului ");
define("_SUNSETTIME", "Ora apusului");

define("_HIGH", "Puternic");
define("_MID", "Mediu");
define("_LOW", "Scăzut");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Când EVReadySupport este activat și faza limită curentă este o fază, valoarea limită curentă nu poate fi mai mică de 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Când EVReadySupport este activat și faza limită de curent este trifazată, valoarea limită de curent nu poate fi mai mică de 14!");
define("_LEDDIMMINGSETTINGS", "Setări de estompare cu LED-uri");
define("_LEDDIMMINGLEVEL", "Nivel de estompare cu LED-uri");
define("_VERYLOW", "Foarte Scăzut");
define("_WARNINGFORLTEENABLED", "Modul de setare IP al interfeței LAN va fi setat ca static și serverul DHCP va fi activat.");
define("_WARNINGFORLTEDISABLED", "Modul de setare IP a interfeței LAN va fi setat ca DHCP Client și serverul DHCP va fi inactivat.");
define("_ACCEPTQUESTION", "Acceptați modificările?");

define("_CELLULARGATEWAYCONFIRM", "Gateway-ul celular va fi dezactivat.");

define("_ETHERNETIP", "IP interfață Ethernet:");
define("_WLANIP", "WLAN Interface IP:");
define("_STRENGTH", "Putere");
define("_WIFIFREQ", "Frecvență");
define("_WIFILEVEL", "Nivel");
define("_CELLULARIP", "IP interfață celulară:");
define("_CELLULAROPERCODE" , "Operator");
define("_CELLULARTECH" , "Tehnologie");
define("_SCANNETWORKS" , "Scanare rețele");
define("_AVAILABLENETWORKS" , "Rețele disponibile");
define("_NETWORKSTATUS" , "Stare rețea");
define("_PLEASEWAITMSG" , "Vă rugăm să așteptați...");
define("_SCANNINGWIFIMSG" , "Se scanează rețelele Wi-Fi");
define("_NOWIFIFOUNDMSG" , "Nu s-au găsit rețele Wi-Fi");
define("_PLEASECHECKWIFICONNMSG" , "Vă rugăm să verificați conexiunea Wi-Fi și să încercați din nou.");

define("_APPLICATIONRESTART", "Această modificare necesită repornirea aplicației.");

define("_QRCODE", "Afișați Codul QR");
define("_QRCODEONSCREEN", "Cod QR pe Ecran");
define("_QRCODEDELIMITER", "Delimitator de cod QR");
define("_INVALIDDELIMITERCHARACTER", "Caracterul delimitator al codului QR este invalid, caracterul de spațiu alb nu este acceptabil, lungimea caracterelor trebuie să fie de minim 1 și maxim 3 caractere, caractere valide 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");

define("_LOCATION", "Locație");
define("_INDOOR", "De interior");
define("_OUTDOOR", "În aer liber");
define("_POWEROPTIMIZEREXTERNALMETER", "Contor Extern");
define("_OPERATIONMODE", "Mod De Operare");
define("_AUTOSELECTED", "Selectat automat");
define("_NOTSELECTED", "Nu a fost selectat");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "Selecția modului de încărcare și configurarea Power Optimizer");

define("_USERINTERACTION", "Interacțiunea cu utilizatorul");
define("_STANDBYLEDBEHAVIOUR", "Comportament LED de așteptare");
define("_OFF", "Dezactivat");
define("_ON", "Activați");

define("_LOADSHEDDINGMINIMUMCURRENT", "Curent minim de reducere a sarcinii");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Curent maxim de detectare a sarcinii dezechilibrate");

define("_SCHEDULEDCHARGING", "Încărcare programată");
define("_OFFPEAKCHARGING", "Încărcare în afara vârfului");
define("_OFFPEAKCHARGINGWEEKENDS", "În weekenduri de încărcare în afara vârfului");
define("_OFFPEAKCHARGINGPERIODS", "Perioade de încărcare în afara vârfului");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Continuă încărcarea la sfârșitul intervalului de vârf");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Continuă încărcarea fără reautorizare după pierderea energiei");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Întârziere aleatorie <br> maximă Durată (secunde)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Durata maximă de întârziere aleatorie este necesară!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Durata maximă de întârziere aleatorie trebuie să fie întreagă!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Durata maximă de întârziere aleatorie ar trebui să fie între 0 și 1800");
define("_OFFPEAKCHARGINGPERIODSERROR", "* Sunt necesare perioade de încărcare în afara vârfului!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Ora de pornire și de terminare a încărcării în afara vârfului nu poate fi aceeași!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Încărcare în afara vârfului a doua perioadă de timp");
define("_OFFPEAKDISABLEDCONFIRM", "Încărcarea în afara vârfului va fi dezactivată. Confirmați?");
define("_SHOWSERVICECONTACTINFO", "Afișați informații suplimentare de contact pentru servicii");
define("_EXTRASERVICECONTACTINFORMATION", "Informațiile de contact ale serviciului sunt afișate pe ecranele Conectare cablu de încărcare, Pregătire pentru încărcare, Inițializare și așteptare pentru conexiune");

define("_LOADSHEDDINGSTATUS", "Stare de descărcare a încărcăturii:");
define("_ACTIVE", "Activ");
define("_INACTIVE", "Inactiv");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Dacă doriți să utilizați opțiunea de gestionare a încărcăturii în Modbus,<br>mai întâi trebuie să dezactivați Limita de curent total a Optimizatorului de putere<br>din &#39Selectarea modului de încărcare și Configurarea Optimizatorului de putere&#39.");
define("_MODBUSALERT", "Dacă doriți să activați contorul extern Power Optimizer,<br>mai întâi trebuie să dezactivați Modbus<br>de la &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Dacă doriți să utilizați Opțiunea de gestionare a încărcăturii în Modul Master/Slave,<br>trebuie mai întâi să dezactivați Optimizatorul de putere<br>din &#39Selectarea modului de încărcare și configurarea optimizatorului de putere&#39.");
define("_DLMALERT", "Dacă doriți să activați Optimizatorul de putere,<br>trebuie mai întâi să dezactivați Master/Slave<br>din &#39Gestionarea locală a încărcăturii&#39.");

define("_FOLLOWTHESUNDLMENABLEALERT", "Dacă doriți să utilizați Opțiunea de gestionare a încărcăturii în Modul Master/Slave,<br>trebuie mai întâi să dezactivați Urmaresc soarele<br>din &#39Selectarea modului de încărcare și configurarea optimizatorului de putere&#39.");
define("_DLMALERTFOLLOWTHESUN", "Dacă doriți să activați Urmaresc soarele,<br>trebuie mai întâi să dezactivați Master/Slave<br>din &#39Gestionarea locală a încărcăturii&#39.");

define("_RESETUSERPASSWORD", "Resetați parola <br> utilizatorului");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Dacă doriți să dezactivați Activarea erorii de instalare,<br>mai întâi trebuie să setați Sistemul de împământare de la &#39Setări de instalare&#39 la Faza IT/Split.");
define("_EARTHINGSYSTEMCONFIRM", "Dacă doriți să setați sistemul de împământare la TN/TT,<br>mai întâi trebuie să activați Activarea erorii de instalare din &#39Setări OCPP&#39.");

define("_AUTHKEYMAXLIMIT", "lungimea trebuie să fie de maximum 40 de caractere.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Câmpul Authorization Key este gol.<br>Confirmați modificările?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Întârziere randomizată la sfârșitul de vârf");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Curent de siguranță");
define("_FAILSAFECURRENTERROR", "Este necesar un curent de siguranță!");
define("_FAILSAFECURRENTLESSTHAN0", "* Valoarea curentului de siguranță nu trebuie să fie mai mică de 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Valoarea curentului de siguranță nu trebuie să fie mai mare de 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Valoarea curentului de siguranță nu trebuie să fie mai mare de 50!");

define("_LOCALCHARGESESSION", "Sesiuni de taxare locale");
define("_ROWNUMBER", "Rând nr");
define("_SESSIONUUID", "id-ul taxei");
define("_AUTHORIZATIONUID", "cod rfid");
define("_STARTTIME", "Timp de începere");
define("_STOPTIME", "Timp de oprire");
define("_TOTALTIME", "Timp total");
define("_STATUS", "Stare");
define("_CHARGEPOINTIDS", "Numărul prizei");
define("_INITIALENERGY", "Energia Inițială(kWh)");
define("_LASTENERGY", "Energia Ultima(kWh)");
define("_TOTALENERGY", "Energia totală (kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Înregistrare sesiune completă în CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Jurnal rezumat în format CSV");
define("_STARTDATE", "data de început");
define("_ENDDATE", "Data de încheiere");
define("_RFIDSELECTION", "selecție RFID");
define("_CLEAR", "clar");

define("_FALLBACKCURRENT", "Current de rezervă");
define("_FALLBACKRANGE", "Curentul de rezervă trebuie să fie 0 sau în intervalul de ");
define("_DOWNLOADEEBUSLOGS", "EEBUS Logs");
define("_PAIRINGENERGYMANAGER", "Activat pentru asociere");
define("_PAIR", "Pereche activată");
define("_UNPAIR", "Anulare");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Versiune firmware");
define("_EEBUSDISCOVERY", "Dispozitive descoperite");
define("_REFRESH", "Actualizează");
define("_CPROLEMASTERREQUIREDFIELD", "Dacă doriți să actualizați setările grupului de gestionare a încărcăturii, rolul punctului de încărcare trebuie salvat ca &#39Master&#39 din setările generale de gestionare a încărcăturii.");

define("_LISTOFSLAVES", "Lista sclavilor");
define("_NUMBEROFSLAVES", "Numărul de sclavi");
define("_LISTOFCONNECTOR", "Lista conectorilor");
define("_AVAILABLECURRENT", "Faza curentă disponibilă");

define("_DLMINTERFACE", "Interfață DLM");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "Activați WiFi din interfețele de rețea!");

define("_MUSTBEINTEGER", "trebuie sa fie intreg!");
define("_GRIDBUFFER", "Procentajul marjei de protecție a rețelei");
define("_CHARGINGSTATUSALERT", "În starea de încărcare, valoarea nu poate fi actualizată!");
define("_READUNDERSTAND", "Am citit, înțeleg");

define("_MORETHAN10", "Trebuie să măriți curentul maxim al rețelei sau să micșorați procentajul marjei de protecție a rețelei înainte de a salva aceste setări. Limita maximă a curentului rețelei nu poate fi mai mică de 10A când utilizați procentul marjei protecției rețelei.");

define("_CLUSTERMAXCURRENT", "Curentul maxim al clusterului");
define("_CLUSTERFAILSAFECURRENT", "Cluster Failsafe Current");
define("_CLUSTERMAXCURRENTERROR", "Curentul maxim al clusterului este necesar!");
define("_CLUSTERFAILSAFECURRENTERROR", "Cluster Failsafe Current este necesar!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Valoarea curentului Cluster Failsafe nu trebuie să fie mai mică de 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Valoarea curentului Cluster Failsafe trebuie să fie mai mică decât Curentul maxim al rețelei!");
define("_CLUSTERFAILSAFE", "Mod Cluster Failsafe");

define("_CLUSTERMAXCURRENTLESSTHAN10", "Valoarea curentă maximă a clusterului nu trebuie să fie mai mică de 10");
define("_CLUSTERMAXCURRENTMORETHAN", "Valoarea curentului maxim al clusterului trebuie să fie egală sau mai mică decât această valoare:");