<?php
include_once "access_control.php";
define("_LOGIN", "PRIHLÁSIŤ SA");
define("_USERNAME", "Užívateľské meno:");
define("_PASSWORD", "Heslo:");
define("_CHANGEPASSWORD", "Zmeniť heslo");
define("_CURRENTPASSWORD", "Súčasné heslo:");
define("_NEWPASSWORD", "Nové heslo:");
define("_CONFIRMNEWPASSWORD", "Potvrďte nové heslo:");
define("_SUBMIT", "Odoslať");
define("_CURRENTPASSWORDREQUIRED", "Je potrebné aktuálne heslo");
define("_PASSWORDREQUIRED", "Heslo je povinné");
define("_USERNAMEREQUIRED", "Používateľské meno je povinné");
define("_USERAUTHFAILED", "Overenie používateľa zlyhalo!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Používateľské meno alebo aktuálne heslo je nesprávne!");
define("_DBACCESSFAILURE", "Nie je možný prístup do databázy!");
define("_CHANGEPASSWORDERROR", "Najprv musíte zmeniť svoje heslo!");
define("_SAMEPASSWORDERROR", "Aktuálne a nové heslo by sa musia navzájom líšiť!");
define("_PASSWORDMATCHERROR", "Heslá sa nezhodujú!");
define("_CURRENTPASSWORDWRONG", "Aktuálne heslo je nesprávne!");
define("_PASSWORDERRORLEVEL2", "Heslo je neplatné, dĺžka znakov musí byť 20 a musí obsahovať aspoň dve písmená [A-Za-z], dve číslice [0-9] a dva špeciálne znaky [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Heslo je neplatné, dĺžka znakov musí byť aspoň 12, maximálne 32 znakov a musí obsahovať aspoň dve malé písmená [a-z] a dve veľké písmená [A-Z], dve čísla [0-9] a aspoň dva špeciálne znaky [!%&/()=?*#+-_].");
define("_LOGINLOCKOUT", "Príliš veľa neúspešných pokusov. Skúste to po 1800 sekundách.");

define("_MAINPAGE", "Hlavná stránka");
define("_GENERAL", "Všeobecné nastavenia");
define("_OCPPSETTINGS", "Nastavenia OCPP");
define("_NETWORKINTERFACES", "Sieťové rozhrania");

define("_OCPPCONNINTERFACE", "Rozhranie OCPP pripojenia : ");
define("_CONNECTIONSTATE", "Stav pripojenia : ");
define("_DISCONNECTED", "Odpojený");
define("_NEEDTOLOGINFIRST", "Najprv sa musíte prihlásiť!");
define("_CONNECTED", "Pripojený");
define("_CPSERIALNUMBER", "Sériové číslo CP : ");
define("_HMISOFTWAREVERSION", "Verzia HMI softvéru : ");
define("_OCPPSOFTWAREVERSION", "Verzia OCPP softvéru : ");
define("_POWERBOARDSOFTWAREVERSION", "Verzia softvéru napájacej dosky : ");
define("_OCPPDEVICEID", "ID OCPP zariadenia : ");
define("_DURATIONAFTERPOWERON", "Doba po zapnutí : ");
define("_LOGOUT", "Odhlásiť sa");
define("_PRESET", "Prednastavenia:");

define("_OCPPCONNECTION", "OCPP pripojenia");
define("_ENABLED", "Povolené");
define("_DISABLED", "Deaktivované");
define("_CONNECTIONSETTINGS", "Nastavenia pripojenia");
define("_CENTRALSYSTEMADDRESS", "Adresa centrálneho systému ");
define("_CHARGEPOINTID", "ID nabíjacieho bodu ");
define("_OCPPVERSION", "Verzia OCPP");
define("_SAVE", "Uložiť");
define("_SAVESUCCESSFUL", "Úspešne uložené.");
define("_CENTRALSYSTEMADDRESSERROR", "Vyžaduje sa adresa centrálneho systému!");
define("_CHARGEPOINTIDERROR", "Vyžaduje sa ID nabíjacieho bodu!");
define("_SECONDS", "Sekundy");
define("_ADD", "Pridať");
define("_REMOVE", "Odstrániť");
define("_SAVECAPITAL", "ULOŽIŤ");
define("_CANCEL", "Zrušiť");

define("_CELLULAR", "Mobil");
define("_INTERFACEIPADDRESS", "IP adresa rozhrania: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "Názov APN: ");
define("_APNUSERNAME", "Používateľské meno APN: ");
define("_APNPASSWORD", "Heslo APN: ");
define("_IPSETTING", "IP nastavenia: ");
define("_IPADDRESS", "IP adresa: ");
define("_NETWORKMASK", "Maska siete: ");
define("_DEFAULTGATEWAY", "Predvolená brána: ");
define("_PRIMARYDNS", "Primárny DNS: ");
define("_SECONDARYDNS", "Sekundárny DNS: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Bezpečnosť: ");
define("_SECURITYTYPE", "Vyberte typ zabezpečenia");
define("_NONE", "Žiadne");
define("_SELECTMODE", "Vyberte Režim, prosím!");
define("_RFIDLOCALLIST", "Miestny zoznam RFID");
define("_ACCEPTALLRFIDS", "Prijať všetky RFID");
define("_MANAGERFIDLOCALLIST", "Spravovať miestny zoznam RFID:");
define("_AUTOSTART", "Automatický štart");
define("_PROCESSING", "Spracovanie... Čakajte, prosím...");
define("_MACADDRESS", "MAC adresa: ");
define("_WIFIHOTSPOT", "Hotspot Wi-Fi");
define("_TURNONDURINGBOOT", "Zapnite počas bootovania: ");
define("_AUTOTURNOFFTIMEOUT", "Časový limit automatického vypnutia: ");
define("_AUTOTURNOFF", "Automatické vypnutie: ");
define("_HOTSPOTALERTMESSAGE", "Zmeny nastavenia hotspotu sa prejavia pri ďalšom zapnutí zariadenia. ");
define("_HOTSPOTREBOOTMESSAGE", "Chcete sa teraz reštartovať? ");

define("_DOWNLOADACLOGS", "Stiahnuť AC protokoly");
define("_DOWNLOADCELLULARLOGS", "Stiahnuť protokoly mobilných modulov");
define("_DOWNLOADPOWERBOARDLOGS", "Stiahnuť denníky napájacej dosky");
define("_PASSWORDRESETSUCCESSFUL", "Vaše heslo bolo úspešne obnovené.");
define("_DBOPENEDSUCCESSFULLY", "Databáza bola úspešne otvorená\n");
define("_WSSCERTSSETTINGS", "Nastavenia WSS certifikátov ");
define("_CONFKEYS", "Konfiguračné klávesy");
define("_KEY", "Kláves");
define("_STATIC", "Statický");
define("_TIMEZONE", "Časové pásmo");
define("_PLEASESELECTTIMEZONE", "Vyberte Časové pásmo, prosím");
define("_DISPLAYSETTINGS", "Nastavenia displeja");
define("_DISPLAYLANGUAGE", "Jazyk displeja");
define("_BACKLIGHTDIMMING", "Tlmenie spätného svetla : ");
define("_PLEASESELECT", "Prosím, zvolte si");
define("_TIMEBASED", "Na základe času");
define("_SENSORBASED", "Na základe senzora");
define("_BACKLIGHTDIMMINGLEVEL", "Úroveň tlmenia spätného svetla : ");
define("_BACKLIGHTTHRESHOLD", "Prahová hodnota podsvietenia : ");
define("_SETMIDTHRESHOLD", "Nastaviť strednú prahovú hodnotu");
define("_SETHIGHTHRESHOLD", "Nastaviť vysokú prahovú hodnotu");
define("_LOCALLOADMANAGEMENT", "Riadenie Miestneho zaťaženia");
define("_MINIMUMCURRENT", "Minimálny prúd: ");
define("_FIFOPERCENTAGE", "Percento FIFO:: ");
define("_GRIDMAXCURRENT", "Maximálny prúd v sieti: ");
define("_MASTERIPADDRESS", "IP adresa hlavného servera: ");
define("_BACKLIGHTTIMESETTINGS", "Časové nastavenia Podsvietenia: ");
define("_SHOULDSELECTTIMEZONE", "* Musíte zvoliť časové pásmo!");
define("_MINIMUMCURRENTREQUIRED", "* Vyžaduje sa minimálny prúd!");
define("_CURRENTMUSTBENUMERIC", "* Prúd musí byť číselný!");
define("_FIFOPERCREQUIRED", "* Vyžaduje sa percento FIFO!");
define("_FIFOPERCSHOULDBETWEEN", "* Percento FIFO musí byť medzi 0 a 100!");
define("_PERCMUSTBENUMERIC", "* Percento musí byť číselné!");
define("_GRIDMAXCURRENTREQUIRED", "* Vyžaduje sa maximálny prúd v sieti!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Prúd v sieti musí byť číselný!");
define("_IPADDRESSOFMASTERREQUIRED", "* Vyžaduje sa IP adresa hlavného servera!");
define("_INVALIDIPADDRESS", "* Zadali ste neplatnú IP adresu!");
define("_SAMENETWORKLAN", "* Zadali ste IP adresu v rovnakej sieti ako LAN!");
define("_SAMENETWORKWLAN", "* Zadali ste IP adresu v rovnakej sieti ako WLAN!");
define("_APNISREQUIRED", "Vyžaduje sa APN!");
define("_IPADDRESSREQUIRED", "Vyžaduje sa IP adresa!");
define("_NETWORKMASKREQUIRED", "Vyžaduje sa maska siete!");
define("_INVALIDNETWORKMASK", "* Zadali ste neplatnú Masku siete!");
define("_DEFAULTGATEWAYREQUIRED", "Vyžaduje sa Predvolená brána!");
define("_INVALIDGATEWAY", "Zadali ste neplatnú Predvolenú bránu!");
define("_PRIMARYDNSREQUIRED", "Vyžaduje sa primárne dns!");
define("_INVALIDDNS", "Zadali ste neplatnú dns!");
define("_SELECTIPSETTING", "Zvoľte IP nastavenie, prosím.");
define("_SSIDREQUIRED", "Vyžaduje sa SSID!");
define("_PASSWORDISREQUIRED", "Vyžaduje sa heslo!");
define("_WIFIPASSWORDERROR", "Heslo je neplatné, dĺžka znakov musí byť minimálne 8 a maximálne 63 <br> platných znakov a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Heslo je neplatné, dĺžka znakov musí byť 20,<br>&#8226; Heslo musí obsahovať aspoň dve písmená [A-Za-z],<br>&#8226; Heslo musí obsahovať aspoň dve číslice [0-9],<br>&#8226; Heslo musí obsahovať aspoň dva špeciálne znaky [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Heslo je neplatné, dĺžka znakov musí byť aspoň 12, maximálne 32,<br>&#8226; Heslo musí obsahovať aspoň dve malé písmená [a-z], <br>&#8226; Heslo musí obsahovať aspoň dve veľké písmená [A-Z], <br>&#8226; Heslo musí obsahovať aspoň dve číslice [0-9],<br>&#8226; Heslo musí obsahovať aspoň dva špeciálne znaky [!%&/()=?*#+-_]");
define("_WIFISSIDERROR", "SSID je neplatný, platné znaky a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Vyberte typ zabezpečenia");
define("_HOSTIPREQUIRED", "* Vyžaduje sa IP hostiteľa!");
define("_CERTMANREQUIRED", "* Vyžaduje sa Správa certifikácie!");
define("_OCPPENABLEALERT", "Ak chcete svoju Nabíjaciu stanicu používať v samostatnom režime,<br>musíte najskôr deaktivovať pripojenie OCPP v ponuke nastavení OCPP.");
define("_NOTSAVEDALERT", "Stránka nebola uložená.");
define("_SAVEQUESTION", "Chcete uložiť zmeny?");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Mobilné pripojenie bude zakázané. Potvrdiť?");
define("_WIFICONNECTIONCONFIRM", "Pripojenie Wi-Fi bude zakázané. Potvrdiť?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Ak chcete povoliť server LAN DHCP,<br>musíte najskôr vypnúť Wi-Fi hotspot z &#39Wi-Fi hotspotu&#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Ak chcete povoliť Wi-Fi hotspot,<br>musíte najskôr zakázať server LAN DHCP v časti &#39Nastavenie IP siete LAN&#39.");

define("_DYNAMIC", "Dynamický");
define("_DIAGNOSTICS", "Diagnostika");
define("_LOCALLOAD", "Riadenie Miestneho zaťaženia");
define("_DOWNLOAD", "Stiahnuť");
define("_STARTDATE", "Dátum začiatku");
define("_ENDDATE", "Dátum konca");
define("_CLEAREVENTLOGS", "Vymazať všetky záznamy udalostí");
define("_CLEAREVENTLOGSINFO", "Týmto sa vymažú všetky záznamy udalostí!");
define("_DOWNLOADEVENTLOGSINFO", "Stiahnuť záznamy udalostí zariadenia na maximálne 5 dní");
define("_DEVICEEVENTLOGS", "Záznamy udalostí zariadenia");
define("_DEVICECHANGELOGS", "Záznamy zmien zariadenia");
define("_LOGSDATEERROR", "Vyberte prosím dátumy na maximálne 5 dní.");
define("_DOWNLOACHANGELOGS", "Stiahnuť záznamy zmien zariadenia");
define("_VPNFUNCTIONALITY", "Funkcia VPN: ");
define("_CERTMANAGEMENT", "Správa certifikácie: ");
define("_NAME", "Názov: ");
define("_CONNECTIONINTERFACE", "Rozhranie pripojenia ");
define("_ANY", "Akékoľvek");
define("_OCPPCONNPARAMETERS", "Konfiguračné parametre OCPP");
define("_SETDEFAULT", "Nastaviť ako predvolené ");
define("_STANDALONEMODE", "Samostatný režim");
define("_STANDALONEMODETITLE", "Samostatný režim:");
define("_STANDALONEMODENOTSELECTED", "* Samostatný režim nie je možné zvoliť, pretože je povolený OCPP.");
define("_CHARGERWEBUI", "Webové užívateľské rozhranie nabíjačky");
define("_SYSTEMMAINTENANCE", "Údržba systému");
define("_HOSTIP", "Hostiteľská IP adresa: ");
define("_PASSWORDERRORLEVEL1", "Heslo je neplatné, dĺžka znakov musí byť minimálne 6 znakov a musí obsahovať aspoň 1 malé písmeno, 1 veľké písmeno a 1 číselný znak!");
define("_SELECTBACKLIGHTDIMMING", "* Musíte zvoliť stlmenie podsvietenia!");
define("_ISREQUIRED", "je povinné!");
define("_ISNOTVALID", "nie je platné!");
define("_ISDUPLICATED", "je dupliciran!");
define("_MUSTBENUMERIC", "musí byť číselné!");
define("_VPNFUNCTIONALITYREQUIRED", "* Vyžaduje sa funkcia VPN!");
define("_VPNNAMEREQUIRED", "* Je potrebné uviesť názov VPN!");
define("_VPNPASSWORDREQUIRED", "* Je potrebné heslo VPN!");
define("_EXPLANATION", "Je potrebné uviesť heslo VPN.");
define("_FIRMWAREUPDATE", "Aktualizácie firmvéru");
define("_BACKUPRESTORE", "Zálohovanie a obnovenie konfigurácie");
define("_SYSTEMRESET", "Reset systému");
define("_CHANGEADMINPASSWORD", "Heslo administrátora");
define("_FACTORYRESET", "Predvolené hodnoty od výrobcu");
define("_FACTORYRESETBUTTON", "Resetovanie na hodnoty od výrobcu");
define("_FACTORYDEFAULTCONFIGURATION", "Konfigurácia na hodnoty od výrobcu");
define("_LOGFILES", "Súbory denníka");
define("_BACKUPFILE", "Záložný súbor");
define("_RESTOREFILE", "Obnoviť konfiguračný súbor");
define("_FREEMODEMAXCHARACTER", "musí mať maximálne 32 znakov!");
define("_RESTOREMESSAGE", "Potvrdzujete, že chcete použiť zmeny a reštartovať teraz?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "Vaše heslo musí mať aspoň 6 znakov a musí obsahovať aspoň jedno veľké
písmeno, jedno malé písmeno a jednu číslicu.");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Vaše heslo musí mať 20 znakov a musí obsahovať aspoň dve písmená,
dve číslice a dva špeciálne znaky.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Vaše heslo musí mať minimálne 12, maximálne 32 znakov a musí obsahovať minimálne dve veľké písmená,
dve malé písmená, dve číslice a dva špeciálne znaky.");

define("_BACKTOLOGIN", "Späť na Prihlásenie");
define("_CHANGE", "Change");
define("_SYSTEMADMINISTRATION", "Správa systému");
define("_UPDATE", "Aktualizácia");
define("_CONFIRM", "Potvrdiť");
define("_FACTORYDEFAULTCONFIRM", "Naozaj chcete obnoviť pôvodné výrobné nastavenia?");
define("_FILENAME", "Názov súboru");
define("_UPLOAD", "Nahranie");
define("_SELECTFIRMWARE", "Vyberte súbor s aktualizáciou firmvéru z PC");
define("_FIRMWAREFILESIZE", "Skontrolujte veľkosť súboru s firmvérom.");
define("_FIRMWAREFILETYPE", "Skontrolujte typ súboru s firmvérom.");

define("_LESSTHANOREQUAL4", "musí byť medzi 1 a 4");
define("_LESSTHANOREQUAL20", "musí byť menší alebo rovný 20");
define("_LESSTHANOREQUAL65000", "musí byť menší alebo rovný 65000");
define("_LESSTHANOREQUAL300", "musí byť menší alebo rovný 300");
define("_LESSTHANOREQUAL86500", "musí byť menší alebo rovný 86500");
define("_LESSTHANOREQUAL10000", "musí byť menší alebo rovný 10000");
define("_LESSTHANOREQUAL22", "musí byť menší alebo rovný 22");
define("_LESSTHANOREQUAL10", "musí byť menší alebo rovný 0");
define("_LESSTHANOREQUAL600", "musí byť menší alebo rovný 600");
define("_LESSTHANOREQUAL120", "musí byť menší alebo rovný 120");
define("_HIGHTHANOREQUAL0", "musí byť vyššia alebo rovná 0");
define("_CHANGEPASSWORDSUGGESTION", "Odporúčame vám zmeniť si predvolené heslo v ponuke údržby systému");

define("_FILESIZE", "Skontrolujte veľkosť súboru.");
define("_FILETYPE", "Skontrolujte typ súboru.");

define("_BACKUPVERSIONCHECK", "Verzia tohto súboru nie je pre zariadenie vhodná.");
define("_HARDRESETCONFIRM", "Naozaj chcete uskutočniť Tvrdý reset?");
define("_SOFTRESETCONFIRM", "Naozaj chcete uskutočniť jemný reset?");
define("_NEWSETUP", "Pre nové nastavenie použite príručku používateľa.");

define("_LOGOSETTINGS", "Nastavenia loga");
define("_USELOGO", "Vyberte súbor s logom z počítača");
define("_LOGOTYPE", "Vyberte logo vo formáte png.");
define("_LOGODIMENSION", "Maximálna povolená veľkosť loga je 80 x 80, vyberte logo s príslušnou veľkosťou.");

define("_SERVICECONTACTINFO", "Kontaktné informácie pre Servis obrazovky");
define("_SERVICECONTACTINFOCHARACTER", "Kontaktné informácie pre Servis obrazovky musia mať maximálne 25 znakov!<br>Platné znaky a..z 0..9 .+@*");

define("_SCREENTHEME", "Téma obrazovky");
define("_DARKBLUE", "Tmavomodrá");
define("_ORANGE", "Oranžová");
define("_PLEASEENTERRFIDLOCALLIST", "Zadajte miestny zoznam RFID!");

define("_LOADMANAGEMENT", "Správu zaťaženia");
define("_CPROLE", "Rola nabíjacieho bodu");
define("_GRIDSETTINGS", "Nastavenia mriežky");
define("_LOADMANAGEMENTMODE", "Režim pre správu zaťaženia");
define("_LOADMANAGEMENTGROUP", "Skupina pre správu zaťaženia");
define("_LOADMANAGEMENTOPTION", "Možnosť správy zaťaženia");
define("_ALARMS", "Alarmy");

define("_MASTER", "Master");
define("_SLAVE", "Slave");
define("_TOTALCURRENTLIMIT", "Celkový prúdový limit na fázu");
define("_SUPPLYTYPE", "Typ napájania");
define("_FIFOPERCANTAGE", "Percento FIFO");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Rovnako zdieľané");
define("_COMBINED", "Kombinované");
define("_TOTALCURRENTLIMITERROR", "Vyžaduje sa celkový prúdový limit na fázu!");
define("_LESSTHAN1024", "musí byť menej ako 1024");
define("_ATLEAST0","mora biti barem 0");
define("_MORETHAN12", "musí byť viac ako 12");
define("_CHOOSEONE", "Zvoľte jedno");
define("_SLAVEMINCHCURRENT", "Offline Failsafe nastavenie súčasného nabíjania");
define("_SERIALNO", "Sériové číslo");
define("_CONNECTORSTATE", "Stav konektora");
define("_NUMBEROFPHASES", "Počet fáz");
define("_PHASECONSEQUENCE", "Poradie fázového pripojenia");
define("_VIP", "VIP nabíjanie");
define("_CPMODE", "CP Mode");
define("_VIPERROR", "Vyžaduje sa VIP nabíjanie");
define("_PHASECONSEQUENCEERROR", "Vyžaduje sa Poradie fázového pripojenia!");
define("_CPMODEERROR", "Vyžaduje sa Režim CP!");
define("_SUPPORTEDCURRENT", "Podporovaný prúd");
define("_INSTANTCURPERPHASE", "Okamžitá prúdová fáza");
define("_FIFOCHARGINGPERCENTAGE", "Percento nabíjania FIFO");
define("_MINIMUMCURRENT1P", "Minimálny nabíjací prúd 1- fáza");
define("_MINIMUMCURRENT3P", "Minimálny nabíjací prúd 3- fáza");
define("_MAXIMUMCURRENT", "Maximálny nabíjací prúd");
define("_STEP", "Krok");
define("_UPDATEDLMGROUP", "Aktualizácia skupiny DLM");
define("_MAINCIRCUITCURRENT", "Maximálny prúd siete");
define("_MAINCIRCUITCURRENTERROR", "Vyžaduje sa maximálny prúd siete!");
define("_DLMMAXCURRENT", "DLM Celkový prúdový limit na fázu");
define("_DLMMAXCURRENTERROR", "Vyžaduje sa celkový prúdový limit DLM na fázu!");
define("_DLMMAXCURRENTMORETHANMAIN", "Celkový prúdový limit DLM by mal byť viac ako polovica prúdu hlavného ističa");
define("_DLMMAXCURRENTLESSTHANMAIN", "Celkový prúdový limit DLM by mal byť menší ako prúd hlavného ističa");

define("_DHCPSERVER", "DHCP Server");
define("_DHCPCLIENT", "Klient DHCP");

define("_MAXDHCPADDRRANGE", "Koncová IP adresa servera DHCP");
define("_MINDHCPADDRRANGE", "Začiatočná IP adresa servera DHCP");

define("_MAXDHCPADDRRANGEERROR", "Vyžaduje sa koncová IP adresa servera DHCP!");
define("_MINDHCPADDRRANGEERROR", "Vyžaduje sa začiatočná IP adresa servera DHCP!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "Koncová IP adresa servera DHCP by mala byť vyššia ako začiatočná adresa IP servera DHCP");
define("_IPADDRESSRANGE", "IP adresa nemôže mať hodnotu medzi začiatočnou a koncovou adresou DHCP servera");
define("_INVALIDSUBNET", "IP adresa nie je v skutočnej podsieti");

define("_CONNECTIONSTATUS", "Stav pripojenia");

define("_INSTALLATIONSETTINGS", "Nastavenie pre inštaláciu");
define("_EARTHINGSYSTEM", "Uzemňovací systém");
define("_CURRENTLIMITERSETTINGS", "Nastavenia obmedzovača prúdu");
define("_CURRENTLIMITERPHASE", "Fáza obmedzovača prúdu");
define("_CURRENTLIMITERVALUE", "Hodnota obmedzovača prúdu");
define("_UNBALANCEDLOADDETECTION", "Detekcia nesymetrického zaťaženia");
define("_EXTERNALENABLEINPUT", "Externý povolený vstup");
define("_LOCKABLECABLE", "Uzamykateľný kábel");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Celkový prúdový limit optimalizátora výkonu");
define("_POWEROPTIMIZER", "Optimalizátor výkonu");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "Jedna fáza");
define("_THREEPHASE", "Tri fázy");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Celkový prúdový limit <br> optimalizátora výkonu musí byť <br> vyšší alebo rovný 16");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Celkový prúdový limit <br> optimalizátora výkonu musí byť <br> vyšší alebo rovný 100");
define("_FOLLOWTHESUN", "Nasledujte slnko");
define("_FOLLOWTHESUNMODE", "Postupujte podľa slnečného režimu");
define("_AUTOPHASESWITCHING", "Automatické prepínanie fáz");
define("_MAXHYBRID", "Maximálny hybrid");
define("_SUNONLY", "Iba slnko");
define("_SUNHYBRID", "Slnečný hybrid");

define("_DISPLAYBACKLIGHTSETTINGS", "Nastavenia podsvietenia obrazovky");
define("_BACKLIGHTLEVEL", "Úroveň podsvieteniaÚroveň podsvietenia");
define("_SUNRISETIME", "Čas východu slnka ");
define("_SUNSETTIME", "Čas západu slnka");

define("_HIGH", "Vysoká");
define("_MID", "Stredná");
define("_LOW", "Nízka");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Keď je EVReadySupport zapnutá a fázou limitu prúdu je jedna fáza, hodnota aktuálneho limitu nemôže byť menšia ako 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Keď je EVReadySupport zapnutá a fáza aktuálneho limitu je trojfázová, hodnota aktuálneho limitu nemôže byť nižšia ako 14!");
define("_LEDDIMMINGSETTINGS", "Nastavenia stmievania Led");
define("_LEDDIMMINGLEVEL", "Úroveň stmievania Led");
define("_VERYLOW", "Ve&#39mi Nízka");

define("_CELLULARGATEWAYCONFIRM", "Mobilná brána bude deaktivovaná.");

define("_ETHERNETIP", "IP rozhrania Ethernet:");
define("_WLANIP", "IP rozhrania WLAN:");
define("_STRENGTH", "Pevnosť");
define("_WIFIFREQ", "Frekvencia");
define("_WIFILEVEL", "úroveň");
define("_CELLULARIP", "IP mobilného rozhrania:");
define("_CELLULAROPERCODE" , "Operátor");
define("_CELLULARTECH" , "Technológia");
define("_APPLICATIONRESTART", "Táto zmena vyžaduje reštart aplikácie.");
define("_ACCEPTQUESTION", "Prijímate zmeny?");
define("_SCANNETWORKS", "Skenovať siete");
define("_AVAILABLENETWORKS", "Dostupné siete");
define("_NETWORKSTATUS", "Stav siete");
define("_PLEASEWAITMSG", "Prosím, čakajte...");
define("_SCANNINGWIFIMSG", "Skenovanie Wi-Fi sietí");
define("_NOWIFIFOUNDMSG", "Nenašli sa žiadne Wi-Fi siete");
define("_PLEASECHECKWIFICONNMSG", "Skontrolujte pripojenie Wi-Fi a skúste to znova.");

define("_QRCODE", "Zobraziť QR Kód");
define("_QRCODEONSCREEN", "QR Kód na Obrazovke");
define("_QRCODEDELIMITER", "Oddeľovač QR kódu");
define("_INVALIDDELIMITERCHARACTER", "Znak oddeľovača QR kódu je neplatný, medzera nie je prijateľná, dĺžka znakov musí byť minimálne 1 a maximálne 3 znakov, platné znaky 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");

define("_LOCATION", "Miesto");
define("_INDOOR", "Vnútorný");
define("_OUTDOOR", "Vonku");
define("_POWEROPTIMIZEREXTERNALMETER", "Externý Merač");
define("_OPERATIONMODE", "Operačný Mód");
define("_AUTOSELECTED", "Automaticky vybraté");
define("_NOTSELECTED", "Nevybraté");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "Výber režimu nabíjania a konfigurácia optimalizátora napájania");

define("_USERINTERACTION", "Interakcia používateľa");
define("_STANDBYLEDBEHAVIOUR", "Chovanie pohotovostného režimu LED");
define("_OFF", "Vypnuté");
define("_ON", "Na");

define("_LOADSHEDDINGMINIMUMCURRENT", "Minimálny prúd odľahčenia záťaže");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Max. prúd detekcie nevyváženého zaťaženia");

define("_SCHEDULEDCHARGING", "Plánované nabíjanie");
define("_OFFPEAKCHARGING", "Nabíjanie mimo špičky");
define("_OFFPEAKCHARGINGWEEKENDS", "Víkendy mimo špičky");
define("_OFFPEAKCHARGINGPERIODS", "Obdobia nabíjania mimo špičky");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Pokračujte v nabíjaní po skončení špičkového intervalu");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Pokračujte v nabíjaní bez opätovnej autentifikácie po výpadku napájania");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Randomizované oneskorenie maximálne <br> trvanie (sekundy)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Randomizované oneskorenie Vyžaduje sa maximálne trvanie!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Náhodné oneskorenie Maximálne trvanie musí byť celé číslo!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Maximálne trvanie náhodného oneskorenia by malo byť medzi 0 a 1800");
define("_OFFPEAKCHARGINGPERIODSERROR", "* Vyžadujú sa doby nabíjania mimo špičky!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Čas začiatku a konca nabíjania mimo špičky nemôže byť rovnaký!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Druhé obdobie nabíjania mimo špičky");
define("_OFFPEAKDISABLEDCONFIRM", "Nabíjanie mimo špičky bude vypnuté. Potvrdiť?");
define("_SHOWSERVICECONTACTINFO", "Zobraziť ďalšie kontaktné informácie služby");
define("_EXTRASERVICECONTACTINFORMATION", "Servisné kontaktné informácie sú zobrazené na obrazovkách Pripojiť nabíjací kábel, Príprava na nabíjanie, Inicializácia a Čakanie na pripojenie");

define("_LOADSHEDDINGSTATUS", "Stav odbremenenia:");
define("_ACTIVE", "Aktívne");
define("_INACTIVE", "Neaktívne");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Ak chcete použiť možnosť správy záťaže v Modbuse,<br>najprv musíte vypnúť celkový prúdový limit optimalizátora výkonu<br>v &#39Výber režimu nabíjania a konfigurácia optimalizátora výkonu&#39.");
define("_MODBUSALERT", "Ak chcete povoliť externý merač Power Optimizer,<br>najprv musíte deaktivovať Modbus<br>v &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Ak chcete použiť možnosť riadenia záťaže v režime Master/Slave,<br>najprv musíte deaktivovať Optimalizátor výkonu<br>z &#39Výber režimu nabíjania a konfigurácia Optimalizátora výkonu&#39.");
define("_DLMALERT", "Ak chcete aktivovať svoj Optimalizátor výkonu,<br>musíte najprv deaktivovať Master/Slave<br>v &#39Lokálnom riadení zaťaženia&#39.");

define("_FOLLOWTHESUNDLMENABLEALERT", "Ak chcete použiť možnosť riadenia záťaže v režime Master/Slave,<br>najprv musíte deaktivovať Nasledujte slnko<br>z &#39Výber režimu nabíjania a konfigurácia Optimalizátora výkonu&#39.");
define("_DLMALERTFOLLOWTHESUN", "Ak chcete aktivovať svoj Nasledujte slnko,<br>musíte najprv deaktivovať Master/Slave<br>v &#39Lokálnom riadení zaťaženia&#39.");

define("_RESETUSERPASSWORD", "Obnoviť heslo <br> používateľa");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Ak chcete vypnúť možnosť Povoliť chybu pri inštalácii,<br>najprv musíte nastaviť uzemňovací systém z &#39Nastavenia inštalácie&#39 na IT/Split Phase.");
define("_EARTHINGSYSTEMCONFIRM", "Ak chcete nastaviť uzemňovací systém na TN/TT,<br>najprv musíte povoliť možnosť Povoliť chybu pri inštalácii v časti &#39OCPP Settings&#39.");

define("_AUTHKEYMAXLIMIT", "dĺžka by mala byť maximálne 40 znakov.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Pole Authorization Key je prázdne.<br>Potvrdili ste zmeny?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Randomizované oneskorenie na konci špičky");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Bezpečný prúd");
define("_FAILSAFECURRENTERROR", "Vyžaduje sa bezpečný prúd!");
define("_FAILSAFECURRENTLESSTHAN0", "* Failsafe Aktuálna hodnota nesmie byť menšia ako 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Failsafe Aktuálna hodnota nesmie byť väčšia ako 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Failsafe Aktuálna hodnota nesmie byť väčšia ako 50!");

define("_LOCALCHARGESESSION", "Miestne účtovné relácie");
define("_ROWNUMBER", "Rad No");
define("_SESSIONUUID", "ID poplatku");
define("_AUTHORIZATIONUID", "Kode RFID");
define("_STARTTIME", "Startije čas");
define("_STOPTIME", "Zastavit čas");
define("_TOTALTIME", "Celkový čas");
define("_STATUS", "Postavenie");
define("_CHARGEPOINTIDS", "Številka vtičnice");
define("_INITIALENERGY", "Počiatočná Energia(kWh)");
define("_LASTENERGY", "Posledna Energia(kWh)");
define("_TOTALENERGY", "Celková Energia(kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Prihlásenie Celej Relácie v CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Súhrnné prihlásenie do CSV");
define("_STARTDATE", "dátum začiatku");
define("_ENDDATE", "dátum ukončenia");
define("_RFIDSELECTION", "Dátum RFID");
define("_CLEAR", "jasný");

define("_FALLBACKCURRENT", "Záložný prúd");
define("_FALLBACKRANGE", "Spätný prúd musí byť 0 alebo v rámci rozsahu ");
define("_DOWNLOADEEBUSLOGS", "EEBUS Logs");
define("_PAIRINGENERGYMANAGER", "Povolené pre párovanie");
define("_PAIR", "Pair Enable");
define("_UNPAIR", "Unpair");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Verzia firmvéru");
define("_EEBUSDISCOVERY", "Objavené zariadenia");
define("_REFRESH", "Refresh");
define("_CPROLEMASTERREQUIREDFIELD", "Ak chcete aktualizovať nastavenia skupiny správy záťaže, rola nabíjacieho bodu musí byť uložená ako &#39Master&#39 zo všeobecných nastavení správy záťaže.");

define("_LISTOFSLAVES", "Zoznam otrokov");
define("_NUMBEROFSLAVES", "Počet otrokov");
define("_LISTOFCONNECTOR", "Zoznam konektorov");
define("_AVAILABLECURRENT", "Dostupná aktuálna fáza");

define("_DLMINTERFACE", "DLM Interface");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "Povoli WiFi zo sieťových rozhraní!");

define("_MUSTBEINTEGER", "musí byť celé číslo!");
define("_GRIDBUFFER", "Percento ochranného rozpätia siete");
define("_CHARGINGSTATUSALERT", "V stave nabíjania nie je možné hodnotu aktualizovať!");
define("_READUNDERSTAND", "Prečítal som, rozumiem");

define("_MORETHAN10", "Pred uložením týchto nastavení musíte zvýšiť maximálny prúd siete alebo znížiť percento ochranného okraja siete. Limit maximálneho prúdu siete nemôže byť nižší ako 10A pri použití percentuálneho podielu ochrany siete.");

define("_CLUSTERMAXCURRENT", "Maximálny prúd klastra");
define("_CLUSTERFAILSAFECURRENT", "Cluster Failsafe Current");
define("_CLUSTERMAXCURRENTERROR", "Vyžaduje sa maximálny prúd klastra!");
define("_CLUSTERFAILSAFECURRENTERROR", "Vyžaduje sa bezpečný prúd klastra!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Cluster Failsafe Aktuálna hodnota nesmie byť menšia ako 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Hodnota klastra Failsafe Current musí byť menšia ako Maximum Grid Current!");
define("_CLUSTERFAILSAFE", "Cluster Failsafe Mode");

define("_CLUSTERMAXCURRENTLESSTHAN10", "Max. aktuálna hodnota klastra nesmie byť menšia ako 10");
define("_CLUSTERMAXCURRENTMORETHAN", "Maximálna aktuálna hodnota klastra musí byť rovnaká alebo menšia ako táto hodnota:");