<?php
include_once "access_control.php";
define("_LOGIN", "AANMELDEN");
define("_USERNAME", "Gebruikersnaam:");
define("_PASSWORD", "Wachtwoord:");
define("_CHANGEPASSWORD", "Het wachtwoord wijzigen");
define("_CURRENTPASSWORD", "Huidig wachtwoord:");
define("_NEWPASSWORD", "Nieuw wachtwoord:");
define("_CONFIRMNEWPASSWORD", "Nieuw wachtwoord bevestigen:");
define("_SUBMIT", "Verzenden");
define("_CURRENTPASSWORDREQUIRED", "Huidig wachtwoord is vereist");
define("_PASSWORDREQUIRED", "Wachtwoord is vereist");
define("_USERNAMEREQUIRED", "Gebruikersnaam is vereist");
define("_USERAUTHFAILED", "Verificatie van de gebruiker mislukt!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Gebruikersnaam of huidig wachtwoord is verkeerd!");
define("_DBACCESSFAILURE", "Geen toegang tot de databank!");
define("_CHANGEPASSWORDERROR", "U moet eerst uw wachtwoord wijzigen!");
define("_SAMEPASSWORDERROR", "Het huidige en het nieuwe wachtwoord moeten verschillen van elkaar!");
define("_PASSWORDMATCHERROR", "De wachtwoorden stemmen niet overeen!");
define("_CURRENTPASSWORDWRONG", "Huidig wachtwoord is sterk!");
define("_PASSWORDERRORLEVEL2", "Wachtwoord is ongeldig, tekenlengte moet 20 zijn en minimaal twee letters [A-Za-z], twee cijfers [0-9] en twee speciale tekens bevatten [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Het wachtwoord is ongeldig, de tekenlengte moet minimaal 12, maximaal 32 tekens zijn en bevat minimaal twee kleine letters [a-z] en twee hoofdletters [A-Z], twee cijfers [0-9] en minimaal twee speciale tekens [!%&/()=?*#+-_] zijn.");
define("_LOGINLOCKOUT", "Teveel mislukte pogingen. Probeer het na 1800 seconden.");

define("_MAINPAGE", "Hoofdpagina");
define("_GENERAL", "Algemene instellingen");
define("_OCPPSETTINGS", "OCPP-instellingen");
define("_NETWORKINTERFACES", "Netwerk interfaces");

define("_OCPPCONNINTERFACE", "OCPP aansluiting interface : ");
define("_CONNECTIONSTATE", "Verbindingsstatus : ");
define("_DISCONNECTED", "Verbinding verbroken");
define("_NEEDTOLOGINFIRST", "U moet zich eerst aanmelden!");
define("_CONNECTED", "Verbonden");
define("_CPSERIALNUMBER", "CP serienummer : ");
define("_HMISOFTWAREVERSION", "HMI softwareversie : ");
define("_OCPPSOFTWAREVERSION", "OCPP softwareversie : ");
define("_POWERBOARDSOFTWAREVERSION", "Voedingskaart softwareversie : ");
define("_OCPPDEVICEID", "OCPP apparaat-ID : ");
define("_DURATIONAFTERPOWERON", "Duur na inschakeling : ");
define("_LOGOUT", "Afmelden");
define("_PRESET", "Pre-Sets:");

define("_OCPPCONNECTION", "OCPP aansluiting");
define("_ENABLED", "Ingeschakeld");
define("_DISABLED", "Uitgeschakeld");
define("_CONNECTIONSETTINGS", "Verbindingsinstelling");
define("_CENTRALSYSTEMADDRESS", "Centraal systeem adres ");
define("_CHARGEPOINTID", "Laadpunt ID ");
define("_OCPPVERSION", "OCPP-versie");
define("_SAVE", "Opslaan");
define("_SAVESUCCESSFUL", "Correct opgeslagen");
define("_CENTRALSYSTEMADDRESSERROR", "Centraal systeem adres is vereist!");
define("_CHARGEPOINTIDERROR", "Laadpunt ID is vereist!");
define("_SECONDS", "Seconden");
define("_ADD", "Toevoegen");
define("_REMOVE", "Verwijderen");
define("_SAVECAPITAL", "OPSLAAN");
define("_CANCEL", "Annuleren");

define("_CELLULAR", "Cellulair");
define("_INTERFACEIPADDRESS", "Interface IP-adres: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "APN-naam: ");
define("_APNUSERNAME", "APN-gebruikersnaam: ");
define("_APNPASSWORD", "APN-wachtwoord: ");
define("_IPSETTING", "IP instelling: ");
define("_IPADDRESS", "IP-adres: ");
define("_NETWORKMASK", "Netwerkmasker: ");
define("_DEFAULTGATEWAY", "Standaardgateway: ");
define("_PRIMARYDNS", "Primaire DNS: ");
define("_SECONDARYDNS", "Secundaire DNS: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Beveiliging: ");
define("_SECURITYTYPE", "Selecteer het beveiligingstype");
define("_NONE", "Geen");
define("_SELECTMODE", "Selecteer de modus!");
define("_RFIDLOCALLIST", "RFID lokale lijst");
define("_ACCEPTALLRFIDS", "Alle RFID aanvaarden");
define("_AUTOSTART", "Automatische start");
define("_MANAGERFIDLOCALLIST", "RFID lokale lijst beheren:");
define("_PROCESSING", "Bezig met verwerken... Even geduld...");
define("_MACADDRESS", "MAC-Adres: ");
define("_WIFIHOTSPOT", "Wifi hotspot");
define("_TURNONDURINGBOOT", "Inschakelen tijdens opstarten: ");
define("_AUTOTURNOFFTIMEOUT", "Time-out automatisch uitschakelen: ");
define("_AUTOTURNOFF", "Automatische uitschakeling: ");
define("_HOTSPOTALERTMESSAGE", "Wijzigingen in de hotspot-instellingen worden van kracht de volgende keer dat het apparaat wordt ingeschakeld. ");
define("_HOTSPOTREBOOTMESSAGE", "Wil je nu opnieuw opstarten? ");
define("_DOWNLOADACLOGS", "AC logbestanden downloaden");
define("_DOWNLOADCELLULARLOGS", "Cellulaire modus logbestanden downloaden");
define("_DOWNLOADPOWERBOARDLOGS", "Voedingskaart logbestanden downloaden");
define("_PASSWORDRESETSUCCESSFUL", "Uw wachtwoord is correct opnieuw ingesteld");
define("_DBOPENEDSUCCESSFULLY", "Databank is correct geopend\n");
define("_WSSCERTSSETTINGS", "WSS-certificaten instellingen ");
define("_CONFKEYS", "Configuratietoetsen");
define("_KEY", "Toets");
define("_STATIC", "Statisch");
define("_TIMEZONE", "Tijdzone");
define("_PLEASESELECTTIMEZONE", "Selecteer de tijdzone");
define("_DISPLAYSETTINGS", "Instellingen weergeven");
define("_DISPLAYLANGUAGE", "Taal weergeven");
define("_BACKLIGHTDIMMING", "Achtergrondverlichting dimmen : ");
define("_PLEASESELECT", "Selecteer een optie");
define("_TIMEBASED", "Tijdgebaseerd");
define("_SENSORBASED", "Sensorgebaseerd");
define("_BACKLIGHTDIMMINGLEVEL", "Achtergrondverlichting dimmen niveau : ");
define("_BACKLIGHTTHRESHOLD", "Achtergrondverlichting drempelwaarde : ");
define("_SETMIDTHRESHOLD", "GemiddeldeDrempelwaardeInstellen");
define("_SETHIGHTHRESHOLD", "HogeDrempelwaardeInstellen");
define("_LOCALLOADMANAGEMENT", "Lokaal loadmanagement");
define("_MINIMUMCURRENT", "Minimumstroom: ");
define("_FIFOPERCENTAGE", "FIFO Percentage: ");
define("_GRIDMAXCURRENT", "Rooster maximale stroom: ");
define("_MASTERIPADDRESS", "IP-adres van Master: ");
define("_BACKLIGHTTIMESETTINGS", "Achtergrondverlichting tijdinstellingen: ");
define("_SHOULDSELECTTIMEZONE", "* U moet een tijdzone selecteren!");
define("_MINIMUMCURRENTREQUIRED", "* Minimumstroom is vereist!");
define("_CURRENTMUSTBENUMERIC", "* Stroom moet numeriek zijn!");
define("_FIFOPERCREQUIRED", "* FIFO-percentage is vereist!");
define("_FIFOPERCSHOULDBETWEEN", "* FIFO-percentage moet tussen 0 en 100 zijn!");
define("_PERCMUSTBENUMERIC", "* Percentage moet numeriek zijn!");
define("_GRIDMAXCURRENTREQUIRED", "* Rooster maximale stroom is vereist!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Rooster stroom moet numeriek zijn!");
define("_IPADDRESSOFMASTERREQUIRED", "* IP-adres van Master is vereist!");
define("_INVALIDIPADDRESS", "* U hebt een ongeldig IP-adres ingevoerd!");
define("_SAMENETWORKLAN", "* U hebt een IP-adres ingevoerd in hetzelfde netwerk met LAN!");

define("_SAMENETWORKWLAN", "* U hebt een IP-adres in hetzelfde netwerk met WLAN ingevoerd!");
define("_APNISREQUIRED", "APN is vereist!");
define("_IPADDRESSREQUIRED", "IP-adres is vereist!");
define("_NETWORKMASKREQUIRED", "Netwerkmasker is vereist!");
define("_INVALIDNETWORKMASK", "* U hebt een ongeldig netwerkmasker ingevoerd!");
define("_DEFAULTGATEWAYREQUIRED", "Standaardgateway is vereist!");
define("_INVALIDGATEWAY", "U hebt een ongeldig netwerkmasker ingevoerd!");
define("_PRIMARYDNSREQUIRED", "Primaire DNS is vereist!");
define("_INVALIDDNS", "U hebt een ongeldige DNS ingevoerd!");
define("_SELECTIPSETTING", "Selecteer de IP-instelling");
define("_SSIDREQUIRED", "SSID is vereist!");
define("_PASSWORDISREQUIRED", "Wachtwoord is vereist!");
define("_WIFIPASSWORDERROR", "Wachtwoord is ongeldig, de tekenlengte moet minimaal 8 en maximaal 63 <br> geldige tekens zijn a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Wachtwoord is ongeldig, tekenlengte moet 20 . zijn,<br>&#8226; Wachtwoord moet minimaal twee letters bevatten [A-Za-z],<br>&#8226; Wachtwoord moet minimaal twee cijfers bevatten [0-9],<br>&#8226; Wachtwoord moet minimaal twee speciale tekens bevatten [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Wachtwoord is ongeldig, tekenlengte moet minimaal 12 zijn, maximaal 32,<br>&#8226; Wachtwoord moet ten minste twee kleine letters [a-z] bevatten, <br>&#8226; Wachtwoord moet minimaal twee hoofdletters [A-Z] bevatten, <br>&#8226; Wachtwoord moet minimaal twee cijfers bevatten [0-9],<br>&#8226; Wachtwoord moet minimaal twee speciale tekens bevatten [!%&/()=?*#+-_]");

define("_WIFISSIDERROR", "SSID is ongeldig, geldige tekens a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Selecteer het beveiligingstype");
define("_HOSTIPREQUIRED", "* Host IP is vereist!");
define("_CERTMANREQUIRED", "* Certificatiebeheer is vereist!");
define("_OCPPENABLEALERT", "Als u uw laadstation wilt gebruiken in de zelfstandige modus moet u eerst de OCPP-verbinding uitschakelen in het menu ‘OCPP-instellingen’");
define("_NOTSAVEDALERT", "De pagina is niet opgeslagen");
define("_SAVEQUESTION", "Wilt u de wijzigingen opslaan?");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Cellulaire verbinding wordt uitgeschakeld. Wilt u bevestigen?");
define("_WIFICONNECTIONCONFIRM", "WiFi-verbinding wordt uitgeschakeld. Wilt u bevestigen?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Als u LAN DHCP Server wilt inschakelen,<br>moet u eerst Wi-Fi Hotspot uitschakelen<br>via &#39Wi-Fi Hotspot&#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Als u Wi-Fi Hotspot wilt inschakelen,<br>moet u eerst LAN DHCP Server uitschakelen<br>via &#39LAN IP Setting&#39.");

define("_DYNAMIC", "Dynamisch");
define("_DIAGNOSTICS", "Diagnostiek");
define("_LOCALLOAD", "Lokaal loadmanagement");
define("_DOWNLOAD", "Downloaden");
define("_STARTDATE", "Startdatum");
define("_ENDDATE", "Einddatum");
define("_CLEAREVENTLOGS", "Alle gebeurtenislijsten wissen");
define("_CLEAREVENTLOGSINFO", "Dit wist alle gebeurtenislijsten!");
define("_DOWNLOADEVENTLOGSINFO", "Download apparaat gebeurtenislijsten voor maximaal 5 dagen");
define("_DEVICEEVENTLOGS", "Apparaat gebeurtenislijsten");
define("_DEVICECHANGELOGS", "Apparaat wijzigingslijsten");
define("_LOGSDATEERROR", "Selecteer data voor maximaal 5 dagen.");
define("_DOWNLOACHANGELOGS", "Download apparaat wijzigingslijsten");
define("_VPNFUNCTIONALITY", "VPN functionaliteit: ");
define("_CERTMANAGEMENT", "Certificatiebeheer: ");
define("_NAME", "Naam: ");
define("_CONNECTIONINTERFACE", "Verbinding interface ");
define("_ANY", "Alle");
define("_OCPPCONNPARAMETERS", "OCPP configuratieparameters");
define("_SETDEFAULT", "Instellen op standaardwaarden ");
define("_STANDALONEMODE", "Zelfstandige modus");
define("_STANDALONEMODETITLE", "Zelfstandige modus:");
define("_STANDALONEMODENOTSELECTED", "* Zelfstandige modus kunnen niet worden geselecteerd aangezien OCPP is ingeschakeld");
define("_CHARGERWEBUI", "Lader internetgebruiker interface");
define("_SYSTEMMAINTENANCE", "Systeemonderhoud");
define("_HOSTIP", "Host IP: ");
define("_PASSWORDERRORLEVEL1", "Wachtwoord is ongeldig, tekenlengte moet minimaal 6 tekens zijn en minimaal 1 kleine letter, 1 hoofdletter en 1 numeriek teken bevatten!");
define("_SELECTBACKLIGHTDIMMING", "* U moet het achtergrondverlichting dimmen selecteren!");
define("_ISREQUIRED", "is vereist!");
define("_ISNOTVALID", "is niet geldig!");
define("_ISDUPLICATED", "wordt gedupliceerd!");
define("_MUSTBENUMERIC", "moet numeriek zijn!");
define("_VPNFUNCTIONALITYREQUIRED", "* VPN-functionaliteit is vereist!");
define("_VPNNAMEREQUIRED", "* VPN-naam is vereist!");
define("_VPNPASSWORDREQUIRED", "* VPN wachtwoord is vereist!");
define("_EXPLANATION", "Toont het vereiste veld aan.");
define("_FIRMWAREUPDATE", "Firmware updates");
define("_BACKUPRESTORE", "Configuratie back-up & herstellen");
define("_SYSTEMRESET", "Systeem opnieuw instellen");
define("_CHANGEADMINPASSWORD", "Systeembeheer wachtwoord");
define("_FACTORYRESET", "Fabrieksinstellingen");
define("_FACTORYRESETBUTTON", "Fabrieksinstellingen terugplaatsen");
define("_FACTORYDEFAULTCONFIGURATION", "Fabrieksinstellingen configuratie");
define("_LOGFILES", "Logbestanden");
define("_BACKUPFILE", "Back-upbestand");
define("_RESTOREFILE", "Configuratiebestand terugplaatsen");
define("_FREEMODEMAXCHARACTER", "moet maximaal 32 tekens bevatten !");
define("_RESTOREMESSAGE", "Bevestigt u om wijzigingen toe te passen en nu opnieuw op te starten?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עברית");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "U wachtwoord moet 6 tekens bevatten en het moet ten minste
een hoofdletter, een kleine letter en een cijfer bevatten.");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Uw wachtwoord moet 20 tekens bevatten  en moet minimaal twee letters,
twee cijfers en twee speciale tekens bevatten.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Uw wachtwoord moet minimaal 12, maximaal 32 tekens lang zijn en moet minimaal
twee hoofdletters, twee kleine letters, twee cijfers en twee speciale tekens bevatten.");

define("_BACKTOLOGIN", "Terug naar login");
define("_CHANGE", "Wijzigen");
define("_SYSTEMADMINISTRATION", "Systeembeheer");
define("_UPDATE", "Update");
define("_CONFIRM", "Bevestigen");
define("_FACTORYDEFAULTCONFIRM", "Bent u zeker dat u de fabrieksinstellingen wilt terugplaatsen?");
define("_FILENAME", "Bestandsnaam");
define("_UPLOAD", "Uploaden");
define("_SELECTFIRMWARE", "Selecteer het Firmware updatebestand via PC");
define("_FIRMWAREFILESIZE", "Controleer de grootte van het firmwarebestand.");
define("_FIRMWAREFILETYPE", "Controleer het type firmwarebestand.");

define("_LESSTHANOREQUAL4", "moet tussen 1 en 4 liggen");
define("_LESSTHANOREQUAL20", "moet kleiner zijn dan of gelijk aan 20");
define("_LESSTHANOREQUAL65000", "moet kleiner zijn dan of gelijk aan 65000");
define("_LESSTHANOREQUAL300", "moet kleiner zijn dan of gelijk aan 300");
define("_LESSTHANOREQUAL86500", "moet kleiner zijn dan of gelijk aan 86500");
define("_LESSTHANOREQUAL10000", "moet kleiner zijn dan of gelijk aan 10000");
define("_LESSTHANOREQUAL22", "moet kleiner zijn dan of gelijk aan 22");
define("_LESSTHANOREQUAL10", "moet kleiner zijn dan of gelijk aan 10");
define("_LESSTHANOREQUAL600", "moet kleiner zijn dan of gelijk aan 600");
define("_LESSTHANOREQUAL120", "moet kleiner zijn dan of gelijk aan 120");
define("_HIGHTHANOREQUAL0", "moet groter zijn dan of gelijk zijn aan 0");
define("_CHANGEPASSWORDSUGGESTION", "Wij raden u aan uw standaard wachtwoord te wijzigen in het systeemonderhoud menu");

define("_FILESIZE", "Controleer de grootte van het  bestand");
define("_FILETYPE", "Controleer het type  bestand");

define("_BACKUPVERSIONCHECK", "De versie van dit bestand is niet geschikt voor het apparaat.");
define("_HARDRESETCONFIRM", "Bent u zeker dat u een Harde reset wilt uitvoeren?");
define("_SOFTRESETCONFIRM", "Bent u zeker dat u een Zachte reset wilt uitvoeren?");
define("_NEWSETUP", "Gebruik de gebruikershandleiding voor de nieuwe instelling.");

define("_LOGOSETTINGS", "Logo-instellingen");
define("_USELOGO", "Selecteer het logobestand op de PC");
define("_LOGOTYPE", "Selecteer een logo met .png-formaat");
define("_LOGODIMENSION", "De maximaal toegelaten afmetingen zijn 80x80, Selecteer een logo met de correcte grootte.");

define("_SERVICECONTACTINFO", "Weergavedienst contactgegevens");
define("_SERVICECONTACTINFOCHARACTER", "Weergavedienst contactgegevens mogen maximaal 25 tekens bevatten!<br>Geldige tekens a..z 0..9 .+@*");

define("_SCREENTHEME", "Weergavethema");
define("_DARKBLUE", "Donkerblauw");
define("_ORANGE", "Oranje");
define("_PLEASEENTERRFIDLOCALLIST", "Voer de RFID lokale lijst in!");

define("_LOADMANAGEMENT", "Loadmanagement");
define("_CPROLE", "Laadpunt rol");
define("_GRIDSETTINGS", "Roosterinstellingen");
define("_LOADMANAGEMENTMODE", "Loadmanagement modus");
define("_LOADMANAGEMENTGROUP", "Loadmanagement groep");
define("_LOADMANAGEMENTOPTION", "Optie voor laadbeheer");
define("_ALARMS", "Alarmen");

define("_MASTER", "Master");
define("_SLAVE", "Slave");
define("_TOTALCURRENTLIMIT", "Totale stroomlimiet per fase");
define("_SUPPLYTYPE", "Toevoertype");
define("_FIFOPERCANTAGE", "FIFO Percentage");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Gelijk gedeeld");
define("_COMBINED", "Gecombineerd");
define("_TOTALCURRENTLIMITERROR", "Totale stroomlimiet per fase is vereist!");
define("_LESSTHAN1024", "moet kleiner zijn dan 1024");
define("_ATLEAST0","moet ten minste 0 zijn");
define("_MORETHAN12", "moet meer zijn dan 12");
define("_CHOOSEONE", "Kies één optie");
define("_SLAVEMINCHCURRENT", "Offline Failsafe Laadstroom Instelling");
define("_SERIALNO", "Serienummer");
define("_CONNECTORSTATE", "Verbindingsstatus");
define("_NUMBEROFPHASES", "Aantal fasen");
define("_PHASECONSEQUENCE", "Fase verbindingssequentie");
define("_VIP", "VIP laden");
define("_CPMODE", "CP-modus");
define("_VIPERROR", "VIP laden is vereist");
define("_PHASECONSEQUENCEERROR", "Fase verbindingssequentie is vereist!");
define("_CPMODEERROR", "CP-modus is vereist!");
define("_SUPPORTEDCURRENT", "Ondersteunde stroom");
define("_INSTANTCURPERPHASE", "Onmiddellijke stroomfase");
define("_FIFOCHARGINGPERCENTAGE", "FIFO laadpercentage");
define("_MINIMUMCURRENT1P", "Minimale laadstroom 1-fasig");
define("_MINIMUMCURRENT3P", "Minimale laadstroom 3-fasig");
define("_MAXIMUMCURRENT", "Maximale laadstroom");
define("_STEP", "Stap");
define("_UPDATEDLMGROUP", "DLM-groep bijwerken");
define("_MAINCIRCUITCURRENT", "Maximale netstroom");
define("_MAINCIRCUITCURRENTERROR", "Maximale netstroom is vereist!");
define("_DLMMAXCURRENT", "DLM Totale stroomlimiet per fase");
define("_DLMMAXCURRENTERROR", "DLM Totale stroomlimiet per fase is vereist!");
define("_DLMMAXCURRENTMORETHANMAIN", "DLM Totale stroomlimiet moet meer zijn dan de helft van de stroom van de hoofdstroomonderbreker");
define("_DLMMAXCURRENTLESSTHANMAIN", "DLM Totale stroomlimiet moet lager zijn dan de stroom van de hoofdstroomonderbreker");

define("_DHCPSERVER", "DHCP Server");
define("_DHCPCLIENT", "DHCP Client");

define("_MAXDHCPADDRRANGE", "DHCP-server einde IP-adres");
define("_MINDHCPADDRRANGE", "DHCP-server start IP-adres");

define("_MAXDHCPADDRRANGEERROR", "DHCP-server einde IP-adres is vereist!");
define("_MINDHCPADDRRANGEERROR", "DHCP-server start IP-adres is vereist!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "Het DHCP-server einde IP-adres moet groter zijn dan het DHCP-server start IP-adres");
define("_IPADDRESSRANGE", "Het IP-adres mag geen waarde zijn tussen het DHCP-server start en het DHCP-server einde IP-adres");
define("_INVALIDSUBNET", "Het IP-adres is niet in het reële subnet ");

define("_CONNECTIONSTATUS", "Verbindingsstatus");

define("_INSTALLATIONSETTINGS", "Installatie-instellingen");
define("_EARTHINGSYSTEM", "Aardingssysteem");
define("_CURRENTLIMITERSETTINGS", "Stroombegrenzer instellingen");
define("_CURRENTLIMITERPHASE", "Stroombegrenzer fase");
define("_CURRENTLIMITERVALUE", "Stroombegrenzer waarde");
define("_UNBALANCEDLOADDETECTION", "Lading in onbalans detectie");
define("_EXTERNALENABLEINPUT", "Extern vrijgavecontact ingang");
define("_LOCKABLECABLE", "Vergrendelbare kabel");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Stroom optimizer totale stroomlimiet");
define("_POWEROPTIMIZER", "Stroom optimizer");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split-fase");
define("_ONEPHASE", "Eenfasig");
define("_THREEPHASE", "Driefasig");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Stroom optimizer totale <br> stroomlimiet moet hoger <br> zijn dan of gelijk aan 16");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Stroom optimizer totale <br> stroomlimiet moet minder <br> zijn dan of gelijk aan 100");
define("_FOLLOWTHESUN", "Volg de zon");
define("_FOLLOWTHESUNMODE", "Volg de zonmodus");
define("_AUTOPHASESWITCHING", "Automatische faseomschakeling");
define("_MAXHYBRID", "Maximaal hybride");
define("_SUNONLY", "Alleen zon");
define("_SUNHYBRID", "Zon hybride");

define("_DISPLAYBACKLIGHTSETTINGS", "Achtergrondverlichting instellingen weergeven");
define("_BACKLIGHTLEVEL", "Achtergrondverlichting niveau");
define("_SUNRISETIME", "Zonsopgang tijd ");
define("_SUNSETTIME", "Zonsondergang tijd");

define("_HIGH", "Hoog");
define("_MID", "Gemiddeld");
define("_LOW", "Laag");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Wanneer EVReadySupport is ingeschakeld en de stroomgrensfase één fase is, mag de stroomgrenswaarde niet lager zijn dan 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Wanneer EVReadySupport is ingeschakeld en de stroombegrenzingsfase driefasig is, mag de stroomgrenswaarde niet lager zijn dan 14!");
define("_LEDDIMMINGSETTINGS", "Led-diminstellingen");
define("_LEDDIMMINGLEVEL", "Led-dimniveau");
define("_VERYLOW", "Heel laag");

define("_CELLULARGATEWAYCONFIRM", "Mobiele gateway wordt uitgeschakeld.");

define("_ETHERNETIP", "Ethernet-interface IP:");
define("_WLANIP", "WLAN-interface IP:");
define("_STRENGTH", "Kracht");
define("_WIFIFREQ", "Frequentie");
define("_WIFILEVEL", "Niveau");
define("_CELLULARIP", "Mobiele interface IP:");
define("_CELLULAROPERCODE" , "Exploitant");
define("_CELLULARTECH" , "Technologie");
define("_APPLICATIONRESTART", "Voor deze wijziging is een herstart van de toepassing vereist.");
define("_ACCEPTQUESTION", "Accepteert u de wijzigingen?");
define("_QRCODE", "QR-Code Weergeven");
define("_QRCODEONSCREEN", "QR-code op het Scherm");
define("_QRCODEDELIMITER", "QR-code scheidingsteken");
define("_INVALIDDELIMITERCHARACTER", "Scheidingsteken QR-code is ongeldig, witruimteteken is niet acceptabel, tekenlengte moet minimaal 1 en maximaal 3 tekens zijn, geldige tekens 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_LOCATION", "Plaats");
define("_INDOOR", "Binnen");
define("_OUTDOOR", "Buitenshuis");
define("_POWEROPTIMIZEREXTERNALMETER", "Externe Meter");
define("_OPERATIONMODE", "Operatie Modus");
define("_AUTOSELECTED", "Automatisch geselecteerd");
define("_NOTSELECTED", "Niet geselecteerd");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "Selectie laadmodus en configuratie Power Optimizer");
define("_SCANNETWORKS", "Scan netwerken");
define("_AVAILABLENETWORKS", "Beschikbare netwerken");
define("_NETWORKSTATUS", "Netwerkstatus");
define("_PLEASEWAITMSG", "Even geduld...");
define("_SCANNINGWIFIMSG", "Wi-Fi netwerken scannen");
define("_NOWIFIFOUNDMSG", "Geen Wi-Fi netwerken gevonden");
define("_PLEASECHECKWIFICONNMSG", "Controleer uw Wi-Fi verbinding en probeer het opnieuw.");

define("_USERINTERACTION", "Gebruikersinteractie");
define("_STANDBYLEDBEHAVIOUR", "Stand-by LED-gedrag");
define("_OFF", "Uit");
define("_ON", "Op");

define("_LOADSHEDDINGMINIMUMCURRENT", "Belastingafschakeling Minimale stroom");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Ongebalanceerde belastingsdetectie Max. stroom");

define("_SCHEDULEDCHARGING", "Gepland opladen");
define("_OFFPEAKCHARGING", "Off Peak opladen");
define("_OFFPEAKCHARGINGWEEKENDS", "Off Peak oplaadweekenden");
define("_OFFPEAKCHARGINGPERIODS", "Dalende oplaadperiodes");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Doorgaan met opladen na het einde van het piekinterval");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Doorgaan met opladen zonder herauthenticatie na stroomuitval");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Willekeurige vertraging Maximale <br> Duur (seconden)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Willekeurige vertraging Maximale duur is vereist!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Willekeurige vertraging Maximale duur moet een geheel getal zijn!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Willekeurige vertraging Maximale duur moet tussen 0 en 1800 zijn!");
define("_OFFPEAKCHARGINGPERIODSERROR", "* Off Peak oplaadperiodes zijn vereist!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Off Peak Opladen Start- en Eindtijd kunnen niet hetzelfde zijn!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Daluren Opladen Tweede Tijdsperiode");
define("_OFFPEAKDISABLEDCONFIRM", "Opladen tijdens daluren wordt uitgeschakeld. Wilt u bevestigen?");
define("_SHOWSERVICECONTACTINFO", "Servicecontactgegevens weergeven");
define("_EXTRASERVICECONTACTINFORMATION", "De contactgegevens van de service worden weergegeven op de schermen Oplaadkabel aansluiten, Opladen voorbereiden, Initialiseren en Wachten op verbinding");

define("_LOADSHEDDINGSTATUS", "Status belastingafschakeling:");
define("_ACTIVE", "Actief");
define("_INACTIVE", "Inactief");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Als u uw Load Management-optie in Modbus wilt gebruiken,<br>moet u eerst de totale stroomlimiet van Power Optimizer uitschakelen<br>vanuit &#39Laadmodusselectie en Power Optimizer-configuratie&#39.");
define("_MODBUSALERT", "Als u uw Power Optimizer externe meter wilt inschakelen,<br>moet u eerst Modbus deactiveren<br>vanuit &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Als u uw Laadbeheeroptie in Master/Slave wilt gebruiken,<br>moet u eerst de Energieoptimalisator uitschakelen<br>in &#39Selectie van Laadmodus en Configuratie van Energieoptimalisator&#39.");
define("_DLMALERT", "Als je je Energieoptimalisator wilt inschakelen,<br>moet je eerst Master/Slave deactiveren<br>in &#39Lokale Laadbeheer&#39.");

define("_FOLLOWTHESUNDLMENABLEALERT", "Als u uw Laadbeheeroptie in Master/Slave wilt gebruiken,<br>moet u eerst de Volg de zon uitschakelen<br>in &#39Selectie van Laadmodus en Configuratie van Energieoptimalisator&#39.");
define("_DLMALERTFOLLOWTHESUN", "Als je je Volg de zon wilt inschakelen,<br>moet je eerst Master/Slave deactiveren<br>in &#39Lokale Laadbeheer&#39.");

define("_RESETUSERPASSWORD", "Gebruikerswachtwoord <br> resetten");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Als u Installatiefout inschakelen wilt uitschakelen,<br>moet u eerst het Aardingssysteem instellen van &#39Installatie-instellingen&#39 op IT/Split Phase.");
define("_EARTHINGSYSTEMCONFIRM", "Als u het aardingssysteem op TN/TT wilt zetten,<br>moet u eerst Installatiefout inschakelen inschakelen via  &#39OCPP-instellingen&#39.");

define("_AUTHKEYMAXLIMIT", "lengte mag maximaal 40 tekens zijn.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Het veld Authorization Key is leeg.<br>Bevestigt u de wijzigingen?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Willekeurige vertraging bij dalureneinde");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Failsafe-stroom");
define("_FAILSAFECURRENTERROR", "Failsafe-stroom is vereist!");
define("_FAILSAFECURRENTLESSTHAN0", "* Failsafe Huidige waarde mag niet kleiner zijn dan 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Failsafe Huidige waarde mag niet hoger zijn dan 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Failsafe Huidige waarde mag niet hoger zijn dan 50!");
define("_LOCALCHARGESESSION", "Lokale laadsessies");
define("_ROWNUMBER", "Rijnummer");
define("_SESSIONUUID", "laad-ID");
define("_AUTHORIZATIONUID", "RFID-code");
define("_STARTTIME", "Starttijd");
define("_STOPTIME", "Stoptijd");
define("_TOTALTIME", "Totale tijd");
define("_STATUS", "Status");
define("_CHARGEPOINTIDS", "Stekkerdoos nummer");
define("_INITIALENERGY", "Initiële Energie(kWh)");
define("_LASTENERGY", "Laatste Energie(kWh)");
define("_TOTALENERGY", "Totale energie (kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Volledige sessielogboek in CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Samenvatting Inloggen CSV");
define("_STARTDATE", "begin datum");
define("_ENDDATE", "einddatum");
define("_RFIDSELECTION", "RFID selectie");
define("_CLEAR", "duidelijk");

define("_FALLBACKCURRENT", "Terugvalstroom");
define("_FALLBACKRANGE", "Terugvalstroom moet 0 zijn of binnen het bereik liggen van ");
define("_DOWNLOADEEBUSLOGS", "EEBUS-logbestanden");
define("_PAIRINGENERGYMANAGER", "Ingeschakeld voor koppelen");
define("_PAIR", "Koppel inschakelen");
define("_UNPAIR", "Ontkoppelen");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Firmwareversie");
define("_EEBUSDISCOVERY", "Ontdekte apparaten");
define("_REFRESH", "Vernieuwen");
define("_CPROLEMASTERREQUIREDFIELD", "Als u de instellingen van de Laadbeheergroep wilt bijwerken, moet de rol van het laadpunt worden opgeslagen als &#39Master&#39 vanuit de algemene instellingen voor laadbeheer.");

define("_LISTOFSLAVES", "Lijst met slaven");
define("_NUMBEROFSLAVES", "Aantal slaven");
define("_LISTOFCONNECTOR", "Lijst met connectoren");
define("_AVAILABLECURRENT", "Beschikbare huidige fase");

define("_DLMINTERFACE", "DLM-interface");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "WiFi inschakelen via netwerkinterfaces!");

define("_MUSTBEINTEGER", "moet een geheel getal zijn!");
define("_GRIDBUFFER", "Margepercentage netbescherming");
define("_CHARGINGSTATUSALERT", "In de laadstatus kan de waarde niet worden bijgewerkt!");
define("_READUNDERSTAND", "Ik heb gelezen, ik begrijp het");

define("_MORETHAN10", "U moet de maximale netstroom verhogen of het percentage netbeschermingsmarge verlagen voordat u deze instellingen opslaat. De maximale netstroomlimiet kan niet lager zijn dan 10A bij gebruik van het percentage netbeschermingsmarge.");

define("_CLUSTERMAXCURRENT", "Max. stroom cluster");
define("_CLUSTERFAILSAFECURRENT", "Cluster Failsafe Stroom");
define("_CLUSTERMAXCURRENTERROR", "Max. stroom van cluster is vereist!");
define("_CLUSTERFAILSAFECURRENTERROR", "Cluster failsafe stroom is vereist!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Cluster Failsafe Huidige waarde mag niet kleiner zijn dan 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Cluster Failsafe huidige waarde moet kleiner zijn dan de maximale netstroom!");
define("_CLUSTERFAILSAFE", "Cluster Failsafe-modus");

define("_CLUSTERMAXCURRENTLESSTHAN10", "De maximale huidige clusterwaarde mag niet kleiner zijn dan 10");
define("_CLUSTERMAXCURRENTMORETHAN", "De maximale huidige clusterwaarde moet gelijk zijn aan of kleiner zijn dan deze waarde:");