<?php
include_once "access_control.php";
define("_LOGIN", "כניסה");
define("_USERNAME", "שם משתמש:");
define("_PASSWORD", "ססמה:");
define("_CHANGEPASSWORD", "שנה ססמה");
define("_CURRENTPASSWORD", "ססמה נוכחית:");
define("_NEWPASSWORD", "ססמה חדשה:");
define("_CONFIRMNEWPASSWORD", "אשר ססמה חדשה:");
define("_SUBMIT", "שלח");
define("_CURRENTPASSWORDREQUIRED", "הססמה הנוכחית דרושה");
define("_PASSWORDREQUIRED", "הססמה דרושה");
define("_USERNAMEREQUIRED", "שם המשתמש דרוש");
define("_USERAUTHFAILED", "אימות המשתמש נכשל!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "שם המשתמש או הסיסמה הנוכחית שגויים!");
define("_DBACCESSFAILURE", "לא ניתן לגשת למסד הנתונים!");
define("_CHANGEPASSWORDERROR", "עליך להחליף קודם את הססמה!");
define("_SAMEPASSWORDERROR", "הססמה הנוכחית והחדשה צריכות להיות שונות זו מזו!");
define("_PASSWORDMATCHERROR", "הססמאות לא תואמות!");
define("_CURRENTPASSWORDWRONG", "הססמה הנוכחית שגויה!");
define("_PASSWORDERRORLEVEL2", "הסיסמה לא חוקית, אורך התווים חייב להיות 20 ולהכיל לפחות שתי אותיות [A-Za-z], שתי ספרות [0-9] ושני תווים מיוחדים [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "הסיסמה לא חוקית, אורך התו חייב להיות לפחות 12, מקסימום 32 תווים ומכיל לפחות שתי אותיות קטנות ושתי אותיות רישיות, שני מספרים ולפחות שני תווים מיוחדים.");
define("_LOGINLOCKOUT", "יותר מדי ניסיונות כושלים. אנא נסה לאחר 1800 שניות.");

define("_MAINPAGE", "דף ראשי");
define("_GENERAL", "הגדרות כלליות");
define("_OCPPSETTINGS", "הגדרות OCPP");
define("_NETWORKINTERFACES", "ממשקי רשת");

define("_OCPPCONNINTERFACE", "ממשק ח&#39בור OCPP : ");
define("_CONNECTIONSTATE", "מצב החיבור : ");
define("_DISCONNECTED", "מנותק");
define("_NEEDTOLOGINFIRST", "עליך להיכנס קודם!");
define("_CONNECTED", "מחובר");
define("_CPSERIALNUMBER", "מספר CP סידורי : ");
define("_HMISOFTWAREVERSION", "גרסת תוכנה HMI : ");
define("_OCPPSOFTWAREVERSION", "גרסת תוכנה OCPP : ");
define("_POWERBOARDSOFTWAREVERSION", "גרסת תוכנת לוח ההספק : ");
define("_OCPPDEVICEID", "מזהה מכשיר OCPP : ");
define("_DURATIONAFTERPOWERON", "משך אחרי הפעלה : ");
define("_LOGOUT", "התנתקות");
define("_PRESET", "הגדרות-קדם:");

define("_OCPPCONNECTION", "חיבור OCPP");
define("_ENABLED", "מופעל");
define("_DISABLED", "נָכֶה");
define("_CONNECTIONSETTINGS", "הגדרות חיבור");
define("_CENTRALSYSTEMADDRESS", "כתובת המערכת המרכזית ");
define("_CHARGEPOINTID", "מזהה נקודת טעינה ");
define("_OCPPVERSION", "גרסת OCPP");
define("_SAVE", "שמור");
define("_SAVESUCCESSFUL", "נשמר בהצלחה.");
define("_CENTRALSYSTEMADDRESSERROR", "כתובת המערכת המרכזית דרושה!");
define("_CHARGEPOINTIDERROR", "מזהה נקודת הטעינה דרוש!");
define("_SECONDS", "שניות");
define("_ADD", "הוסף");
define("_REMOVE", "הסר");
define("_SAVECAPITAL", "שמור");
define("_CANCEL", "בטל");

define("_CELLULAR", "סלולרי");
define("_INTERFACEIPADDRESS", "כתובת IP של ממשק: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "שם APN: ");
define("_APNUSERNAME", "שם משתמש APN: ");
define("_APNPASSWORD", "ססמה APN: ");
define("_IPSETTING", "הגדרת IP: ");
define("_IPADDRESS", "כתובת IP: ");
define("_NETWORKMASK", "מסכת רשת: ");
define("_DEFAULTGATEWAY", "שער ברירת מחדל: ");
define("_PRIMARYDNS", "DNS ראשי: ");
define("_SECONDARYDNS", "DNS משני: ");
define("_WIFI", "WLAN");
define("_SECURITY", "בטיחות: ");
define("_SECURITYTYPE", "בחר סוג אבטחה");
define("_NONE", "אין");
define("_SELECTMODE", "בחר מצב!");
define("_RFIDLOCALLIST", "רשימת RFID מקומית");
define("_ACCEPTALLRFIDS", "אשר את כל ה-RFID");
define("_MANAGERFIDLOCALLIST", "נהל רשימת RFID מקומית:");
define("_AUTOSTART", "Autostart");
define("_PROCESSING", "מתבצע עיבוד... המתן...");
define("_MACADDRESS", "כתובת MAC: ");
define("_WIFIHOTSPOT", "נקודת אינטרנט אלחוטי");
define("_TURNONDURINGBOOT", "הפעל במהלך האתחול: ");
define("_AUTOTURNOFFTIMEOUT", "כיבוי פסק זמן אוטומטי: ");
define("_AUTOTURNOFF", "כ&#39בו&#39 אוטומט&#39: ");
define("_HOTSPOTALERTMESSAGE", "שינויים בהגדרת נקודה חמה ייכנסו לתוקף בפעם הבאה שהמכשיר יופעל. ");
define("_HOTSPOTREBOOTMESSAGE", "האם אתה רוצה לאתחל מחדש עכשיו? ");

define("_DOWNLOADACLOGS", "הורד יומני AC");
define("_DOWNLOADCELLULARLOGS", "הורד יומני מודול סלולרי");
define("_DOWNLOADPOWERBOARDLOGS", "הורד יומני לוח הספק");
define("_PASSWORDRESETSUCCESSFUL", "הססמה אופסה בהצלחה.");
define("_DBOPENEDSUCCESSFULLY", "פתיחת מסד הנתונים הצליחה\n");
define("_WSSCERTSSETTINGS", "הגדרות אישורי WSS ");
define("_CONFKEYS", "מקשי תצורה");
define("_KEY", "מקש");
define("_STATIC", "סטטי");
define("_TIMEZONE", "אזור זמן");
define("_PLEASESELECTTIMEZONE", "בחר אזור זמן");
define("_DISPLAYSETTINGS", "הצג הגדרות");
define("_DISPLAYLANGUAGE", "הצג שפה");
define("_BACKLIGHTDIMMING", "עמעום תאורת רקע : ");
define("_PLEASESELECT", "בחר בבקשה");
define("_TIMEBASED", "כתלות בשעה");
define("_SENSORBASED", "כתלות בחיישן");
define("_BACKLIGHTDIMMINGLEVEL", "רמת עמעום תאורת רקע : ");
define("_BACKLIGHTTHRESHOLD", "סף תאורת רקע : ");
define("_SETMIDTHRESHOLD", "הגדר את סף אמצע");
define("_SETHIGHTHRESHOLD", "הגדר סף גבוה");
define("_LOCALLOADMANAGEMENT", "ניהול עומס מקומי");
define("_MINIMUMCURRENT", "זרם מינימלי: ");
define("_FIFOPERCENTAGE", "אחוז נר\"יר:: ");
define("_GRIDMAXCURRENT", "זרם רשת מרבי:: ");
define("_MASTERIPADDRESS", "כתובת ה-IP של המאסטר:: ");
define("_BACKLIGHTTIMESETTINGS", "הגדרות שעת תאורת רקע: ");
define("_SHOULDSELECTTIMEZONE", "* בחר אזור זמן!");
define("_MINIMUMCURRENTREQUIRED", "* הזרם המינימלי דרוש!");
define("_CURRENTMUSTBENUMERIC", "*  ערך הזרם צריך להיות מספרי!");
define("_FIFOPERCREQUIRED", "* אחוז הנר\"יר דרוש!");
define("_FIFOPERCSHOULDBETWEEN", "* אחוז הנר\"יר צריך להיות בין 0 ל-100!");
define("_PERCMUSTBENUMERIC", "* האחוז צריך להיות מספרי!");
define("_GRIDMAXCURRENTREQUIRED", "* זרם הרשת המרבי דרוש!");
define("_GRIDCURRENTMUSTBENUMERIC", "* הערך של זרם הרשת צריך להיות מספרי!");
define("_IPADDRESSOFMASTERREQUIRED", "* כתובת ה-IP של המאסטר דרושה!");
define("_INVALIDIPADDRESS", "* הזנת כתובת IP שגויה!");
define("_SAMENETWORKLAN", "* הזנת כתובת IP באותה רשת עם LAN!");
define("_SAMENETWORKWLAN", "* הזנת כתובת IP באותה רשת עם WLAN!");
define("_APNISREQUIRED", "ה-APN דרוש!");
define("_IPADDRESSREQUIRED", "כתובת ה-IP דרושה!");
define("_NETWORKMASKREQUIRED", "מסכת הרשת דרושה!");
define("_INVALIDNETWORKMASK", "* הזנת מסכת רשת שגויה!");
define("_DEFAULTGATEWAYREQUIRED", "שער ברירת המחדל דרוש!");
define("_INVALIDGATEWAY", "הזנת שער ברירת מחדל שגוי!");
define("_PRIMARYDNSREQUIRED", "ה-dns הראשי דרוש!");
define("_INVALIDDNS", "הזנת dns שגוי!");
define("_SELECTIPSETTING", "בחר הגדרת IP..");
define("_SSIDREQUIRED", "ה-SSID דרוש!");
define("_PASSWORDISREQUIRED", "הססמה דרושה!");
define("_WIFIPASSWORDERROR", "הס&#39סמה לא חוק&#39ת, אורך התו ח&#39&#39ב לה&#39ות לפחות 8 ומקס&#39מום 63 <br> תווים חוק&#39&#39ם a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "הס&#39סמה לא חוק&#39ת, אורך התוו&#39ם ח&#39&#39ב לה&#39ות 20,<br>&#8226; הסיסמה חייבת להכיל לפחות שתי אותיות [A-Za-z],<br>&#8226; הסיסמה חייבת להכיל לפחות שתי ספרות [0-9],<br>&#8226; הסיסמה חייבת להכיל לפחות שני תווים מיוחדים [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; הסיסמה לא חוקית, אורך התווים חייב להיות לפחות 12, מקסימום 32,<br>&#8226; הסיסמה חייבת להכיל לפחות שתי אותיות קטנות [a-z], <br>&#8226; הסיסמה חייבת להכיל לפחות שתי אותיות רישיות [A-Z], <br>&#8226; הסיסמה חייבת להכיל לפחות שתי ספרות [0-9],<br>&#8226; הסיסמה חייבת להכיל לפחות שני תווים מיוחדים [!%&/()=?*#+-_]");

define("_WIFISSIDERROR", "SSID אינו חוקי, תווים חוקיים a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "בחר סוג אבטחה");
define("_HOSTIPREQUIRED", "* ה-IP של המארח דרוש!");
define("_CERTMANREQUIRED", "* ניהול האישור דרוש!");
define("_OCPPENABLEALERT", "אם אתה רוצה להשתמש בתחנת הטעינה שלך במצב עצמאי, עליך להשבית תחילה את חיבור ה-OCPP ב&#39תפריט הגדרות OCPP&#39.");
define("_NOTSAVEDALERT", "הדף לא נשמר.");
define("_SAVEQUESTION", "האם ברצונך לשמור את השינויים?");
define("_OKBUTTON", "אישור");
define("_LTECONNECTIONCONFIRM", "ח&#39בור המכשיר הסלולרי יושבת. האם אתה מאשר?");
define("_WIFICONNECTIONCONFIRM", "ח&#39בור ה-Wi-Fi יושבת. האם אתה מאשר?");
define("_DHCPSERVERCONNECTIONCONFIRM", "אם ברצונך להפעיל את שרת LAN DHCP, תחילה עליך להשבית את נקודה חמה של Wi-Fi מ&#39נקודה חמה של Wi-Fi &#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "אם ברצונך להפעיל נקודה חמה של Wi-Fi, תחילה עליך להשבית את שרת ה- DHCP של LAN מ&#39הגדרת IP IP &#39.");

define("_DYNAMIC", "דינמי");
define("_DIAGNOSTICS", "אבחון");
define("_LOCALLOAD", "ניהול עומס מקומי");
define("_DOWNLOAD", "הורד");
define("_STARTDATE", "תאריך התחלה");
define("_ENDDATE", "תאריך סיום");
define("_CLEAREVENTLOGS", "נקה את כל יומני האירועים");
define("_CLEAREVENTLOGSINFO", "זה ימחוק את כל יומני האירועים!");
define("_DOWNLOADEVENTLOGSINFO", "הורד יומני אירועים של מכשיר לתקופה מקסימלית של 5 ימים");
define("_DEVICEEVENTLOGS", "יומני אירועים של מכשיר");
define("_DEVICECHANGELOGS", "יומני שינויים של מכשיר");
define("_LOGSDATEERROR", "אנא בחר תאריכים לתקופה מקסימלית של 5 ימים.");
define("_DOWNLOACHANGELOGS", "הורד יומני שינויים של מכשיר");
define("_VPNFUNCTIONALITY", "פונקציונליות VPN: ");
define("_CERTMANAGEMENT", "נ&#39הול תעודה: ");
define("_NAME", "שם: ");
define("_CONNECTIONINTERFACE", "ממשק חיבור ");
define("_ANY", "כלשהו");
define("_OCPPCONNPARAMETERS", "פרמטרי תצורת OCPP");
define("_SETDEFAULT", "שחזר ערכי ברירת מחדל ");
define("_STANDALONEMODE", "מצב עצמאי");
define("_STANDALONEMODETITLE", "מצב עצמאי:");
define("_STANDALONEMODENOTSELECTED", "* לא ניתן לבחור את המצב העצמאי, כי ה-OCPP מופעל.");
define("_CHARGERWEBUI", "ממשק משתמש אינטרנטי למטען");
define("_SYSTEMMAINTENANCE", "תחזוקת מערכת");
define("_HOSTIP", "IP מארח: ");
define("_PASSWORDERRORLEVEL1", "הסיסמה לא חוקית, אורך התו חייב להיות מינימום 6 תווים ולהכיל לפחות אות קטנה אחת, אות גדולה אחת ותו מספרי אחד!");
define("_SELECTBACKLIGHTDIMMING", "* עליך לבחור את עמעום תאורת הרקע!");
define("_ISREQUIRED", "דרוש!");
define("_ISNOTVALID", "אינו תקף!");
define("_ISDUPLICATED", "הוא משוכפל");
define("_MUSTBENUMERIC", "צריך להיות מספרי!");
define("_VPNFUNCTIONALITYREQUIRED", "* פונקציונליות ה-Vpn דרושה!");
define("_VPNNAMEREQUIRED", "* שם ה-Vpn דרוש!");
define("_VPNPASSWORDREQUIRED", "* ססמת ה-Vpn דרושה!");
define("_EXPLANATION", "מציין שדה חובה.");
define("_FIRMWAREUPDATE", "עדכוני קושחה");
define("_BACKUPRESTORE", "גיבוי ושחזור של התצורה");
define("_SYSTEMRESET", "איפוס מערכת");
define("_CHANGEADMINPASSWORD", "ססמת ניהול");
define("_FACTORYRESET", "ברירת המחדל של היצרן");
define("_FACTORYRESETBUTTON", "איפוס יצרן");
define("_FACTORYDEFAULTCONFIGURATION", "תצורת ברירת המחדל של היצרן");
define("_LOGFILES", "קובצי יומן");
define("_BACKUPFILE", "קובץ גיבוי");
define("_RESTOREFILE", "שחזר קובץ Config");
define("_FREEMODEMAXCHARACTER", "האורך המרבי הוא 32 תווים!");
define("_RESTOREMESSAGE", "האם אתה מאשר להחיל שינויים ולהפעיל מחדש כעת?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "הססמה צריכה להיות באורך של 6 תווים, ולהכיל לפחות אות גדולה אחת, אות קטנה אחת וספרה אחת.");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "הססמה צריכה להיות באורך של 20 תווים והיא מכילה לפחות שתי אותיות, שתי ספרות ושני תווים מיוחדים.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "הסיסמה שלך חייבת להיות לפחות 12, מקסימום 32 תווים והיא מכילה לפחות שתי אותיות רישיות, שתי אותיות קטנות, שתי ספרות ושני תווים מיוחדים.");
define("_BACKTOLOGIN", "חזרה לכניסה");
define("_CHANGE", "Change");
define("_SYSTEMADMINISTRATION", "ניהול מערכת");
define("_UPDATE", "עדכן");
define("_CONFIRM", "אשר");
define("_FACTORYDEFAULTCONFIRM", "האם אתה באמת רוצה לאפס בחזרה לערכי ברירת המחדל של היצרן?");
define("_FILENAME", "שם קובץ");
define("_UPLOAD", "טען");
define("_SELECTFIRMWARE", "בחר במחשב את קובץ עדכון הקושחה");
define("_FIRMWAREFILESIZE", "בדוק את הגודל של קובץ הקושחה.");
define("_FIRMWAREFILETYPE", "בדוק את הסוג של קובץ הקושחה.");

define("_LESSTHANOREQUAL4", "חייב להיות בין 1 ל-4");
define("_LESSTHANOREQUAL20", "צריך להיות 20 ומטה");
define("_LESSTHANOREQUAL65000", "צריך להיות 65,000 ומטה");
define("_LESSTHANOREQUAL300", "צריך להיות 300 ומטה");
define("_LESSTHANOREQUAL86500", "צריך להיות 86,500 ומטה");
define("_LESSTHANOREQUAL10000", "צריך להיות 10,000 ומטה");
define("_LESSTHANOREQUAL22", "צריך להיות 22 ומטה");
define("_LESSTHANOREQUAL10", "צריך להיות 10 ומטה");
define("_LESSTHANOREQUAL600", "צריך להיות 600 ומטה");
define("_LESSTHANOREQUAL120", "צריך להיות 120 ומטה");
define("_HIGHTHANOREQUAL0", "חייב להיות גבוה או שווה ל-0");
define("_CHANGEPASSWORDSUGGESTION", "אנו ממליצים לשנות את ססמת ברירת המחדל דרך תפריט תחזוקת המערכת");

define("_FILESIZE", "בדוק את גודל הקובץ.");
define("_FILETYPE", "בדוק את סוג הקובץ.");

define("_BACKUPVERSIONCHECK", "גרסת קובץ זו לא תואמת את ההתקן.");
define("_HARDRESETCONFIRM", "האם אתה באמת רוצה לבצע איפוס קשיח?");
define("_SOFTRESETCONFIRM", "האם אתה באמת רוצה לבצע איפוס רך?");
define("_NEWSETUP", "היעזר במדריך למשתמש לצורך ההגדרה מחדש.");

define("_LOGOSETTINGS", "הגדרות סמליל");
define("_USELOGO", "בחר קובץ סמליל מהמחשב");
define("_LOGOTYPE", "בחר סמליל בתבנית png.");
define("_LOGODIMENSION", "גודל הסמליל המרבי המותר הוא 80x80‏, בחר סמליל בגודל מתאים.");

define("_SERVICECONTACTINFO", "הצג פרטי קשר לשירות");
define("_SERVICECONTACTINFOCHARACTER", "האורך המרבי של &#39הצג פרטי קשר לשירו&#39הוא 25 תווים!<br>תווים חוקיים a..z 0..9 .+@*");


define("_SCREENTHEME", "הצג ערכת נושא");
define("_DARKBLUE", "כחול כהה");
define("_ORANGE", "כתום");
define("_PLEASEENTERRFIDLOCALLIST", "הזן רשימת RFID מקומית!");

define("_LOADMANAGEMENT", "ניהול עומס");
define("_CPROLE", "תפקיד נקודת טעינה");
define("_GRIDSETTINGS", "הגדרות רשת חשמל");
define("_LOADMANAGEMENTMODE", "מצב ניהול עומס");
define("_LOADMANAGEMENTGROUP", "קבוצת ניהול עומס");
define("_LOADMANAGEMENTOPTION", "אפשרות לנ&#39הול עומס&#39ם");
define("_ALARMS", "התרעות");

define("_MASTER", "מאסטר");
define("_SLAVE", "Slave");
define("_TOTALCURRENTLIMIT", "גבול זרם כולל לפאזה");
define("_SUPPLYTYPE", "סוג אספקה");
define("_FIFOPERCANTAGE", "אחוז נר\"יר");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "בחלוקה שווה");
define("_COMBINED", "משולב");
define("_TOTALCURRENTLIMITERROR", "גבול הזרם הכולל לפאזה דרוש!");
define("_LESSTHAN1024", "חייב לה&#39ות פחות מ-1024");
define("_ATLEAST0", "חייב להיות לפחות 0");
define("_MORETHAN12", "חייב לה&#39ות &#39ותר מ-12");
define("_CHOOSEONE", "בחר אחד");
define("_SLAVEMINCHCURRENT", "הגדרת זרם טעינה לא מקוון");
define("_SERIALNO", "מספר סידורי");
define("_CONNECTORSTATE", "מצב המחבר");
define("_NUMBEROFPHASES", "מספר הפאזות");
define("_PHASECONSEQUENCE", "רצף חיבור פאזות");
define("_VIP", "טעינת VIP");
define("_CPMODE", "CP Mode");
define("_VIPERROR", "טעינת ה-VIP דרושה");
define("_PHASECONSEQUENCEERROR", "רצף חיבור הפאזות דרוש!");
define("_CPMODEERROR", "מצב ה-CP דרוש!");
define("_SUPPORTEDCURRENT", "זרם נתמך");
define("_INSTANTCURPERPHASE", "פאזת זרם רגעי");
define("_FIFOCHARGINGPERCENTAGE", "אחוז טעינת נר\"יר");
define("_MINIMUMCURRENT1P", "זרם טעינה מינימלי חד-פאזי");
define("_MINIMUMCURRENT3P", "זרם טעינה מינימלי תלת-פאזי");
define("_MAXIMUMCURRENT", "זרם טעינה מרבי");
define("_STEP", "שלב");
define("_UPDATEDLMGROUP", "עדכן קבוצת DLM");
define("_MAINCIRCUITCURRENT", "זרם רשת מקסימלי");
define("_MAINCIRCUITCURRENTERROR", "נדרש זרם רשתמקסימלי!");
define("_DLMMAXCURRENT", "מגבלת זרם כוללת של DLM לכל שלב");
define("_DLMMAXCURRENTERROR", "נדרשת מגבלת זרם כוללת של DLM לכל שלב!");
define("_DLMMAXCURRENTMORETHANMAIN", "מגבלת הזרם הכוללת של DLM צריכה להיות יותר ממחצית מזרם מפסק המעגל הראשי");
define("_DLMMAXCURRENTLESSTHANMAIN", "מגבלת הזרם הכוללת של DLM צריכה להיות פחותה מזרם מפסק המעגל הראשי");

define("_DHCPSERVER", "שרת DHCP");
define("_DHCPCLIENT", "לקוח DHCP");

define("_MAXDHCPADDRRANGE", "כתובת IP קשה של שרת DHCP");
define("_MINDHCPADDRRANGE", "כתובת IP התחלת&#39ת של שרת DHCP");

define("_MAXDHCPADDRRANGEERROR", "נדרשת כתובת IP קצה של שרת DHCP!");
define("_MINDHCPADDRRANGEERROR", "נדרשת כתובת IP התחלתית של שרת DHCP!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "כתובת IP הקצה של שרת DHCP ח&#39&#39בת לה&#39ות גדולה מכתובת IP ההתחלת&#39ת של שרת DHCP");
define("_IPADDRESSRANGE", "כתובת IP א&#39נה &#39כולה לה&#39ות בעלת ערך שב&#39ן שרת DHCP בתחלת&#39 וכתובת IP קצה");
define("_INVALIDSUBNET", "כתובת IP א&#39נה תת-רשת אמ&#39ת&#39ת");

define("_CONNECTIONSTATUS", "מצב חיבור");

define("_INSTALLATIONSETTINGS", "הגדרות התקנה");
define("_EARTHINGSYSTEM", "מערכת הארקה");
define("_CURRENTLIMITERSETTINGS", "הגדרות מגביל זרם");
define("_CURRENTLIMITERPHASE", "מופע מגביל זרם");
define("_CURRENTLIMITERVALUE", "ערך מגביל זרם");
define("_UNBALANCEDLOADDETECTION", "זיהוי עומס לא מאוזן");
define("_EXTERNALENABLEINPUT", "קלט מאופשר חיצוני");
define("_LOCKABLECABLE", "כבל נעיל");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "גבול הזרם הכולל של ממטב ההספק");
define("_POWEROPTIMIZER", "מייעל כוח");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "חד-פאזי");
define("_THREEPHASE", "תלת-פאזי");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "גבול הזרם הכולל של <br> ממטב ההספק צריך <br> להיות 16 ומעלה");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "גבול הזרם הכולל <br> של ממטב ההספק <br> צריך להיות 100 ומטה");
define("_FOLLOWTHESUN", "עקוב אחרי השמש");
define("_FOLLOWTHESUNMODE", "עקוב אחר מצב השמש");
define("_AUTOPHASESWITCHING", "החלפת פאזות אוטומטית");
define("_MAXHYBRID", "מקסימום היברידי");
define("_SUNONLY", "שמש בלבד");
define("_SUNHYBRID", "היברידי שמש");

define("_DISPLAYBACKLIGHTSETTINGS", "הצג הגדרות תאורת רקע");
define("_BACKLIGHTLEVEL", "עוצמת תאורת רקע");
define("_SUNRISETIME", "שעת הזריחה ");
define("_SUNSETTIME", "שעת השקיעה");

define("_HIGH", "גבוהה");
define("_MID", "בינונית");
define("_LOW", "נמוכה");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* כאשר EVReadySupport פועל ושלב הגבול הנוכחי הוא שלב אחד, ערך הגבול הנוכחי לא יכול להיות פחות מ-8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* כאשר EVReadySupport פועל ושלב הגבול הנוכחי הוא תלת פאזי, ערך הגבול הנוכחי לא יכול להיות פחות מ-14!");
define("_LEDDIMMINGSETTINGS", "הגדרות עמעום לד");
define("_LEDDIMMINGLEVEL", "רמת עמעום לד");
define("_VERYLOW", "מאוד נמוך");

define("_CELLULARGATEWAYCONFIRM", "השער הסלולר&#39 &#39ושבת");

define("_ETHERNETIP", "IP ממשק Ethernet:");
define("_WLANIP", "IP ממשק WLAN:");
define("_STRENGTH", "כוח");
define("_WIFIFREQ", "תדירות");
define("_WIFILEVEL", "רָמָה");
define("_CELLULARIP", "&#39של ממשק סלולר IP:");
define("_CELLULAROPERCODE" , "מַפעִיל");
define("_CELLULARTECH" , "טֶכנוֹלוֹגִיָה");
define("_APPLICATIONRESTART", "ש&#39נו&#39 זה מח&#39&#39ב הפעלה מחדש של ה&#39&#39שום.");
define("_ACCEPTQUESTION", "?האם אתה מקבל את הש&#39נו&#39&#39ם");
define("_SCANNETWORKS" , "סרוק רשתות");
define("_AVAILABLENETWORKS" , "רשתות זמינות");
define("_NETWORKSTATUS" , "סטטוס רשת");
define("_PLEASEWAITMSG" , "אנא המתן...");
define("_SCANNINGWIFIMSG" , "סריקת רשתות Wi-Fi");
define("_NOWIFIFOUNDMSG" , "לא נמצאו רשתות Wi-Fi");
define("_PLEASECHECKWIFICONNMSG" , "אנא בדוק את חיבור ה-Wi-Fi שלך ונסה שוב.");

define("_QRCODE", "הצג קוד QR");
define("_QRCODEONSCREEN", "קוד QR על המסך");
define("_QRCODEDELIMITER", "מפרד&#39 קוד QR");
define("_INVALIDDELIMITERCHARACTER", "ק#39&רא קוד ה-QR א#39&נו חוק#39&, תו רווח לא מקובל, אורך התו ח#39&#39&ב לה#39&ות לפחות 1 ומקס#39&מום של 3, <br>תוו#39&ם חוק#39&#39&ם 0..9 .,:;!#^+ $%&/() {[]}=*?-_@<>|");

define("_LOCATION", "מקום");
define("_INDOOR", "מקורה");
define("_OUTDOOR", "בָּחוּץ");
define("_POWEROPTIMIZEREXTERNALMETER", "מד חיצוני");
define("_OPERATIONMODE", "מצב הפעלה");
define("_AUTOSELECTED", "נבחר אוטומט&#39");
define("_NOTSELECTED", "לא נבחר");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "בח&#39רת מצב טעינה ותצורת &#39&#39עול ההספק");

define("_USERINTERACTION", "א&#39נטראקצ&#39ה של משתמש&#39ם");
define("_STANDBYLEDBEHAVIOUR", "התנהגות LED המתנה");
define("_OFF", "&#39כבו");
define("_ON", "עַל");

define("_LOADSHEDDINGMINIMUMCURRENT", "זרם מינימלי של הורדת עומסים");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "זרם מרבי לזיהוי עומס לא מאוזן");

define("_SCHEDULEDCHARGING", "טע&#39נה מתוזמנת");
define("_OFFPEAKCHARGING", "טע&#39נה מחוץ לש&#39א");
define("_OFFPEAKCHARGINGWEEKENDS", "סופ&#39 שבוע של טע&#39נה לא ש&#39א");
define("_OFFPEAKCHARGINGPERIODS", "תקופות טע&#39נה לא ש&#39א");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "המשך טעינה לאחר סיום פרק הזמן של השיא");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "המשך טעינה ללא אוטנטיקציה מחדש לאחר אובדן כוח");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "משך זמן של <br> מרב&#39 בהשה&#39ה אקרא&#39ת (שניות)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* נדרש משך זמן מ&#39רב&#39 של ע&#39כוב אקראי!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* משך הזמן המרב&#39 של ע&#39כוב אקרא&#39 ח&#39&#39ב להיות מספר שלם!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* משך הזמן המקס&#39מל&#39 של ע&#39כוב אקרא&#39 צר&#39ך לה&#39ות ב&#39ן 0 ל-1800!");
define("_OFFPEAKCHARGINGPERIODSERROR", "* נדרשות תקופות טע&#39נה מחוץ לש&#39א!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* זמן התחלה וס&#39ום של טע&#39נה מחוץ לש&#39א לא &#39כול לה&#39ות זהה!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "#39&טעינה לא ש&#39א פרק זמן שנ");
define("_OFFPEAKDISABLEDCONFIRM", "יושבת. טע&#39נה מחוץ לש&#39א תושבת?");
define("_SHOWSERVICECONTACTINFO", "הצג פרט#39& קשר של ש#39&רות נוסף");
define("_EXTRASERVICECONTACTINFORMATION", "מ#39&דע ל#39&צ#39&רת קשר עם הש#39&רות מוצג בכבל הטע#39&נה Connect, הכנה לטע#39&נה, אתחול והמתנה למסכ#39& ח#39&בור");

define("_LOADSHEDDINGSTATUS", "סטטוס הורדת עומסים:");
define("_ACTIVE", "פָּעִיל");
define("_INACTIVE", "לֹא פָּעִיל");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "אם אתה רוצה להשתמש באפשרות ניהול העומס שלך ב-Modbus,<br>תחילה עליך להשבית את מגבלת הזרם הכוללת של Power Optimizer<br>מ-&#39בחירת מצב טעינה ותצורת Power Optimizer&#39.");
define("_MODBUSALERT", "אם ברצונך להפעיל את מד החיצוני Power Optimizer שלך,<br>תחילה עליך לבטל את פעילות Modbus<br>מ-&#39ניהול עומסים מקומיים&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "אם ברצונך להשתמש באפשרות ניהול העומס במצב Master/Slave, עליך תחילה להשבית את ממצא הכוח מתוך &#39בחירת מצב טעינה ותצורת ממצא הכוח&#39.");
define("_DLMALERT", "אם ברצונך להפעיל את ממצע הכוח שלך, עליך תחילה להשבית את Master/Slave מתוך &#39ניהול עומס מקומי&#39.");

define("_FOLLOWTHESUNDLMENABLEALERT", "אם ברצונכם להשתמש באופציית ניהול העומס כ-Master/Slave<br>, עליכם קודם לבטל את מעקב השמש בהגדרות המהדר אופטימיזר האנרגיה.");
define("_DLMALERTFOLLOWTHESUN", "כדי להפעיל את מעקב השמש, עליך להשבית קודם כל את Master/Slave #39&ייב בניהול עומס מקומי.");

define("_RESETUSERPASSWORD", "אפס את <br> סיסמת המשתמש");
define("_INSTALLATIONERRORENABLEDCONFIRM", "אם ברצונך להשבית את הפעלת שגיאת התקנה,<br>תחילה עליך להגדיר את מערכת הארקה מ-&#39הגדרות התקנה&#39 ל-IT/שלב מפוצל.");
define("_EARTHINGSYSTEMCONFIRM", "אם ברצונך להגדיר את מערכת הארקה ל-TN/TT,<br>תחילה עליך להפעיל את הפעלת שגיאת התקנה מ-&#39OCPP Settings&#39.");

define("_AUTHKEYMAXLIMIT", "האורך צריך להיות מקסימום 40 תווים.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "שדה Authorization Key ר&#39ק.<br>האם אתה מאשר את הש&#39נו&#39ם?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "עיכוב אקראי ב-Off Peak End");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "זרם מאובטח");
define("_FAILSAFECURRENTERROR", "יש צורך ב-Failsafe Current!");
define("_FAILSAFECURRENTLESSTHAN0", "* Failsafe הערך הנוכחי לא יכול להיות קטן מ-0!");
define("_FAILSAFECURRENTMORETHAN32", "* Failsafe הערך הנוכחי לא יכול להיות יותר מ-32!");
define("_FAILSAFECURRENTMORETHAN50", "* Failsafe הערך הנוכחי לא יכול להיות יותר מ-50!");

define("_LOCALCHARGESESSION", "היגע טשאַרדזשינג סעשאַנז");
define("_ROWNUMBER", "שורה נומער");
define("_SESSIONUUID", "אָפּצאָל שייַן");
define("_AUTHORIZATIONUID", "קוד RFID");
define("_STARTTIME", "אָנהייב צייַט");
define("_STOPTIME", "סוף צייט");
define("_TOTALTIME", "גאַנץ צייט");
define("_STATUS", "סטטוס");
define("_CHARGEPOINTIDS", "מספר שקע");
define("_INITIALENERGY", "ערשט ענערגיע(kWh)");
define("_LASTENERGY", "סוף ענערגיע(kWh)");
define("_TOTALENERGY", "אנרגיה כוללת (בקוט)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "יומן הפעלה מלא ב-CSV");
define("_DOWNLOADFULLSESSIONLOGS", "סיכום כניסה ב-CSV");
define("_STARTDATE", "תאריך התחלה");
define("_ENDDATE", "תאריך סיום");
define("_RFIDSELECTION", "בחירת RFID");
define("_CLEAR", "ברור");

define("_FALLBACKCURRENT", "זרם נפילה");
define("_FALLBACKRANGE", "זרם החזרה חייב להיות 0 או בטווח של ");
define("_DOWNLOADEEBUSLOGS", "EEBUS Logs");
define("_PAIRINGENERGYMANAGER", "מופעל עבור צימוד");
define("_PAIR", "Pir Enable");
define("_UNPAIR", "Unpair");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "גירסת קושחה");
define("_EEBUSDISCOVERY", "התקנים שהתגלו");
define("_REFRESH", "רענן");
define("_CPROLEMASTERREQUIREDFIELD", "אם ברצונך לעדכן את ההגדרות של קבוצת ניהול עומסים, יש לשמור את תפקיד נקודת הטעינה בתור &#39Master&#39 מהגדרות כלליות של ניהול עומסים.");

define("_LISTOFSLAVES", "Popis robova");
define("_NUMBEROFSLAVES", "Broj robova");
define("_LISTOFCONNECTOR", "Popis konektora");
define("_AVAILABLECURRENT", "Dostupna trenutna faza");

define("_DLMINTERFACE", "ממשק DLM");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "אפשר WiFi ממשקי רשת!");

define("_MUSTBEINTEGER", "ח&#39&#39ב לה&#39ות מספר שלם!");
define("_GRIDBUFFER", "אחוז מרווח הגנת רשת");
define("_CHARGINGSTATUSALERT", "במצב הטעינה לא ניתן לעדכן את הערך!");
define("_READUNDERSTAND", "קראתי, אני מבין");

define("_MORETHAN10", "עליך להגדיל את זרם הרשת המרבי או להקטין את אחוז שול ההגנה על הרשת לפני שמירת10-ההגדרות הללו. מגבלת זרם הרשת המרבי לא יכולה להיות נמוכה מA בעת שימוש באחוז שול ההגנה עלהרשת.");

define("_CLUSTERMAXCURRENT", "זרם מרבי באשכול");
define("_CLUSTERFAILSAFECURRENT", "אשכול Failsafe Current");
define("_CLUSTERMAXCURRENTERROR", "דרוש זרם מרבי באשכול!");
define("_CLUSTERFAILSAFECURRENTERROR", "יש צורך ב-Cluster !Failsafe Current");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "הערך Cluster Failsafe הנוכחי לא יכול להיות קטן מ-0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "ערך ה-Cluster חייב Failsafe Current להיות נמוך מ- Maximum Grid Current!");
define("_CLUSTERFAILSAFE", "מצב בטיחותי באשכול");

define("_CLUSTERMAXCURRENTLESSTHAN0", "1מקסימום אשכול הערך הנוכחי לא יכול להיות קטן מ-0!");
define("_CLUSTERMAXCURRENTMORETHAN", "ערך הזרם המרבי של האשכול חייב להיות שווה או קטן מהערך הזה:");