<?php
include_once "access_control.php";
define("_LOGIN", "LOG IND");
define("_USERNAME", "Brugernavn:");
define("_PASSWORD", "Adgangskode:");
define("_CHANGEPASSWORD", "Skift adgangskode");
define("_CURRENTPASSWORD", "Nuværende adgangskode:");
define("_NEWPASSWORD", "Ny adgangskode:");
define("_CONFIRMNEWPASSWORD", "Bekræft ny adgangskode:");
define("_SUBMIT", "Send");
define("_CURRENTPASSWORDREQUIRED", "En nuværende adgangskode er påkrævet");
define("_PASSWORDREQUIRED", "Adgangskode er påkrævet");
define("_USERNAMEREQUIRED", "Brugernavn er påkrævet");
define("_USERAUTHFAILED", "Brugergodkendelse mislykkedes!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Brugernavn eller nuværende adgangskode er forkert!");
define("_DBACCESSFAILURE", "Kan ikke få adgang til databasen!");
define("_CHANGEPASSWORDERROR", "Du skal først skifte din adgangskode!");
define("_SAMEPASSWORDERROR", "Den nuværende og den nye adgangskode skal være forskellige!");
define("_PASSWORDMATCHERROR", "Adgangskoder stemmer ikke overens!");
define("_CURRENTPASSWORDWRONG", "Nuværende adgangskode er forkert!");
define("_PASSWORDERRORLEVEL2", "Adgangskoden er ugyldig, tegnlængden skal være 20 og indeholde mindst to bogstaver [A-Za-z], to cifre [0-9] og to specialtegn [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Adgangskoden er ugyldig, tegnlængden skal være på mindst 12, maksimalt 32 tegn og indeholde mindst to små [a-z] og to store bogstaver  [A-Z], to tal [0-9] og mindst to specialtegn [!%&/()=?*#+-_].");
define("_LOGINLOCKOUT", "Alt for mange mislykkede forsøg. Prøv venligst efter 1800 sekunder.");

define("_MAINPAGE", "Forside");
define("_GENERAL", "Generelle indstillinger");
define("_OCPPSETTINGS", "OCPP-indstillinger");
define("_NETWORKINTERFACES", "Netværks grænseflader");

define("_OCPPCONNINTERFACE", "OCPP-forbindelse : ");
define("_CONNECTIONSTATE", "Tilslutningsstatus : ");
define("_DISCONNECTED", "Afbrudt");
define("_NEEDTOLOGINFIRST", "Du skal først logge ind!");
define("_CONNECTED", "Tilsluttet");
define("_CPSERIALNUMBER", "CP-serienummer : ");
define("_HMISOFTWAREVERSION", "HMI-softwareversion : ");
define("_OCPPSOFTWAREVERSION", "OCPP-softwareversion : ");
define("_POWERBOARDSOFTWAREVERSION", "Softwareversion for strømkort : ");
define("_OCPPDEVICEID", "OCPP-enheds-ID : ");
define("_DURATIONAFTERPOWERON", "Varighed efter at strømmen er sat til : ");
define("_LOGOUT", "Log ud");
define("_PRESET", "Forudindstillinger:");

define("_OCPPCONNECTION", "OCPP-forbindelse");
define("_ENABLED", "Aktiveret");
define("_DISABLED", "Deaktiveret");
define("_CONNECTIONSETTINGS", "Tilslutningsindstillinger");
define("_CENTRALSYSTEMADDRESS", "Central systemadresse ");
define("_CHARGEPOINTID", "ID opladningspunkt ");
define("_OCPPVERSION", "OCPP-version");
define("_SAVE", "Gem");
define("_SAVESUCCESSFUL", "Gemt.");
define("_CENTRALSYSTEMADDRESSERROR", "Central systemadresse påkrævet!");
define("_CHARGEPOINTIDERROR", "Opladningspunkts-ID er påkrævet!");
define("_SECONDS", "Sekunder");
define("_ADD", "Tilføj");
define("_REMOVE", "Fjern");
define("_SAVECAPITAL", "GEM");
define("_CANCEL", "Annuller");

define("_CELLULAR", "Mobil");
define("_INTERFACEIPADDRESS", "Grænseflade-IP-adresse: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "APN-navn: ");
define("_APNUSERNAME", "APN-brugernavn: ");
define("_APNPASSWORD", "APN-adgangskode: ");
define("_IPSETTING", "IP-indstillinger: ");
define("_IPADDRESS", "IP-adresse: ");
define("_NETWORKMASK", "Netværksmaske: ");
define("_DEFAULTGATEWAY", "Standardgateway: ");
define("_PRIMARYDNS", "Primær DNS: ");
define("_SECONDARYDNS", "Sekundær DNS: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Sikkerhed: ");
define("_SECURITYTYPE", "Vælg sikkerhedstype");
define("_NONE", "Ingen");
define("_SELECTMODE", "Vælg tilstand!");
define("_RFIDLOCALLIST", "RFID lokal liste");
define("_ACCEPTALLRFIDS", "Godkend alle RFID’er");
define("_MANAGERFIDLOCALLIST", "Administrer RFID lokal liste:");
define("_AUTOSTART", "Autostart");
define("_PROCESSING", "Bearbejdning... Vent venligst...");
define("_MACADDRESS", "MAC-adresse: ");
define("_WIFIHOTSPOT", "Wi-Fi-hotspot");
define("_TURNONDURINGBOOT", "Tænd under opstart: ");
define("_AUTOTURNOFFTIMEOUT", "Automatisk slukning af timeout: ");
define("_AUTOTURNOFF", "Automatisk sluk: ");
define("_HOTSPOTALERTMESSAGE", "Ændringer af hotspot-indstillinger træder i kraft næste gang enheden tændes. ");
define("_HOTSPOTREBOOTMESSAGE", "Vil du genstarte nu? ");

define("_DOWNLOADACLOGS", "Download AC-logs");
define("_DOWNLOADCELLULARLOGS", "Download logs for mobile moduler");
define("_DOWNLOADPOWERBOARDLOGS", "Download logs for strømkort");
define("_PASSWORDRESETSUCCESSFUL", "Din adgangskode er ændret.");
define("_DBOPENEDSUCCESSFULLY", "Database er åbnet\n");
define("_WSSCERTSSETTINGS", "WSS-certifikatindstillinger ");
define("_CONFKEYS", "Konfigurationsnøgler");
define("_KEY", "Nøgle");
define("_STATIC", "Statisk");
define("_TIMEZONE", "Tidszone");
define("_PLEASESELECTTIMEZONE", "Vælg tidszone");
define("_DISPLAYSETTINGS", "Visningsindstillinger");
define("_DISPLAYLANGUAGE", "Visningssprog");
define("_BACKLIGHTDIMMING", "Dæmpning af baggrundslys : ");
define("_PLEASESELECT", "Vælg");
define("_TIMEBASED", "Tidsbaseret");
define("_SENSORBASED", "Sensorbaseret");
define("_BACKLIGHTDIMMINGLEVEL", "Dæmpningsniveau for baggrundslys : ");
define("_BACKLIGHTTHRESHOLD", "Grænse for baggrundslys : ");
define("_SETMIDTHRESHOLD", "SetMidThreshold");
define("_SETHIGHTHRESHOLD", "SetHighThresold");
define("_LOCALLOADMANAGEMENT", "Lokal belastningsstyring");
define("_MINIMUMCURRENT", "Minimum strømstyrke: ");
define("_FIFOPERCENTAGE", "FIFO-procent: ");
define("_GRIDMAXCURRENT", "Grid maksimal strømstyrke: ");
define("_MASTERIPADDRESS", "IP-adresse for master: ");
define("_BACKLIGHTTIMESETTINGS", "Tidsindstillinger for baggrundslys: ");
define("_SHOULDSELECTTIMEZONE", "* Du skal vælge tidszone!");
define("_MINIMUMCURRENTREQUIRED", "* Minimum strømstyrke er påkrævet!");
define("_CURRENTMUSTBENUMERIC", "* Strømstyrke skal være numerisk!");
define("_FIFOPERCREQUIRED", "* FIFO-procent er påkrævet!");
define("_FIFOPERCSHOULDBETWEEN", "* FIFO-procent skal ligge mellem 0 og 100!");
define("_PERCMUSTBENUMERIC", "* Procent skal være numerisk!");
define("_GRIDMAXCURRENTREQUIRED", "* Grid-maksimumstyrke er påkrævet!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Gridstrømstyrke skal være numerisk!");
define("_IPADDRESSOFMASTERREQUIRED", "* IP-adresse på masker er påkrævet!");
define("_INVALIDIPADDRESS", "* Du har indtastet en ugyldig IP-adresse!");
define("_SAMENETWORKLAN", "* Du har indtastet en IP-adresse i det samme netværk med LAN!");
define("_SAMENETWORKWLAN", "* Du har indtastet en IP-adresse i det samme netværk med WLAN!");
define("_APNISREQUIRED", "APN er påkrævet!");
define("_IPADDRESSREQUIRED", "IP-adresse er påkrævet!");
define("_NETWORKMASKREQUIRED", "Netværksmaske er påkrævet!");
define("_INVALIDNETWORKMASK", "* Du har indtastet en ugyldig netværksmaske!");
define("_DEFAULTGATEWAYREQUIRED", "Standardgateway er påkrævet!");
define("_INVALIDGATEWAY", "Du har indtastet en ugyldig standardgateway!");
define("_PRIMARYDNSREQUIRED", "Primær DNS er påkrævet!");
define("_INVALIDDNS", "Du har indtastet en ugyldig DNS!");
define("_SELECTIPSETTING", "Vælg IP-indstillinger.");
define("_SSIDREQUIRED", "SSID er påkrævet!");
define("_PASSWORDISREQUIRED", "Adgangskode er påkrævet!");
define("_WIFIPASSWORDERROR", "Adgangskoden er ugyldig, tegnlængden skal være minimum 8 og højst 63 <br> gyldige tegn a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=* ?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Adgangskoden er ugyldig, tegnlængden skal være 20,<br>&#8226; Adgangskoden skal indeholde mindst to bogstaver [A-Za-z],<br>&#8226; Adgangskoden skal indeholde mindst to cifre [0-9],<br>&#8226; Adgangskoden skal indeholde mindst to specialtegn [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Adgangskoden er ugyldig, tegnlængden skal være mindst 12, maksimalt 32,<br>&#8226; Adgangskoden skal indeholde mindst to små bogstaver [a-z], <br>&#8226; Adgangskoden skal indeholde mindst to store bogstaver [A-Z], <br>&#8226; Adgangskoden skal indeholde mindst to cifre [0-9],<br>&#8226; Adgangskoden skal indeholde mindst to specialtegn [!%&/()=?*#+-_]");
define("_WIFISSIDERROR", "SSID er ugyldigt, gyldige tegn a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Vælg sikkerhedstype");
define("_HOSTIPREQUIRED", "* Host-IP er påkrævet!");
define("_CERTMANREQUIRED", "* Certificeringsadministration er påkrævet!");
define("_OCPPENABLEALERT", "Hvis du ønsker at bruge din ladestation i standalonetilstand, skal du først deaktivere OCPP-forbindelse i &#39OCPP-indstillingsmenuen.");
define("_NOTSAVEDALERT", "Siden blev ikke gemt.");
define("_SAVEQUESTION", "Vil du gemme ændringerne?");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Mobiltilslutning vil blive deaktiveret. Bekræfter du det?");
define("_WIFICONNECTIONCONFIRM", "Wi-Fi-tilslutning vil blive deaktiveret. Bekræfter du det?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Hvis du vil aktivere LAN DHCP-server,<br>skal du først deaktivere Wi-Fi Hotspot<br>fra &#39Wi-Fi Hotspot&#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Hvis du vil aktivere Wi-Fi Hotspot,<br>skal du først deaktivere LAN DHCP-server<br>fra &#39LAN IP Setting&#39.");

define("_DYNAMIC", "Dynamisk");
define("_DIAGNOSTICS", "Diagnostik");
define("_LOCALLOAD", "Lokal belastningsstyring");
define("_DOWNLOAD", "Download");
define("_STARTDATE", "Startdato");
define("_ENDDATE", "Slutdato");
define("_CLEAREVENTLOGS", "Ryd alle hændelseslogs");
define("_CLEAREVENTLOGSINFO", "Dette vil rydde alle hændelseslogs!");
define("_DOWNLOADEVENTLOGSINFO", "Download enhedens hændelseslogs for en maksimalt periode på 5 dage");
define("_DEVICEEVENTLOGS", "Enhedens hændelseslogs");
define("_DEVICECHANGELOGS", "Enhedens ændringslogs");
define("_LOGSDATEERROR", "Vælg venligst datoer for en maksimal periode på 5 dage.");
define("_DOWNLOACHANGELOGS", "Download enhedens ændringslogs");
define("_VPNFUNCTIONALITY", "VPN-funktionalitet: ");
define("_CERTMANAGEMENT", "Certificeringsstyring: ");
define("_NAME", "Navn: ");
define("_CONNECTIONINTERFACE", "Tilslutningsgrænseflade ");
define("_ANY", "Enhver");
define("_OCPPCONNPARAMETERS", "OCPP-konfigurationsparametre");
define("_SETDEFAULT", "Sæt til standard ");
define("_STANDALONEMODE", "Standalone tilstand");
define("_STANDALONEMODETITLE", "Standalonetilstand:");
define("_STANDALONEMODENOTSELECTED", "* Standalonetilstand kan ikke vælges, da OCPP er aktiveret.");
define("_CHARGERWEBUI", "Opladerens webbrugergrænseflade");
define("_SYSTEMMAINTENANCE", "Systemvedligeholdelse");
define("_HOSTIP", "Værts-IP: ");
define("_PASSWORDERRORLEVEL1", "Adgangskoden er ugyldig, tegnlængden skal være minimum 6 tegn og indeholde mindst 1 lille bogstav, 1 stort bogstav og 1 numerisk tegn!");
define("_SELECTBACKLIGHTDIMMING", "* Du skal vælge dæmpning af baggrundslys!");
define("_ISREQUIRED", "er påkrævet!");
define("_ISNOTVALID", "er ikke gyldig!");
define("_ISDUPLICATED", "er duplikeret!");
define("_MUSTBENUMERIC", "skal være numerisk!");
define("_VPNFUNCTIONALITYREQUIRED", "* VPN-funktionalitet er påkrævet!");
define("_VPNNAMEREQUIRED", "* VPN-navn er påkrævet!");
define("_VPNPASSWORDREQUIRED", "* VPN-adgangskode er påkrævet!");
define("_EXPLANATION", "Angiver krævet felt.");
define("_FIRMWAREUPDATE", "Firmwareopdateringer");
define("_BACKUPRESTORE", "Konfiguration af backup og gendannelse");
define("_SYSTEMRESET", "Systemnulstilling");
define("_CHANGEADMINPASSWORD", "Administrationsadgangskode");
define("_FACTORYRESET", "Fabriksstandard");
define("_FACTORYRESETBUTTON", "Fabriksnulstilling");
define("_FACTORYDEFAULTCONFIGURATION", "Konfiguration af fabriksstandard");
define("_LOGFILES", "Logfiler");
define("_BACKUPFILE", "Backupfiler");
define("_RESTOREFILE", "Gendan konfigurationsfil");
define("_FREEMODEMAXCHARACTER", "skal være på maksimalt 32 tegn!");
define("_RESTOREMESSAGE", "Bekræfter du at anvende ændringer og genstarte nu?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "Din adgangskode skal være på 6 tegn og skal indeholde mindst et stort bogstav,
mindst et lille bogstav og et tal.");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Dit kodeord skal være på 20 tegn, og det skal indeholde mindst to bogstaver,
to talcifre og to specialtegn.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Dit kodeord skal være på minimum 12, maksimalt 32 tegn,
og det skal indeholde mindst to store bogstaver, to små bogstaver, to talcifre og to specialtegn.");
define("_BACKTOLOGIN", "Tilbage til login");
define("_CHANGE", "Skift");
define("_SYSTEMADMINISTRATION", "Systemadministration");
define("_UPDATE", "Opdater");
define("_CONFIRM", "Bekræft");
define("_FACTORYDEFAULTCONFIRM", "Er du sikker på at du ønsker at nulstille til fabriksindstillinger?");
define("_FILENAME", "Filnavn");
define("_UPLOAD", "Upload");
define("_SELECTFIRMWARE", "Vælg firmwareopdateringsfil fra PC");
define("_FIRMWAREFILESIZE", "Kontroller størrelsen på firmwarefilen.");
define("_FIRMWAREFILETYPE", "Kontroller typen på firmwarefilen.");

define("_LESSTHANOREQUAL4", "skal være mellem 1 og 4");
define("_LESSTHANOREQUAL20", "skal være mindre end eller lig med 20");
define("_LESSTHANOREQUAL65000", "skal være mindre end eller lig med 65000");
define("_LESSTHANOREQUAL300", "skal være mindre end eller lig med 300");
define("_LESSTHANOREQUAL86500", "skal være mindre end eller lig med 86500");
define("_LESSTHANOREQUAL10000", "skal være mindre end eller lig med 10000");
define("_LESSTHANOREQUAL22", "skal være mindre end eller lig med 22");
define("_LESSTHANOREQUAL10", "skal være mindre end eller lig med 10");
define("_LESSTHANOREQUAL600", "skal være mindre end eller lig med 600");
define("_LESSTHANOREQUAL120", "skal være mindre end eller lig med 120");
define("_HIGHTHANOREQUAL0", "skal være højere end eller lig med 0");
define("_CHANGEPASSWORDSUGGESTION", "Vi anbefaler at du skifter din standardadgangskode fra systemvedligeholdelsesmenuen");

define("_FILESIZE", "Kontroller størrelsen på filen.");
define("_FILETYPE", "Kontroller typen på filen.");

define("_BACKUPVERSIONCHECK", "Versionen på denne fil passer ikke til enheden.");
define("_HARDRESETCONFIRM", "Er du sikker på at du vil lave en hård nulstilling?");
define("_SOFTRESETCONFIRM", "Er du sikker på at du vil lave en blød nulstilling?");
define("_NEWSETUP", "Brug brugervejledningen til den nye indstilling.");

define("_LOGOSETTINGS", "Logo-indstillinger");
define("_USELOGO", "Vælg logofil fra PC");
define("_LOGOTYPE", "Vælg et logo i PNG-format.");
define("_LOGODIMENSION", "Den maksimalt tilladte logostørrelse er 80x80, vælg et logo i den rigtige størrelse.");

define("_SERVICECONTACTINFO", "Kontaktoplysninger til Displayservice");
define("_SERVICECONTACTINFOCHARACTER", "Kontaktoplysninger til Displayservice må højst være på 25 tegn!<br>Gyldige tegn a..z 0..9 .+@*");

define("_SCREENTHEME", "Displaytema");
define("_DARKBLUE", "Mørk blå");
define("_ORANGE", "Orange");
define("_PLEASEENTERRFIDLOCALLIST", "Indtast RFID lokal liste!");

define("_LOADMANAGEMENT", "Belastningsstyring");
define("_CPROLE", "Charge Point Role");
define("_GRIDSETTINGS", "Grid-indstillinger");
define("_LOADMANAGEMENTMODE", "Belastningsstyringstilstand");
define("_LOADMANAGEMENTGROUP", "Belastningsstyringsgruppe");
define("_LOADMANAGEMENTOPTION", "Indstilling for belastningshåndtering");
define("_ALARMS", "Alarmer");

define("_MASTER", "Master");
define("_SLAVE", "Slave");
define("_TOTALCURRENTLIMIT", "Total strømbegrænsning pr. fase");
define("_SUPPLYTYPE", "Forsyningstype");
define("_FIFOPERCANTAGE", "FIFO Percentage");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Lige delt");
define("_COMBINED", "Kombineret");
define("_TOTALCURRENTLIMITERROR", "Total strømbegrænsning pr. fase er påkrævet!");
define("_LESSTHAN1024", "skal være under 1024");
define("_ATLEAST0","skal være mindst 0");
define("_MORETHAN12", "skal være over 12");
define("_CHOOSEONE", "Vælg en");
define("_SLAVEMINCHCURRENT", "Offline fejlsikker opladningsstrømindstilling");
define("_SERIALNO", "Serienummer");
define("_CONNECTORSTATE", "Stiktilstand");
define("_NUMBEROFPHASES", "Antal faser");
define("_PHASECONSEQUENCE", "Fasestik-sekvens");
define("_VIP", "VIP-opladning");
define("_CPMODE", "CP-tilstand");
define("_VIPERROR", "VIP-opladning er påkrævet");
define("_PHASECONSEQUENCEERROR", "Fasestik-sekvens er påkrævet!");
define("_CPMODEERROR", "CP-tilstand er påkrævet!");
define("_SUPPORTEDCURRENT", "Understøttet strøm");
define("_INSTANTCURPERPHASE", "Øjeblikkelig strømfase");
define("_FIFOCHARGINGPERCENTAGE", "FIFO-opladningsprocent");
define("_MINIMUMCURRENT1P", "Minimum ladestrøm 1-faset");
define("_MINIMUMCURRENT3P", "Minimum ladestrøm 3-faset");
define("_MAXIMUMCURRENT", "Maksimal ladestrøm");
define("_STEP", "Trin");
define("_UPDATEDLMGROUP", "Opdater DLM-gruppe");
define("_MAINCIRCUITCURRENT", "Maksimal netstrøm");
define("_MAINCIRCUITCURRENTERROR", "Maksimal netstrøm er påkrævet!");
define("_DLMMAXCURRENT", "DLM samlet strømgrænse pr. fase");
define("_DLMMAXCURRENTERROR", "DLM samlet strømgrænse pr. fase er påkrævet!");
define("_DLMMAXCURRENTMORETHANMAIN", "DLM totalstrømgrænse bør være mere end halvdelen af hovedstrømafbryderstrømmen");
define("_DLMMAXCURRENTLESSTHANMAIN", "DLM totalstrømgrænse bør være mindre end hovedstrømafbryderstrømm");

define("_DHCPSERVER", "DHCP-server");
define("_DHCPCLIENT", "DHCP-klient");

define("_MAXDHCPADDRRANGE", "DHCP-server slut-IP-adresse");
define("_MINDHCPADDRRANGE", "DHCP-server start-IP-adresse");

define("_MAXDHCPADDRRANGEERROR", "DHCP-server slut-IP-adresse er påkrævet!");
define("_MINDHCPADDRRANGEERROR", "DHCP-server start-IP-adresse er påkrævet!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "DHCP-server slut-IP-adresse skal være større end DHCP-server-start-IP-adresse");
define("_IPADDRESSRANGE", "IP-adresse kan ikke have en værdi mellem DHCP-server-start- og slut-IP-adresser");
define("_INVALIDSUBNET", "Ip-adresse er ikke det rigtige subnet");

define("_CONNECTIONSTATUS", "Forbindelsesstatus");

define("_INSTALLATIONSETTINGS", "Installations indstillinger");
define("_EARTHINGSYSTEM", "Jordforbindelsessystem");
define("_CURRENTLIMITERSETTINGS", "Indstillinger for strømbegrænser");
define("_CURRENTLIMITERPHASE", "Fase for strømbegrænser");
define("_CURRENTLIMITERVALUE", "Værdi for strømbegrænser");
define("_UNBALANCEDLOADDETECTION", "Detektion af ubalanceret belastning");
define("_EXTERNALENABLEINPUT", "Ekstern aktivering af input");
define("_LOCKABLECABLE", "Låsbart kabel");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Energioptimering total strømbegrænser");
define("_POWEROPTIMIZER", "Power Optimizer");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "Enfaset");
define("_THREEPHASE", "Tre-faset");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Energioptimering total <br> strømbegrænser skal være <br> lig med eller større end 16");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Energioptimering total <br> strømbegrænser skal være <br> lig med eller mindre end 100");
define("_FOLLOWTHESUN", "Følg solen");
define("_FOLLOWTHESUNMODE", "Følg soltilstanden");
define("_AUTOPHASESWITCHING", "Automatisk faseskift");
define("_MAXHYBRID", "Max hybrid");
define("_SUNONLY", "Kun sol");
define("_SUNHYBRID", "Solhybrid");

define("_DISPLAYBACKLIGHTSETTINGS", "Vis indstillinger for baggrundsbelysning");
define("_BACKLIGHTLEVEL", "Niveau for baggrundslys");
define("_SUNRISETIME", "Solopgangstid ");
define("_SUNSETTIME", "Solnedgangstid");

define("_HIGH", "Høj");
define("_MID", "Medium");
define("_LOW", "Lav");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Når EVReadySupport tændt og Current Limiter Phase er én fase, må strømbegrænserværdien ikke være mindre end 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Når EVReadySupport tændt og Current Limiter Phase er trefaset, må strømbegrænserværdien ikke være mindre end 14!");
define("_LEDDIMMINGSETTINGS", "Led-dæmpningsindstillinger");
define("_LEDDIMMINGLEVEL", "Led dæmpning niveau");
define("_VERYLOW", "Meget Lav");

define("_CELLULARGATEWAYCONFIRM", "Cellular Gateway deaktiveres.");

define("_ETHERNETIP", "Ethernet-grænseflade IP:");
define("_WLANIP", "WLAN-grænseflade IP:");
define("_STRENGTH", "Styrke");
define("_WIFIFREQ", "Frekvens");
define("_WIFILEVEL", "Niveau");
define("_CELLULARIP", "Mobilgrænseflade IP:");
define("_CELLULAROPERCODE" , "Operatør");
define("_CELLULARTECH" , "Teknologi");
define("_APPLICATIONRESTART", "Denne ændring kræver genstart af programmet.");
define("_ACCEPTQUESTION", "Accepterer du ændringerne?");
define("_SCANNETWORKS", "Skan netværk");
define("_AVAILABLENETWORKS", "Tilgængelige netværk");
define("_NETWORKSTATUS", "Netværksstatus");
define("_PLEASEWAITMSG", "Vent venligst...");
define("_SCANNINGWIFIMSG", "Scanner Wi-Fi-netværk");
define("_NOWIFIFOUNDMSG", "Ingen Wi-Fi-netværk fundet");
define("_PLEASECHECKWIFICONNMSG", "Kontroller venligst din Wi-Fi-forbindelse og prøv igen.");

define("_QRCODE", "Vis QR -kode");
define("_QRCODEONSCREEN", "QR -kode på skærmen");
define("_QRCODEDELIMITER", "QR-kode afgrænser");
define("_INVALIDDELIMITERCHARACTER", "QR-kode afgrænsningstegn er ugyldigt, blanktegn er ikke acceptabelt, tegnlængden skal være minimum 1 og højst 3, gyldige tegn 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");

define("_LOCATION", "Beliggenhed");
define("_INDOOR", "Indendørs");
define("_OUTDOOR", "Udendørs");
define("_POWEROPTIMIZEREXTERNALMETER", "Ekstern Måler");
define("_OPERATIONMODE", "Driftstilstand");
define("_AUTOSELECTED", "Auto valgt");
define("_NOTSELECTED", "Ikke valgt");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "Valg Af Opladningstilstand Og Konfiguration Af Power Optimizer");

define("_USERINTERACTION", "Brugerinteraktion");
define("_STANDBYLEDBEHAVIOUR", "Standby LED -adfærd");
define("_OFF", "Af");
define("_ON", "På");

define("_LOADSHEDDINGMINIMUMCURRENT", "Minimumstrøm for belastningsreduktion");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Ubalanceret belastningsdetektering Maks. strøm");

define("_SCHEDULEDCHARGING", "Planlagt opladning");
define("_OFFPEAKCHARGING", "Off Peak opladning");
define("_OFFPEAKCHARGINGWEEKENDS", "Off peak opladning weekender");
define("_OFFPEAKCHARGINGPERIODS", "Opladningsperioder uden for spidsbelastning");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Fortsæt opladningen efter spidsintervallets slutning");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Fortsæt opladningen uden reautentificering efter strømtab");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Randomiseret forsinkelse maksimal <br>-varighed (sekunder)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Randomiseret forsinkelse Maksimal varighed er påkrævet!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Randomiseret forsinkelse maksimal varighed skal være heltal!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Randomiseret forsinkelse maksimal varighed skal være mellem 0 og 1800");
define("_OFFPEAKCHARGINGPERIODSERROR", "* Opladningsperioder uden for spidsbelastning er påkrævet!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Off Peak Charging Start- og Sluttidspunkt kan ikke være det samme!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Off-peak opladning Anden tidsperiode");
define("_OFFPEAKDISABLEDCONFIRM", "Off-Peak Charging vil blive deaktiveret. Bekræfter du det?");
define("_SHOWSERVICECONTACTINFO", "Vis Ekstra Service Kontakt Info");
define("_EXTRASERVICECONTACTINFORMATION", "Servicekontaktoplysninger vises på Connect Charging Cable, Klargøring til opladning, Initialisering og Venter på tilslutningsskærme");

define("_LOADSHEDDINGSTATUS", "Belastningstabsstatus: ");
define("_ACTIVE", "Aktiv");
define("_INACTIVE", "Inaktiv");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Hvis du vil bruge din Load Management Option i Modbus,<br>først skal du deaktivere Power Optimizer Total Current Limit<br>fra &#39Opladningstilstandsvalg og Power Optimizer Configuration&#39.");
define("_MODBUSALERT", "Hvis du vil aktivere din eksterne Power Optimizer-måler,<br>skal du først deaktivere Modbus<br>fra &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Hvis du vil bruge din Belastningsstyringsmulighed i Master/Slave,<br>skal du først deaktivere Kraftoptimereren<br>fra &#39Opladningstilstandsvælgelse og Kraftoptimerer konfiguration&#39.");
define("_DLMALERT", "Hvis du vil aktivere din Kraftoptimerer,<br>skal du først deaktivere Master/Slave<br>fra &#39Lokal Laststyring&#39.");

define("_DLMALERTFOLLOWTHESUN", "Hvis du vil aktivere Følg solen,<br>skal du først deaktivere Master/Slave<br>fra &#39Lokal Laststyring&#39.");
define("_FOLLOWTHESUNDLMENABLEALERT", "Hvis du vil bruge din Belastningsstyringsmulighed i Master/Slave,<br>skal du først deaktivere Følg solen<br>fra &#39Opladningstilstandsvælgelse og Kraftoptimerer konfiguration&#39.");

define("_RESETUSERPASSWORD", "Nulstil <br> brugeradgangskode");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Hvis du vil deaktivere Aktivering af installationsfejl,<br>skal du først indstille Earthing System fra &#39Installationsindstillinger&#39 til IT/Split Phase.");
define("_EARTHINGSYSTEMCONFIRM", "Hvis du vil indstille Earthing System til TN/TT,<br>skal du først aktivere Installationsfejl Aktiver fra &#39OCPP Settings&#39.");

define("_AUTHKEYMAXLIMIT", "længden må maksimalt være 40 tegn.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Authorization Key-feltet er tomt.<br>Bekræfter du ændringerne?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Randomiseret forsinkelse ved lavbelastningsslut");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Fejlsikker strøm");
define("_FAILSAFECURRENTERROR", "Fejlsikker strøm er påkrævet!");
define("_FAILSAFECURRENTLESSTHAN0", "* Fejlsikker Nuværende værdi må ikke være mindre end 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Fejlsikker Nuværende værdi må ikke være mere end 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Fejlsikker Nuværende værdi må ikke være mere end 50!");

define("_LOCALCHARGESESSION", "Lokale Opladningssessioner");
define("_ROWNUMBER", "Række nr");
define("_SESSIONUUID", "opladnings-id");
define("_AUTHORIZATIONUID", "RFID-kode");
define("_STARTTIME", "Starttidspunkt");
define("_STOPTIME", "Stoptidspunkt");
define("_TOTALTIME", "Samlet tid");
define("_STATUS", "Status");
define("_CHARGEPOINTIDS", "Stikkontaktnummer");
define("_INITIALENERGY", "Indledende energi(kWh)");
define("_LASTENERGY", "Sidste Energi(kWh)");
define("_TOTALENERGY", "Total Energi(kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Fuld sessionslog på CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Opsummeret log i CSV-format");
define("_STARTDATE", "start dato");
define("_ENDDATE", "slut dato");
define("_RFIDSELECTION", "RFID valg");
define("_CLEAR", "klar");

define("_FALLBACKCURRENT", "Tilbagegangsstrøm");
define("_FALLBACKRANGE", "Reservestrøm skal være 0 eller inden for området for ");
define("_DOWNLOADEEBUSLOGS", "EEBUS-logfiler");
define("_PAIRINGENERGYMANAGER", "Aktiveret til parring");
define("_PAIR", "Pair Enable");
define("_UNPAIR", "Fjern parring");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Firmwareversion");
define("_EEBUSDISCOVERY", "Opdagede enheder");
define("_REFRESH", "Opdater");
define("_CPROLEMASTERREQUIREDFIELD", "Hvis du vil opdatere indstillinger for belastningsstyringsgruppe, skal ladepunktsrollen gemmes som &#39Master&#39 fra generelle indstillinger for belastningsstyring.");

define("_LISTOFSLAVES", "Liste over slaver");
define("_NUMBEROFSLAVES", "Antal slaver");
define("_LISTOFCONNECTOR", "Liste over forbindelser");
define("_AVAILABLECURRENT", "Tilgængelig aktuel fase");

define("_DLMINTERFACE", "DLM Interface");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "Aktiver WiFi fra netværks grænseflader!");

define("_MUSTBEINTEGER", "skal være heltal!");

define("_GRIDBUFFER", "Grid Protection Margin Procent");
define("_CHARGINGSTATUSALERT", "I opladningsstatus kan værdien ikke opdateres!");
define("_READUNDERSTAND", "Jeg har læst, jeg forstår");

define("_MORETHAN10", "Du skal øge den maksimale netstrøm eller reducere Grid Protection Margin Procent før du gemmer disse indstillinger. Den maksimale Grid Current grænse kan ikke være lavere end 10A, når du bruger Grid Protection Margin Procent.");

define("_CLUSTERMAXCURRENT", "Cluster Max Current");
define("_CLUSTERFAILSAFECURRENT", "Cluster Failsafe Current");
define("_CLUSTERMAXCURRENTERROR", "Cluster Max Current er påkrævet!");
define("_CLUSTERFAILSAFECURRENTERROR", "Cluster Failsafe Current er påkrævet!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Cluster Failsafe Aktuel værdi må ikke være mindre end 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Cluster Failsafe Current værdi skal være mindre end den maksimale netstrøm!");
define("_CLUSTERFAILSAFE", "Cluster Failsafe Mode");

define("_CLUSTERMAXCURRENTLESSTHAN10", "Cluster Max Current værdi må ikke være mindre end 10");
define("_CLUSTERMAXCURRENTMORETHAN", "Cluster Max Current værdi skal være lig med eller mindre end denne værdi:");