<?php
include_once "access_control.php";
define("_LOGIN", "LOGGA IN");
define("_USERNAME", "Användarnamn:");
define("_PASSWORD", "Lösenord:");
define("_CHANGEPASSWORD", "Byta Lösenord");
define("_CURRENTPASSWORD", "Nuvarande Lösenord:");
define("_NEWPASSWORD", "Nytt Lösenord:");
define("_CONFIRMNEWPASSWORD", "Bekräfta nytt lösenord::");
define("_SUBMIT", "Skicka");
define("_CURRENTPASSWORDREQUIRED", "Nuvarande lösenord krävs");
define("_PASSWORDREQUIRED", "Lösenord krävs");
define("_USERNAMEREQUIRED", "Användarnamn krävs");
define("_USERAUTHFAILED", "Användarautentisering misslyckades!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Användarnamn eller nuvarande lösenord är fel!");
define("_DBACCESSFAILURE", "Det går inte att komma åt databasen!");
define("_CHANGEPASSWORDERROR", "Du måste först ändra ditt lösenord!");
define("_SAMEPASSWORDERROR", "Det nuvarande och det nya lösenordet ska vara olika från varandra!");
define("_PASSWORDMATCHERROR", "Lösenorden stämmer inte överens!");
define("_CURRENTPASSWORDWRONG", "Nuvarande lösenord är fel!");
define("_PASSWORDERRORLEVEL2", "Lösenordet är ogiltigt, teckenlängden måste vara 20 och innehålla minst två bokstäver [A-Za-z], två siffror [0-9] och två specialtecken [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Geslo je neveljavno, dolgo mora biti vsaj 12, največ 32 znakov in vsebovati vsaj dve mali [a-z] in dve veliki črki [A-Z], dve številki [0-9] in vsaj dva posebna znaka [!%&/()=?*#+-_].");
define("_LOGINLOCKOUT", "För många misslyckade försök. Försök efter 1800 sekunder.");

define("_MAINPAGE", "Huvudsida");
define("_GENERAL", "Allmänna Inställningar");
define("_OCPPSETTINGS", "OCPP-inställningar");
define("_NETWORKINTERFACES", "Nätverks gränssnitt");

define("_OCPPCONNINTERFACE", "OCPP-anslutningsgränssnitt : ");
define("_CONNECTIONSTATE", "Anslutningsstatus : ");
define("_DISCONNECTED", "Frånkopplad");
define("_NEEDTOLOGINFIRST", "Du måste logga in först!");
define("_CONNECTED", "Ansluten");
define("_CPSERIALNUMBER", "CP-serienummer : ");
define("_HMISOFTWAREVERSION", "HMI-programvaruversion : ");
define("_OCPPSOFTWAREVERSION", "OCPP-programvaruversion : ");
define("_POWERBOARDSOFTWAREVERSION", "Power Board - Programversion : ");
define("_OCPPDEVICEID", "OCPP-Enhets-ID: : ");
define("_DURATIONAFTERPOWERON", "Varaktighet efter att strömmen slås på : ");
define("_LOGOUT", "Logga ut");
define("_PRESET", "Förinställningar:");

define("_OCPPCONNECTION", "OCPP-anslutning");
define("_ENABLED", "Aktiverat");
define("_DISABLED", "Avaktiverat");
define("_CONNECTIONSETTINGS", "Anslutningsinställningar");
define("_CENTRALSYSTEMADDRESS", "Centralsystemets Adress ");
define("_CHARGEPOINTID", "ID för Laddningspunkt ");
define("_OCPPVERSION", "OCPP-Version");
define("_SAVE", "Spara");
define("_SAVESUCCESSFUL", "Framgångsrikt sparat.");
define("_CENTRALSYSTEMADDRESSERROR", "Centralsystemets adress krävs!");
define("_CHARGEPOINTIDERROR", "ID för laddningspunkt krävs!");
define("_SECONDS", "Sekunder");
define("_ADD", "Lägg till");
define("_REMOVE", "Ta bort");
define("_SAVECAPITAL", "SPARA");
define("_CANCEL", "Abvryt");

define("_CELLULAR", "Cellulär");
define("_INTERFACEIPADDRESS", "Gränssnittets IP-adress: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "APN-Namn: ");
define("_APNUSERNAME", "APN-Användarnamn: ");
define("_APNPASSWORD", "APN-Lösenord : ");
define("_IPSETTING", "IP-Inställning: ");
define("_IPADDRESS", "IP-Adress: ");
define("_NETWORKMASK", "Nätverksmask: ");
define("_DEFAULTGATEWAY", "Standardgateway: ");
define("_PRIMARYDNS", "Primär DNS: ");
define("_SECONDARYDNS", "Sekundär DNS: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Säkerhet: ");
define("_SECURITYTYPE", "Välj säkerhetstyp");
define("_NONE", "Ingen");
define("_SELECTMODE", "Vänligen välj läge!");
define("_RFIDLOCALLIST", "RFID-Lokallista");
define("_ACCEPTALLRFIDS", "Acceptera Alla RFID");
define("_MANAGERFIDLOCALLIST", "Hantera RFID-Lokallista:");
define("_AUTOSTART", "Autostart");
define("_PROCESSING", "Bearbetning... Var god vänta...");
define("_MACADDRESS", "MAC-Adress: ");
define("_WIFIHOTSPOT", "Wi-Fi-hotspot");
define("_TURNONDURINGBOOT", "Slå på under start: ");
define("_AUTOTURNOFFTIMEOUT", "Automatisk avstängning av timeout: ");
define("_AUTOTURNOFF", "Automatisk avstängning: ");
define("_HOTSPOTALERTMESSAGE", "Ändringar av hotspot-inställningar träder i kraft nästa gång enheten slås på. ");
define("_HOTSPOTREBOOTMESSAGE", "Vill du starta om nu? ");

define("_DOWNLOADACLOGS", "Ladda ner AC-Loggar");
define("_DOWNLOADCELLULARLOGS", "Ladda ner Cellulärmodul-loggar");
define("_DOWNLOADPOWERBOARDLOGS", "Ladda ner Power Board-loggar");
define("_PASSWORDRESETSUCCESSFUL", "Ditt lösenord har återställts framgångsrikt.");
define("_DBOPENEDSUCCESSFULLY", "Öppnade databasen framgångsrikt\n");
define("_WSSCERTSSETTINGS", "Inställningar för WSS-Certifikat ");
define("_CONFKEYS", "Konfigurationstangenter");
define("_KEY", "Tangent");
define("_STATIC", "Statisk");
define("_TIMEZONE", "Tidszon");
define("_PLEASESELECTTIMEZONE", "Vänligen Välj Tidszon");
define("_DISPLAYSETTINGS", "Visningsinställningar");
define("_DISPLAYLANGUAGE", "Visningsspråk");
define("_BACKLIGHTDIMMING", "Dimmning av Bakgrundsbelysning : ");
define("_PLEASESELECT", "Vänligen välj");
define("_TIMEBASED", "Tidsbaserad");
define("_SENSORBASED", "Sensorbaserad");
define("_BACKLIGHTDIMMINGLEVEL", "Dimmningsnivå för Bakgrundsbelysning : ");
define("_BACKLIGHTTHRESHOLD", "Tröskelvärde för Bakgrundsbelysning : ");
define("_SETMIDTHRESHOLD", "SetMid Tröskelvärde");
define("_SETHIGHTHRESHOLD", "SetHigh Tröskelvärde");
define("_LOCALLOADMANAGEMENT", "Lokal Load Management");
define("_MINIMUMCURRENT", "Lägsta strömflöde: ");
define("_FIFOPERCENTAGE", "FIFO-Procent: ");
define("_GRIDMAXCURRENT", "Nätets Maximala strömflöde: ");
define("_MASTERIPADDRESS", "IP-adress för Master: ");
define("_BACKLIGHTTIMESETTINGS", "Tidsinställningar för Bakgrundsbelysning: ");
define("_SHOULDSELECTTIMEZONE", "* Du måste välja tidszon!");
define("_MINIMUMCURRENTREQUIRED", "* Minimalt strömflöde krävs!");
define("_CURRENTMUSTBENUMERIC", "* Strömflödet måste vara numeriskt!");
define("_FIFOPERCREQUIRED", "* FIFO-procentsats krävs!");
define("_FIFOPERCSHOULDBETWEEN", "* FIFO-procentsatsen måste ligga mellan 0 och 100!");
define("_PERCMUSTBENUMERIC", "* Procentsatsen måste vara numerisk!");
define("_GRIDMAXCURRENTREQUIRED", "* Maximalt strömflöde för nätet krävs!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Strömflödet för nätet måste vara numeriskt!");
define("_IPADDRESSOFMASTERREQUIRED", "* IP-adress för master krävs!");
define("_INVALIDIPADDRESS", "* Du har angett en ogiltig IP-adress!");
define("_SAMENETWORKLAN", "* Du har angett en IP-adress i samma nätverk med LAN!");
define("_SAMENETWORKWLAN", "* Du har angett en IP-adress i samma nätverk med WLAN!");
define("_APNISREQUIRED", "APN krävs!");
define("_IPADDRESSREQUIRED", "IP-adress krävs!");
define("_NETWORKMASKREQUIRED", "Nätverksmask krävs!");
define("_INVALIDNETWORKMASK", "* Du har angett en ogiltig nätverksmask!");
define("_DEFAULTGATEWAYREQUIRED", "Standardgateway krävs!");
define("_INVALIDGATEWAY", "Du har angett en ogiltig standardgateway!");
define("_PRIMARYDNSREQUIRED", "Primär dns krävs!");
define("_INVALIDDNS", "Du har angett en ogiltig dns!");
define("_SELECTIPSETTING", "Vänligen välj IP-inställning.");
define("_SSIDREQUIRED", "SSID krävs!");
define("_PASSWORDISREQUIRED", "Lösenord krävs!");
define("_WIFIPASSWORDERROR", "Geslo je neveljavno, dolžina znakov mora biti najmanj 8 in največ 63 <br> veljavnih znakov  a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Geslo je neveljavno, dolžina znakov mora biti 20,<br>&#8226; Lösenordet måste innehålla minst två bokstäver [A-Za-z],<br>&#8226; Lösenordet måste innehålla minst två siffror [0-9],<br>&#8226; Lösenordet måste innehålla minst två specialtecken [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Lösenordet är ogiltigt, teckenlängden måste vara minst 12, högst 32,<br>&#8226; Lösenordet måste innehålla minst två gemener [a-z], <br>&#8226; Lösenordet måste innehålla minst två versaler [A-Z], <br>&#8226; Lösenordet måste innehålla minst två siffror [0-9],<br>&#8226; Lösenordet måste innehålla minst två specialtecken [!%&/()=?*#+-_]");
define("_WIFISSIDERROR", "SSID är ogiltigt, giltiga tecken a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Vänligen välj säkerhetstyp");
define("_HOSTIPREQUIRED", "* Värd-IP krävs!");
define("_CERTMANREQUIRED", "* Certifieringshantering krävs!");
define("_OCPPENABLEALERT", "Om du vill använda din laddningsstation i Fristående Läge måste du först inaktivera OCPP-anslutningen från &#39OCPP:s Inställningsmeny&#39.");
define("_NOTSAVEDALERT", "Sidan blev inte sparad.");
define("_SAVEQUESTION", "Vill du spara valda inställningar");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Simkort Gateway avaktiveras. Bekräfta");
define("_WIFICONNECTIONCONFIRM", "Wi-Fi anslutningen kommer att avaktiveras. Bekräftar du?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Om du vill aktivera LAN DHCP-server<br>måste du först inaktivera Wi-Fi Hotspot<br>från &#39Wi-Fi Hotspot&#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Om du vill aktivera Wi-Fi Hotspot<br>måste du först inaktivera LAN DHCP-server<br>från &#39LAN IP Setting&#39.");

define("_DYNAMIC", "Dynamisk");
define("_DIAGNOSTICS", "Diagnostik");
define("_LOCALLOAD", "Lokal Load Management");
define("_DOWNLOAD", "Ladda ner");
define("_STARTDATE", "Startdatum");
define("_ENDDATE", "Slutdatum");
define("_CLEAREVENTLOGS", "Rensa alla händelselogg");
define("_CLEAREVENTLOGSINFO", "Detta kommer att rensa alla händelselogg!");
define("_DOWNLOADEVENTLOGSINFO", "Ladda ner enhetens händelselogg för högst 5 dagar");
define("_DEVICEEVENTLOGS", "Enhetens händelselogg");
define("_DEVICECHANGELOGS", "Enhetens ändringslogg");
define("_LOGSDATEERROR", "Vänligen välj datum för högst 5 dagar.");
define("_DOWNLOACHANGELOGS", "Ladda ner enhetens ändringslogg");
define("_VPNFUNCTIONALITY", "VPN-Funktion: ");
define("_CERTMANAGEMENT", "Sertifieringshantering: ");
define("_NAME", "Namn: ");
define("_CONNECTIONINTERFACE", "Anslutningsgränssnitt ");
define("_ANY", "Vilken som helst");
define("_OCPPCONNPARAMETERS", "OCPP-Konfigurationsparametrar");
define("_SETDEFAULT", "Ställ in Standardinställningar ");
define("_STANDALONEMODE", "Fristående Läge");
define("_STANDALONEMODETITLE", "Fristående Läge:");
define("_STANDALONEMODENOTSELECTED", "* Fristående läge kan inte väljas eftersom OCPP är aktiverat.");
define("_CHARGERWEBUI", "Laddare för Webbläsargränssnitt");
define("_SYSTEMMAINTENANCE", "Systemunderhåll");
define("_HOSTIP", "Värd-IP: ");
define("_PASSWORDERRORLEVEL1", "Lösenordet är ogiltigt, teckenlängden måste vara minst 6 tecken och innehålla minst 1 liten bokstav, 1 stor bokstav och 1 siffertecken!");
define("_SELECTBACKLIGHTDIMMING", "* Du måste välja dimmning för bakgrundsbelysning!");
define("_ISREQUIRED", "är ett krav!");
define("_ISNOTVALID", "är inte giltigt!");
define("_ISDUPLICATED", "är duplicerad!");
define("_MUSTBENUMERIC", "måste vara numerisk!");
define("_VPNFUNCTIONALITYREQUIRED", "* Vpn-funktion krävs!");
define("_VPNNAMEREQUIRED", "* Vpn-namn krävs!");
define("_VPNPASSWORDREQUIRED", "* Vpn-lösenord krävs!");
define("_EXPLANATION", "Anger att fältet är obligatoriskt.");
define("_FIRMWAREUPDATE", "Firmware-uppdatering");
define("_BACKUPRESTORE", "Konfiguration av Säkerhetskopiering och Återställning");
define("_SYSTEMRESET", "Systemåterställning");
define("_CHANGEADMINPASSWORD", "Administrationslösenord");
define("_FACTORYRESET", "Standard fabriksinställning");
define("_FACTORYRESETBUTTON", "Standard fabriksåterställning");
define("_FACTORYDEFAULTCONFIGURATION", "Konfiguration av standard fabriksinställning");
define("_LOGFILES", "Loggfiler");
define("_BACKUPFILE", "Säkerhetskopieringsfil");
define("_RESTOREFILE", "Återställ konfigurationsfil");
define("_FREEMODEMAXCHARACTER", "måste vara maximalt 32 tecken!");
define("_RESTOREMESSAGE", "Bekräftar du att tillämpa ändringar och starta om nu?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "Lösenordet måste bestå av 6 tecken och innehålla minst en stor
bokstav,en liten bokstav och en siffra..");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Vaše geslo mora vsebovati 20 znakov in mora vsebovati vsaj dve črki,
dve števki in dva posebna znaka.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Ditt lösenord måste vara minst 12, högst 32 tecken och det måste innehålla
minst två versaler, två gemener, två siffror och två specialtecken.");

define("_BACKTOLOGIN", "Tillbaka till inloggning");
define("_CHANGE", "Change");
define("_SYSTEMADMINISTRATION", "Systemadministration");
define("_UPDATE", "Uppdatera");
define("_CONFIRM", "Bekräfta");
define("_FACTORYDEFAULTCONFIRM", "Är du säker på att du vill återställa till fabriksinställningar?");
define("_FILENAME", "Filnamn");
define("_UPLOAD", "Uppladdning");
define("_SELECTFIRMWARE", "Välj uppdateringsfil av fast programvara från datorn");
define("_FIRMWAREFILESIZE", "Kontrollera storleken på den fasta programvarufilen.");
define("_FIRMWAREFILETYPE", "Kontrollera typen på den fasta programvarufilen.");

define("_LESSTHANOREQUAL4", "måste vara mellan 1 och 4");
define("_LESSTHANOREQUAL20", "skall vara mindre än eller lika med 20");
define("_LESSTHANOREQUAL65000", "skall vara mindre än eller lika med 65000");
define("_LESSTHANOREQUAL300", "skall vara mindre än eller lika med 300");
define("_LESSTHANOREQUAL86500", "skall vara mindre än eller lika med 86500");
define("_LESSTHANOREQUAL10000", "skall vara mindre än eller lika med 10000");
define("_LESSTHANOREQUAL22", "skall vara mindre än eller lika med 22");
define("_LESSTHANOREQUAL10", "skall vara mindre än eller lika med 10");
define("_LESSTHANOREQUAL600", "skall vara mindre än eller lika med 600");
define("_LESSTHANOREQUAL120", "skall vara mindre än eller lika med 120");
define("_HIGHTHANOREQUAL0", "måste vara högre än eller lika med 0");
define("_CHANGEPASSWORDSUGGESTION", "Vi rekommenderar att du ändrar ditt standardlösenord från menyn för systemunderhåll");

define("_FILESIZE", "Vänligen kontrollera filens storlek.");
define("_FILETYPE", "Vänligen kontrollera filens typ.");

define("_BACKUPVERSIONCHECK", "Filens version är inte lämplig för enheten.");
define("_HARDRESETCONFIRM", "Är du säker på att du ska utföra hård återställning?");
define("_SOFTRESETCONFIRM", "Är du säker på att du ska utföra mjukåterställning?");
define("_NEWSETUP", "Använd användarhandboken för den nya inställningen.");

define("_LOGOSETTINGS", "Inställningar för logotyp");
define("_USELOGO", "Välj logotypfil från dator");
define("_LOGOTYPE", "Välj en logotyp i png-format.");
define("_LOGODIMENSION", "Den högsta tillåtna logotypstorleken är 80x80, vänligen välj en logotyp med lämplig storlek.");

define("_SERVICECONTACTINFO", "Visa tjänstens kontaktuppgifter");
define("_SERVICECONTACTINFOCHARACTER", "Tjänstens kontaktuppgifter måste innehålla max 25 tecken!<br>Giltiga tecken a..z 0..9 .+@*");

define("_SCREENTHEME", "Visningstema");
define("_DARKBLUE", "Mörkblå");
define("_ORANGE", "orange");
define("_PLEASEENTERRFIDLOCALLIST", "Ange den lokala RFID-listan!");

define("_LOADMANAGEMENT", "Belastningshantering");
define("_CPROLE", "Charge Point Role");
define("_GRIDSETTINGS", "Nät Inställningar");
define("_LOADMANAGEMENTMODE", "Belastningshanterings Läge");
define("_LOADMANAGEMENTGROUP", "Belastningshanterings Grupp");
define("_LOADMANAGEMENTOPTION", "Možnost Upravljanja Obremenitve");
define("_ALARMS", "Larm");

define("_MASTER", "Master");
define("_SLAVE", "Slav");
define("_TOTALCURRENTLIMIT", "Total strömflödesbegränsning per fas");
define("_SUPPLYTYPE", "Leveranstyp");
define("_FIFOPERCANTAGE", "FIFO-Procent:");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Jämnt fördelad");
define("_COMBINED", "Kombinerad");
define("_TOTALCURRENTLIMITERROR", "Total strömflödesbegränsning per fas krävs!");
define("_LESSTHAN1024", "måste vara mindre än 1024");
define("_ATLEAST0","måste vara minst 0");
define("_MORETHAN12", "måste vara mer än 12");
define("_CHOOSEONE", "Välj en");
define("_SLAVEMINCHCURRENT", "Offline Felsäker laddningsströminställning");
define("_SERIALNO", "Serienummer");
define("_CONNECTORSTATE", "Anslutningstillstånd");
define("_NUMBEROFPHASES", "Antal faser");
define("_PHASECONSEQUENCE", "Fasanslutningssekvens");
define("_VIP", "VIP-laddning");
define("_CPMODE", "CP-läge");
define("_VIPERROR", "VIP-laddning krävs");
define("_PHASECONSEQUENCEERROR", "Fasanslutningssekvens krävs!");
define("_CPMODEERROR", "CP-läge krävs!");
define("_SUPPORTEDCURRENT", "Stödd ström");
define("_INSTANTCURPERPHASE", "Direktströms fas");
define("_FIFOCHARGINGPERCENTAGE", "Procentuell andel FIFO-laddning");
define("_MINIMUMCURRENT1P", "Lägsta laddningsström 1-fas");
define("_MINIMUMCURRENT3P", "Lägsta laddningsström 3-fas");
define("_MAXIMUMCURRENT", "Maximal laddningsström");
define("_STEP", "Steg");
define("_UPDATEDLMGROUP", "Uppdatera DLM Group");
define("_MAINCIRCUITCURRENT", "Maximal nätström");
define("_MAINCIRCUITCURRENTERROR", "Maximal nätström krävs!");
define("_DLMMAXCURRENT", "DLM total strömgräns per fas");
define("_DLMMAXCURRENTERROR", "DLM total strömgräns per fas krävs!");
define("_DLMMAXCURRENTMORETHANMAIN", "DLM totala strömgräns bör vara mer än hälften av huvudströmbrytarens ström");
define("_DLMMAXCURRENTLESSTHANMAIN", "DLM totala strömgräns bör vara mindre än huvudströmbrytarens ström");

define("_DHCPSERVER", "DHCP-server");
define("_DHCPCLIENT", "DHCPklient");

define("_MAXDHCPADDRRANGE", "DHCP-serverns slut IP-adress");
define("_MINDHCPADDRRANGE", "DHCP-serverns start IP-adress");

define("_MAXDHCPADDRRANGEERROR", "DHCP-serverns slut IP-adress krävs!");
define("_MINDHCPADDRRANGEERROR", "DHCP-serverns start IP-adress krävs!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "DHCP-serverns slut IP-adress måste vara större än DHCP-serverns start IP-adress");
define("_IPADDRESSRANGE", "IP-adressen kan inte ha ett värde mellan DHCP-server start och slut IP-adresser");
define("_INVALIDSUBNET", "IP-adressen är inte sann subnet");

define("_CONNECTIONSTATUS", "Anslutningsstatus");

define("_INSTALLATIONSETTINGS", "Installations Inställningar");
define("_EARTHINGSYSTEM", "Jordningssystem");
define("_CURRENTLIMITERSETTINGS", "Strömbegränsarens inställningar");
define("_CURRENTLIMITERPHASE", "Strömbegränsarens fas");
define("_CURRENTLIMITERVALUE", "Strömbegränsnings värde");
define("_UNBALANCEDLOADDETECTION", "Detektering av obalanserad laddning");
define("_EXTERNALENABLEINPUT", "Extern aktiveringsingång");
define("_LOCKABLECABLE", "Låsbar kabel");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Effektoptimerarens Totala Strömflödesbegränsning");
define("_POWEROPTIMIZER", "Effektoptimering");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "En fas");
define("_THREEPHASE", "Tre fas");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Effektoptimerarens <br> Strömflödesbegränsning <br> måste vara större än eller <br> lika med 16.");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Effektoptimerarens <br> totala Strömflödesbegränsning <br> måste vara större än eller <br> lika med 100.");
define("_FOLLOWTHESUN", "Följ solen");
define("_FOLLOWTHESUNMODE", "Följ solläget");
define("_AUTOPHASESWITCHING", "Automatisk fasväxling");
define("_MAXHYBRID", "Max hybrid");
define("_SUNONLY", "Endast sol");
define("_SUNHYBRID", "Solhybrid");

define("_DISPLAYBACKLIGHTSETTINGS", "Inställningar för bakgrundsbelysning på visningsskärmen");
define("_BACKLIGHTLEVEL", "Bakgrundsbelysningsnivå");
define("_SUNRISETIME", "Tid för soluppgång ");
define("_SUNSETTIME", "Tid för solnedgång");

define("_HIGH", "Hög");
define("_MID", "Mid");
define("_LOW", "Låg");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Ko je EVReadySupport vklopljen in je faza omejitve toka ena faza, vrednost omejitve toka ne sme biti manjša od 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Ko je EVReadySupport vklopljen in je faza omejitve toka trifazna, vrednost omejitve toka ne sme biti manjša od 14!");
define("_LEDDIMMINGSETTINGS", "Inställningar för LED-dimning");
define("_LEDDIMMINGLEVEL", "Nivå för LED-dimning");
define("_VERYLOW", "Väldigt låg");

define("_CELLULARGATEWAYCONFIRM", "Simkort Gateway avaktiveras. Bekräfta");

define("_ETHERNETIP", "IP vmesnika Ethernet:");
define("_WLANIP", "IP vmesnika WLAN:");
define("_STRENGTH", "Styrka");
define("_WIFIFREQ", "Frekvens");
define("_WIFILEVEL", "Nivå");
define("_CELLULARIP", "IP mobilnega vmesnika:");
define("_CELLULAROPERCODE" , "Operatör");
define("_CELLULARTECH" , "Teknologi");
define("_APPLICATIONRESTART", "Denna ändring kräver omstart");
define("_ACCEPTQUESTION", "Vill du spara valda inställningar");
define("_SCANNETWORKS" , "Skanna nätverk");
define("_AVAILABLENETWORKS" , "Tillgängliga nätverk");
define("_NETWORKSTATUS" , "Nätverksstatus");
define("_PLEASEWAITMSG" , "Vänligen vänta...");
define("_SCANNINGWIFIMSG" , "Skannar Wi-Fi nätverk");
define("_NOWIFIFOUNDMSG" , "Inga Wi-Fi nätverk hittades");
define("_PLEASECHECKWIFICONNMSG" , "Vänligen kontrollera din Wi-Fi-anslutning och försök igen.");

define("_QRCODE", "Visa QR kod");
define("_QRCODEONSCREEN", "QR kod visas i skärm");
define("_QRCODEDELIMITER", "QR kod avgränsare");
define("_INVALIDDELIMITERCHARACTER", "QR-kod avgränsare är ogiltigt, blanksteg är inte acceptabelt, teckenlängden måste vara minst 1, högst 3 tecken, ogiltiga tecken 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");

define("_LOCATION", "Lokacija");
define("_INDOOR", "Inomhus");
define("_OUTDOOR", "Na prostem");
define("_POWEROPTIMIZEREXTERNALMETER", "Extern Mätare");
define("_OPERATIONMODE", "Operation läge");
define("_AUTOSELECTED", "Samodejno izbrano");
define("_NOTSELECTED", "Ni izbrano");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "ladd läge val och effekt optimeringskonfiguration");

define("_USERINTERACTION", "Interakcija uporabnika");
define("_STANDBYLEDBEHAVIOUR", "Vedenje LED v stanju pripravljenosti");
define("_OFF", "Izklopljeno");
define("_ON", "Vklopljeno");

define("_LOADSHEDDINGMINIMUMCURRENT", "Minimalni tok zmanjšanja obremenitve");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Največji tok zaznavanja neuravnotežene obremenitve");

define("_SCHEDULEDCHARGING", "Načrtovano polnjenje");
define("_OFFPEAKCHARGING", "Polnjenje izven konice");
define("_OFFPEAKCHARGINGWEEKENDS", "Ob koncu tedna za polnjenje");
define("_OFFPEAKCHARGINGPERIODS", "Obdobja polnjenja izven konice");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Fortsätt ladda efter att toppintervallet har avslutats");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Fortsätt ladda utan reautentisering efter strömtapp");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Najdaljše trajanje naključne zamude <br> (sekunde)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Zahtevano je najdaljše trajanje naključne zamude!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Randomised Delay Maximum Duration must be integer!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Najdaljše trajanje naključne zamude mora biti celo število!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Čas začetka in konca polnjenja izven vrha ne moreta biti enaka!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Drugo časovno obdobje polnjenja izven obremenitve");
define("_OFFPEAKDISABLEDCONFIRM", "Off-Peak Charging kommer att inaktiveras. Bekräftar du?");
define("_SHOWSERVICECONTACTINFO", "Prikaži kontaktne informacije dodatne storitve");
define("_EXTRASERVICECONTACTINFORMATION", "Kontaktni podatki servisa so prikazani na zaslonih Priključite polnilni kabel, Priprava na polnjenje, Inicializacija in Čakanje na povezavo");

define("_LOADSHEDDINGSTATUS", "Stanje razbremenitve:");
define("_ACTIVE", "Aktiven");
define("_INACTIVE", "Neaktiven");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Če želite uporabiti svojo možnost upravljanja obremenitve v Modbusu,<br>morate najprej onemogočiti Omejitev skupnega toka Power Optimizer<br>v &#39Charging Mode Selection in Power Optimizer Configuration&#39.");
define("_MODBUSALERT", "Če želite omogočiti svoj zunanji merilnik Power Optimizer,<br>morate najprej deaktivirati Modbus<br>iz &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Om du vill använda din Lasthanteringsalternativ i Master/Slave,<br>måste du först inaktivera Kraftoptimeraren<br>från &#39Laddningslägeval och Kraftoptimerarkonfiguration&#39.");
define("_DLMALERT", "Om du vill aktivera din Kraftoptimerare<br>måste du först inaktivera Master/Slave<br>från &#39Lokal Laststyrning&#39.");

define("_FOLLOWTHESUNDLMENABLEALERT", "Om du vill använda din Lasthanteringsalternativ i Master/Slave,<br>måste du först inaktivera Följ solen<br>från &#39Laddningslägeval och Kraftoptimerarkonfiguration&#39.");
define("_DLMALERTFOLLOWTHESUN", "Om du vill aktivera din Följ solen<br>måste du först inaktivera Master/Slave<br>från &#39Lokal Laststyrning&#39.");

define("_RESETUSERPASSWORD", "Ponastavi <br> uporabniško geslo");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Om du vill inaktivera Installation Error Enable<br>måste du först ställa in Earthing System från &#39Installation Settings&#39 till IT/Split Phase.");
define("_EARTHINGSYSTEMCONFIRM", "Om du vill ställa in Earthing System till TN/TT,<br>måste du först aktivera Installation Error Enable från &#39OCPP Settings&#39.");

define("_AUTHKEYMAXLIMIT", "längden får vara högst 40 tecken.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Authorization Key-fältet är tomt.<br>Bekräftar du ändringarna?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Randomiserad fördröjning vid lågtrafik");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Felsäker ström");
define("_FAILSAFECURRENTERROR", "Felsäker ström krävs!");
define("_FAILSAFECURRENTLESSTHAN0", "* Failsafe Current vrednost ne sme biti manjša od 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Failsafe Current vrednost ne sme biti večja od 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Failsafe Current vrednost ne sme biti večja od 50!");

define("_LOCALCHARGESESSION", "Lokala avgiftssessioner");
define("_ROWNUMBER", "Rad No");
define("_SESSIONUUID", "laddnings-id");
define("_AUTHORIZATIONUID", "Auktoriseringskort-ID");
define("_STARTTIME", "Starttid");
define("_STOPTIME", "Stopptid");
define("_TOTALTIME", "Totaltid");
define("_STATUS", "Status");
define("_CHARGEPOINTIDS", "Uttagsnummer");
define("_INITIALENERGY", "Uppstarts Energi(kWh)");
define("_LASTENERGY", "Sista Energin(kWh)");
define("_TOTALENERGY", "Total energi(kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Full Session Logga in CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Sammanfattning Logga in CSV");
define("_STARTDATE", "start datum");
define("_ENDDATE", "slutdatum");
define("_RFIDSELECTION", "RFID val");
define("_CLEAR", "klar");

define("_FALLBACKCURRENT", "Nadomestni tok");
define("_FALLBACKRANGE", "Reservström måste vara 0 eller inom intervallet för ");
define("_DOWNLOADEEBUSLOGS", "EEBUS-loggar");
define("_PAIRINGENERGYMANAGER", "Aktiverad för parning");
define("_PAIR", "Paraktivera");
define("_UNPAIR", "Ta bort par");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Firmware-version");
define("_EEBUSDISCOVERY", "Upptäckta enheter");
define("_REFRESH", "Refresh");
define("_CPROLEMASTERREQUIREDFIELD", "Om du vill uppdatera inställningarna för belastningshanteringsgrupp måste laddningspunktsrollen sparas som &#39Master&#39 från allmänna inställningar för lasthantering.");

define("_LISTOFSLAVES", "Lista över slavar");
define("_NUMBEROFSLAVES", "Antal slavar");
define("_LISTOFCONNECTOR", "Lista över anslutningar");
define("_AVAILABLECURRENT", "Tillgänglig aktuell fas");

define("_DLMINTERFACE", "DLM-gränssnitt");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "Aktivera WiFi från nätverksgränssnitt!");

define("_MUSTBEINTEGER", "måste vara heltal!");
define("_GRIDBUFFER", "Grid Protection Margin Procent");
define("_CHARGINGSTATUSALERT", "I laddningsstatus kan värdet inte uppdateras!");
define("_READUNDERSTAND", "Jag har läst, jag förstår");

define("_MORETHAN10", "Du måste öka den maximala nätströmmen eller minska procentandelen Grid Protection Margin innan du sparar dessa inställningar. Den maximala Grid Current-gränsen får inte vara lägre än 10A när du använder Grid Protection Margin Procent.");

define("_CLUSTERMAXCURRENT", "Cluster Max Current");
define("_CLUSTERFAILSAFECURRENT", "Cluster Failsafe Current");
define("_CLUSTERMAXCURRENTERROR", "Cluster Max Current krävs!");
define("_CLUSTERFAILSAFECURRENTERROR", "Cluster Failsafe Current krävs!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Cluster Failsafe Aktuellt värde får inte vara mindre än 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Cluster Failsafe Current värde måste vara mindre än Maximal Grid Current!");
define("_CLUSTERFAILSAFE", "Cluster Failsafe Mode");

define("_CLUSTERMAXCURRENTLESSTHAN10", "Cluster Max Aktuellt värde får inte vara mindre än 10");
define("_CLUSTERMAXCURRENTMORETHAN", "Cluster Max Aktuellt värde måste vara lika med eller mindre än detta värde:");