<?php
include_once "access_control.php";
define("_LOGIN", "PŘIHLÁŠENÍ");
define("_USERNAME", "Uživatelské jméno:");
define("_PASSWORD", "Heslo:");
define("_CHANGEPASSWORD", "Změnit heslo");
define("_CURRENTPASSWORD", "Současné heslo:");
define("_NEWPASSWORD", "Nové heslo:");
define("_CONFIRMNEWPASSWORD", "Potvrďte nové heslo:");
define("_SUBMIT", "Odeslat");
define("_CURRENTPASSWORDREQUIRED", "Je třeba aktuální heslo");
define("_PASSWORDREQUIRED", "Heslo je povinné");
define("_USERNAMEREQUIRED", "Uživatelské jméno je povinné");
define("_USERAUTHFAILED", "Ověření uživatele selhalo!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Uživatelské jméno nebo aktuální heslo je špatné!");
define("_DBACCESSFAILURE", "Není možný přístup do databáze!");
define("_CHANGEPASSWORDERROR", "Nejprve musíte změnit své heslo!");
define("_SAMEPASSWORDERROR", "Aktuální a nové heslo by se musí navzájem lišit!");
define("_PASSWORDMATCHERROR", "Hesla se neshodují");
define("_CURRENTPASSWORDWRONG", "Aktuální heslo je nesprávné!");
define("_PASSWORDERRORLEVEL2", "Heslo je neplatné, délka znaků musí být 20 a obsahovat alespoň dvě písmena [A-Za-z], dvě číslice [0-9] a dva speciální znaky [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Heslo je neplatné, délka znaků musí být alespoň 12, maximálně 32 znaků a musí obsahovat alespoň dvě malá písmena [a-z] a dvě velká písmena [A-Z], dvě čísla [0-9] a alespoň dva speciální znaky [!%&/()=?*#+-_].");
define("_LOGINLOCKOUT", "Příliš mnoho neúspěšných pokusů. Zkuste to po 1800 sekundách.");

define("_MAINPAGE", "Hlavní stránka");
define("_GENERAL", "Obecné nastavení");
define("_OCPPSETTINGS", "Nastavení OCPP");
define("_NETWORKINTERFACES", "Síťové rozhraní");

define("_OCPPCONNINTERFACE", "OCPP rozhraní připojení : ");
define("_CONNECTIONSTATE", "Stav připojení : ");
define("_DISCONNECTED", "Odpojeno");
define("_NEEDTOLOGINFIRST", "Nejprve se musíte přihlásit!");
define("_CONNECTED", "Připojen");
define("_CPSERIALNUMBER", "Sériové číslo CP : ");
define("_HMISOFTWAREVERSION", "Verze HMI softwaru : ");
define("_OCPPSOFTWAREVERSION", "Verze OCPP softwaru : ");
define("_POWERBOARDSOFTWAREVERSION", "Verze softwaru napájecí desky : ");
define("_OCPPDEVICEID", "ID OCPP zařízení : ");
define("_DURATIONAFTERPOWERON", "Doba po zapnutí : ");
define("_LOGOUT", "Odhlásit se");
define("_PRESET", "Přednastavení:");

define("_OCPPCONNECTION", "OCPP připojení");
define("_ENABLED", "Zapnuto");
define("_DISABLED", "Vypnuto");
define("_CONNECTIONSETTINGS", "Nastavení připojení");
define("_CENTRALSYSTEMADDRESS", "Adresa centrálního systému ");
define("_CHARGEPOINTID", "ID nabíjecího bodu ");
define("_OCPPVERSION", "Verze OCPP");
define("_SAVE", "Uložit");
define("_SAVESUCCESSFUL", "Úspěšně uložené.");
define("_CENTRALSYSTEMADDRESSERROR", "Vyžaduje se adresa centrálního systému");
define("_CHARGEPOINTIDERROR", "Vyžaduje se ID nabíjecího bodu");
define("_SECONDS", "Sekundy");
define("_ADD", "Přidat");
define("_REMOVE", "Odstranit");
define("_SAVECAPITAL", "ULOŽIT");
define("_CANCEL", "Zrušit");

define("_CELLULAR", "Mobil");
define("_INTERFACEIPADDRESS", "IP adresa rozhraní: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "Název APN: ");
define("_APNUSERNAME", "Uživatelské jméno APN: ");
define("_APNPASSWORD", "Heslo APN: ");
define("_IPSETTING", "IP nastavení: ");
define("_IPADDRESS", "IP adresa: ");
define("_NETWORKMASK", "Maska sítě: ");
define("_DEFAULTGATEWAY", "Výchozí brána: ");
define("_PRIMARYDNS", "Primární DNS: ");
define("_SECONDARYDNS", "Sekundární DNS: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Bezpečnost: ");
define("_SECURITYTYPE", "Vyberte typ zabezpečení");
define("_NONE", "Žádné");
define("_SELECTMODE", "Vyberte Režim, prosím!");
define("_RFIDLOCALLIST", "Místní seznam RFID");
define("_ACCEPTALLRFIDS", "Přijmout všechny RFID");
define("_MANAGERFIDLOCALLIST", "Spravovat místní seznam RFID:");
define("_AUTOSTART", "Automatické spuštění");
define("_PROCESSING", "Zpracování... Čekejte, prosím...");
define("_MACADDRESS", "MAC adresa: ");
define("_WIFIHOTSPOT", "Wi-Fi hotspot");
define("_TURNONDURINGBOOT", "Zapněte během bootování: ");
define("_AUTOTURNOFFTIMEOUT", "Časový limit automatického vypnutí: ");
define("_AUTOTURNOFF", "Automatické vypnutí: ");
define("_HOTSPOTALERTMESSAGE", "Změny nastavení hotspotu se projeví při příštím zapnutí zařízení. ");
define("_HOTSPOTREBOOTMESSAGE", "Chcete nyní restartovat? ");

define("_DOWNLOADACLOGS", "Stáhnout AC protokoly");
define("_DOWNLOADCELLULARLOGS", "Stáhnout protokoly mobilních modulů");
define("_DOWNLOADPOWERBOARDLOGS", "Stáhnout deníky napájecí desky");
define("_PASSWORDRESETSUCCESSFUL", "Heslo bylo úspěšně obnoveno.");
define("_DBOPENEDSUCCESSFULLY", "Databáze byla úspěšně otevřena\n");
define("_WSSCERTSSETTINGS", "Nastavení WSS certifikátů ");
define("_CONFKEYS", "Konfigurační klávesy");
define("_KEY", "Tlačítko");
define("_STATIC", "Statický");
define("_TIMEZONE", "Časové pásmo");
define("_PLEASESELECTTIMEZONE", "Vyberte Časové pásmo, prosím");
define("_DISPLAYSETTINGS", "Nastavení displeje");
define("_DISPLAYLANGUAGE", "Jazyk displeje");
define("_BACKLIGHTDIMMING", "Tlumení zpětného světla : ");
define("_PLEASESELECT", "Vyberte");
define("_TIMEBASED", "Na základě času");
define("_SENSORBASED", "Na základě senzoru");
define("_BACKLIGHTDIMMINGLEVEL", "Úroveň tlumení zpětného světla : ");
define("_BACKLIGHTTHRESHOLD", "Prahová hodnota podsvícení : ");
define("_SETMIDTHRESHOLD", "Nastavit střední prahovou hodnotu");
define("_SETHIGHTHRESHOLD", "Nastavit vysokou prahovou hodnotu");
define("_LOCALLOADMANAGEMENT", "Řízení Místního zatížení");
define("_MINIMUMCURRENT", "Minimální proud: ");
define("_FIFOPERCENTAGE", "Procento FIFO: ");
define("_GRIDMAXCURRENT", "Maximální proud v síti: ");
define("_MASTERIPADDRESS", "IP adresa hlavního serveru: ");
define("_BACKLIGHTTIMESETTINGS", "Časové nastavení Podsvícení: ");
define("_SHOULDSELECTTIMEZONE", "* Musíte zvolit časové pásmo!");
define("_MINIMUMCURRENTREQUIRED", "* Vyžaduje se minimální proud!");
define("_CURRENTMUSTBENUMERIC", "* Proud musí být číselný!");
define("_FIFOPERCREQUIRED", "* Vyžaduje se procento FIFO!");
define("_FIFOPERCSHOULDBETWEEN", "* Procento FIFO musí být mezi 0 a 100!");
define("_PERCMUSTBENUMERIC", "* Procento musí být číselné!");
define("_GRIDMAXCURRENTREQUIRED", "* Vyžaduje se maximální proud v síti!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Proud v síti musí být číselný!");
define("_IPADDRESSOFMASTERREQUIRED", "* Vyžaduje se IP adresa hlavního serveru!");
define("_INVALIDIPADDRESS", "* Zadali jste neplatnou IP adresu!");
define("_SAMENETWORKLAN", "* Zadali jste IP adresu ve stejné síti jako LAN!!");
define("_SAMENETWORKWLAN", "* Zadali jste IP adresu ve stejné síti jako WLAN!");
define("_APNISREQUIRED", "Vyžaduje se APN!");
define("_IPADDRESSREQUIRED", "Vyžaduje se IP adresa!");
define("_NETWORKMASKREQUIRED", "Vyžaduje se maska sítě!");
define("_INVALIDNETWORKMASK", "* Zadali jste neplatnou Masku sítě!");
define("_DEFAULTGATEWAYREQUIRED", "Vyžaduje se Výchozí brána!");
define("_INVALIDGATEWAY", "Zadali jste neplatnou Výchozí bránu!");
define("_PRIMARYDNSREQUIRED", "Vyžaduje se primární dns!");
define("_INVALIDDNS", "Zadali jste neplatnou dns!");
define("_SELECTIPSETTING", "Zvolte IP nastavení, prosím.");
define("_SSIDREQUIRED", "Vyžaduje se SSID!");
define("_PASSWORDISREQUIRED", "Vyžaduje se heslo!");
define("_WIFIPASSWORDERROR", "Heslo je neplatné, délka znaků musí být minimálně 8 a maximálně 63 <br> platných znaků a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=* ?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Heslo je neplatné, délka znaků musí být 20,<br>&#8226; Heslo musí obsahovat alespoň dvě písmena [A-Za-z],<br>&#8226; Heslo musí obsahovat alespoň dvě číslice [0-9],<br>&#8226; Heslo musí obsahovat alespoň dva speciální znaky [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Heslo je neplatné, délka znaků musí být alespoň 12, maximálně 32,<br>&#8226; Heslo musí obsahovat alespoň dvě malá písmena [a-z], <br>&#8226; Heslo musí obsahovat alespoň dvě velká písmena [A-Z], <br>&#8226; Heslo musí obsahovat alespoň dvě číslice [0-9],<br>&#8226; Heslo musí obsahovat alespoň dva speciální znaky [!%&/()=?*#+-_]");
define("_WIFISSIDERROR", "SSID je neplatné, platné znaky a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Vyberte typ zabezpečení");
define("_HOSTIPREQUIRED", "* Vyžaduje se IP hostitele!");
define("_CERTMANREQUIRED", "* Vyžaduje se Správa certifikace!");
define("_OCPPENABLEALERT", "Chcete-li svou Nabíjecí stanici používat v samostatném režimu, musíte nejprve deaktivovat připojení OCPP v nabídce nastavení OCPP.");
define("_NOTSAVEDALERT", "Stránka nebyla uložena.");
define("_SAVEQUESTION", "Chcete uložit změny?");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Mobilní připojení bude zakázáno. Potvrzujete?");
define("_WIFICONNECTIONCONFIRM", "Wi-fi připojení bude zakázáno. Potvrzujete?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Chcete-li povolit server LAN DHCP,<br>musíte nejprve zakázat Wi-Fi hotspot z<br>Wi-Fi hotspotu.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Chcete-li povolit Wi-Fi hotspot,<br>musíte nejprve deaktivovat LAN DHCP Server z<br>LAN IP Setting.");

define("_DYNAMIC", "Dynamický");
define("_DIAGNOSTICS", "Diagnostika");
define("_LOCALLOAD", "Řízení Místního zatížení");
define("_DOWNLOAD", "Stáhnout");
define("_STARTDATE", "Datum začátku");
define("_ENDDATE", "Datum konce");
define("_CLEAREVENTLOGS", "Vymazat všechny záznamy událostí");
define("_CLEAREVENTLOGSINFO", "Tímto se vymažou všechny záznamy událostí!");
define("_DOWNLOADEVENTLOGSINFO", "Stáhnout záznamy událostí zařízení na maximálně 5 dní");
define("_DEVICEEVENTLOGS", "Záznamy událostí zařízení");
define("_DEVICECHANGELOGS", "Záznamy změn zařízení");
define("_LOGSDATEERROR", "Vyberte prosím data na maximálně 5 dní.");
define("_DOWNLOACHANGELOGS", "Stáhněte si protokoly změn");
define("_VPNFUNCTIONALITY", "Funkce VPN: ");
define("_CERTMANAGEMENT", "Řízení certifikace: ");
define("_NAME", "Název: ");
define("_CONNECTIONINTERFACE", "Rozhraní připojení ");
define("_ANY", "Jakékoliv");
define("_OCPPCONNPARAMETERS", "Konfigurační parametry OCPP");
define("_SETDEFAULT", "Nastavit jako výchozí ");
define("_STANDALONEMODE", "Samostatný režim");
define("_STANDALONEMODETITLE", "Samostatný režim:");
define("_STANDALONEMODENOTSELECTED", "* Samostatný režim nelze zvolit, protože je povolen OCPP.");
define("_CHARGERWEBUI", "Webové uživatelské rozhraní nabíječky");
define("_SYSTEMMAINTENANCE", "Údržba systému");
define("_HOSTIP", "IP hostitele: ");
define("_PASSWORDERRORLEVEL1", "Heslo je neplatné, délka znaku musí být minimálně 6 znaků a obsahovat minimálně 1 malé písmeno, 1 velké písmeno a 1 číselný znak!");
define("_SELECTBACKLIGHTDIMMING", "* Musíte zvolit ztlumení podsvícení!");
define("_ISREQUIRED", "je povinné!!");
define("_ISNOTVALID", "není platné!");
define("_ISDUPLICATED", "je duplicitní!");
define("_MUSTBENUMERIC", "musí být číselné!");
define("_VPNFUNCTIONALITYREQUIRED", "* Vyžaduje se funkce VPN!");
define("_VPNNAMEREQUIRED", "* Je třeba uvést název VPN!");
define("_VPNPASSWORDREQUIRED", "* Je třeba heslo VPN!");
define("_EXPLANATION", "Je třeba uvést heslo VPN.");
define("_FIRMWAREUPDATE", "Aktualizace firmwaru");
define("_BACKUPRESTORE", "Zálohování a obnovení konfigurace");
define("_SYSTEMRESET", "Reset systému");
define("_CHANGEADMINPASSWORD", "Heslo administrátora");
define("_FACTORYRESET", "Výchozí hodnoty od výrobce");
define("_FACTORYRESETBUTTON", "Reset na tovární nastavení");
define("_FACTORYDEFAULTCONFIGURATION", "Konfigurace na hodnoty od výrobce");
define("_LOGFILES", "Soubory protokolu");
define("_BACKUPFILE", "Záložní soubor");
define("_RESTOREFILE", "Obnovit konfigurační soubor");
define("_FREEMODEMAXCHARACTER", "musí mít maximálně 32 znaků!");
define("_RESTOREMESSAGE", "Potvrzujete, že chcete použít změny a restartovat nyní?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "Heslo musí mít alespoň 6 znaků a musí obsahovat alespoň jedno velképísmeno, jedno malé písmeno a jednu číslici..");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Vaše heslo musí mít 20 znaků a musí obsahovat alespoň dvě písmena,dvě číslice a dva speciální znaky.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Vaše heslo musí mít minimálně 12,maximálně 32 znaků a musí obsahovat minimálně dvě velká písmena, dvě malá písmena, dvě číslice a dva speciální znaky.");

define("_BACKTOLOGIN", "Zpět na Přihlášení");
define("_CHANGE", "Change");
define("_SYSTEMADMINISTRATION", "Zpráva systému");
define("_UPDATE", "Aktualizovat");
define("_CONFIRM", "Potvrdit");
define("_FACTORYDEFAULTCONFIRM", "Opravdu chcete obnovit tovární nastavení?");
define("_FILENAME", "Název souboru");
define("_UPLOAD", "Nahrání");
define("_SELECTFIRMWARE", "Vyberte soubor s aktualizací firmwaru z PC");
define("_FIRMWAREFILESIZE", "Zkontrolujte velikost souboru s firmwarem..");
define("_FIRMWAREFILETYPE", "Zkontrolujte typ souboru s firmwarem..");

define("_LESSTHANOREQUAL4", "musí být mezi 1 a 4");
define("_LESSTHANOREQUAL20", "musí být menší nebo roven 20");
define("_LESSTHANOREQUAL65000", "musí být menší nebo roven 65000");
define("_LESSTHANOREQUAL300", "musí být menší nebo roven 300");
define("_LESSTHANOREQUAL86500", "musí být menší nebo roven 86500");
define("_LESSTHANOREQUAL10000", "musí být menší nebo roven 10000");
define("_LESSTHANOREQUAL22", "musí být menší nebo roven 22");
define("_LESSTHANOREQUAL10", "musí být menší nebo roven 10");
define("_LESSTHANOREQUAL600", "musí být menší nebo roven 600");
define("_LESSTHANOREQUAL120", "musí být menší nebo roven 120");
define("_HIGHTHANOREQUAL0", "musí být vyšší nebo rovna 0");
define("_CHANGEPASSWORDSUGGESTION", "Doporučujeme vám změnit si výchozí heslo v nabídce údržby systému");

define("_FILESIZE", "Zkontrolujte velikost souboru.");
define("_FILETYPE", "Zkontrolujte typ souboru.");

define("_BACKUPVERSIONCHECK", "Verze tohoto souboru není pro zařízení vhodná.");
define("_HARDRESETCONFIRM", "Opravdu chcete uskutečnit Tvrdý reset?");
define("_SOFTRESETCONFIRM", "Opravdu chcete uskutečnit Jemný reset?");
define("_NEWSETUP", "Pro nové nastavení použijte příručku uživatele.");

define("_LOGOSETTINGS", "Nastavení loga");
define("_USELOGO", "Vyberte soubor s logem z počítače");
define("_LOGOTYPE", "Vyberte logo ve formátu png.");
define("_LOGODIMENSION", "Maximální povolená velikost loga je 80 x 80, zvolte logo s příslušnou velikostí.");

define("_SERVICECONTACTINFO", "Kontaktní informace pro Servis obrazovky");
define("_SERVICECONTACTINFOCHARACTER", "Kontaktní informace pro Servis obrazovky musí mít maximálně 25 znaků!<br>Platné znaky a..z 0..9 .+@*");

define("_SCREENTHEME", "Téma obrazovky");
define("_DARKBLUE", "Tmavomodrá");
define("_ORANGE", "Oranžová");
define("_PLEASEENTERRFIDLOCALLIST", "Zadejte místní seznam RFID!");

define("_LOADMANAGEMENT", "Správu zatížení");
define("_CPROLE", "Role nabíjecího bodu");
define("_GRIDSETTINGS", "Nastavení mřížky");
define("_LOADMANAGEMENTMODE", "Režim pro správu zatížení");
define("_LOADMANAGEMENTGROUP", "Skupina pro správu zatížení");
define("_LOADMANAGEMENTOPTION", "Možnost správy zatížení");
define("_ALARMS", "Alarmy");

define("_MASTER", "Master");
define("_SLAVE", "Slave");
define("_TOTALCURRENTLIMIT", "Celkový proudový limit na fázi");
define("_SUPPLYTYPE", "Typ napájení");
define("_FIFOPERCANTAGE", "Procento FIFO:");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Stejně sdílené");
define("_COMBINED", "Kombinované");
define("_TOTALCURRENTLIMITERROR", "Vyžaduje se celkový proudový limit na fázi!");
define("_LESSTHAN1024", "musí být méně než 1024");
define("_ATLEAST0","musí být alespoň 0");
define("_MORETHAN12", "musí být více než 12");
define("_CHOOSEONE", "Zvolte jedno");
define("_SLAVEMINCHCURRENT", "Offline Failsafe nabíjení aktuální nastavení");
define("_SERIALNO", "Sériové číslo");
define("_CONNECTORSTATE", "Stav konektoru");
define("_NUMBEROFPHASES", "Počet fází");
define("_PHASECONSEQUENCE", "Pořadí fázového připojení");
define("_VIP", "VIP nabíjení");
define("_CPMODE", "CP Mode");
define("_VIPERROR", "Vyžaduje se VIP nabíjení");
define("_PHASECONSEQUENCEERROR", "Vyžaduje se Pořadí fázového připojení!");
define("_CPMODEERROR", "Vyžaduje se Režim CP!");
define("_SUPPORTEDCURRENT", "Podporovaný proud");
define("_INSTANTCURPERPHASE", "Okamžitá proudová fáze");
define("_FIFOCHARGINGPERCENTAGE", "Procento nabíjení FIFO");
define("_MINIMUMCURRENT1P", "Minimální nabíjecí proud 1- fáze");
define("_MINIMUMCURRENT3P", "Minimální nabíjecí proud 3- fázy");
define("_MAXIMUMCURRENT", "Maximální nabíjecí proud");
define("_STEP", "Krok");
define("_UPDATEDLMGROUP", "Aktualizace skupiny DLM");
define("_MAINCIRCUITCURRENT", "Maximální proud sítě");
define("_MAINCIRCUITCURRENTERROR", "Je vyžadován maximální proud sítě!");
define("_DLMMAXCURRENT", "DLM Celkový proudový limit na fázi");
define("_DLMMAXCURRENTERROR", "Je vyžadován celkový proudový limit DLM na fázi!");
define("_DLMMAXCURRENTMORETHANMAIN", "Celkový proudový limit DLM by měl být více než polovina proudu hlavního jističe");
define("_DLMMAXCURRENTLESSTHANMAIN", "Celkový proudový limit DLM by měl být nižší než proud hlavního jističe");

define("_DHCPSERVER", "DHCP Server");
define("_DHCPCLIENT", "DHCP Zákazník");

define("_MAXDHCPADDRRANGE", "Koncová IP adresa serveru DHCP");
define("_MINDHCPADDRRANGE", "Počáteční IP adresa serveru DHCP");

define("_MAXDHCPADDRRANGEERROR", "Je požadována koncová IP adresa serveru DHCP!");
define("_MINDHCPADDRRANGEERROR", "Je požadována počáteční IP adresa serveru DHCP!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "Koncová IP adresa serveru DHCP by měla být větší než počáteční IP adresa serveru DHCP");
define("_IPADDRESSRANGE", "IP adresa nemůže mít hodnotu mezi počáteční a koncovou IP adresou serveru DHCP");
define("_INVALIDSUBNET", "IP adresa není ve skutečné podsíti");

define("_CONNECTIONSTATUS", "Stav připojení");

define("_INSTALLATIONSETTINGS", "Nastavení pro instalaci");
define("_EARTHINGSYSTEM", "Zemnící systém");
define("_CURRENTLIMITERSETTINGS", "Nastavení omezovače proudu");
define("_CURRENTLIMITERPHASE", "Fáze omezovače proudu");
define("_CURRENTLIMITERVALUE", "Hodnota omezovače proudu");
define("_UNBALANCEDLOADDETECTION", "Detekce nesymetrického zatížení");
define("_EXTERNALENABLEINPUT", "Externí povolený vstup");
define("_LOCKABLECABLE", "Uzamykatelný kabel");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Celkový proudový limit optimalizátoru výkonu");
define("_POWEROPTIMIZER", "Optimalizátor napájení");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "Jedna fáze");
define("_THREEPHASE", "Tři fáze");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Celkový proudový limit <br>  optimalizátoru výkonu musí <br> být vyšší  nebo roven 16");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Celkový proudový limit <br> optimalizátoru výkonu musí <br> být menší <br> nebo roven 100");
define("_FOLLOWTHESUN", "Následuj slunce");
define("_FOLLOWTHESUNMODE", "Postupujte podle režimu Slunce");
define("_AUTOPHASESWITCHING", "Automatické přepínání fází");
define("_MAXHYBRID", "Max hybrid");
define("_SUNONLY", "Pouze slunce");
define("_SUNHYBRID", "Sluneční hybrid");

define("_DISPLAYBACKLIGHTSETTINGS", "Nastavení podsvícení obrazovky");
define("_BACKLIGHTLEVEL", "Úroveň podsvícení");
define("_SUNRISETIME", "Čas východu slunce ");
define("_SUNSETTIME", "Čas západu slunce");

define("_HIGH", "Vysoká");
define("_MID", "Střední");
define("_LOW", "Nízká");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Když je ZEReadySupport zapnutá a fáze omezovače proudu je jedna fáze, hodnota omezovače proudu nesmí být menší než 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Když je ZEReadySupport zapnutá a fáze omezovače proudu je třífázová, hodnota omezovače proudu nesmí být menší než 14!");
define("_LEDDIMMINGSETTINGS", "Nastavení stmívání Led");
define("_LEDDIMMINGLEVEL", "Úroveň stmívání Led");
define("_VERYLOW", "Velmi Nízký");

define("_CELLULARGATEWAYCONFIRM", "Mobilní brána bude deaktivována.");

define("_ETHERNETIP", "IP rozhraní Ethernet:");
define("_WLANIP", "IP rozhraní WLAN:");
define("_STRENGTH", "Síla");
define("_WIFIFREQ", "Frekvence");
define("_WIFILEVEL", "Úroveň");
define("_CELLULARIP", "IP mobilního rozhraní:");
define("_CELLULAROPERCODE" , "Operátor");
define("_CELLULARTECH" , "Technika");
define("_APPLICATIONRESTART", "Tato změna vyžaduje restart aplikace.");
define("_ACCEPTQUESTION", "Přijímáte změny?");
define("_SCANNETWORKS", "Skenovat sítě");
define("_AVAILABLENETWORKS", "Dostupné sítě");
define("_NETWORKSTATUS", "Stav sítě");
define("_PLEASEWAITMSG", "Prosím, čekejte...");
define("_SCANNINGWIFIMSG", "Skenování Wi-Fi sítí");
define("_NOWIFIFOUNDMSG", "Nebyla nalezena žádná Wi-Fi síť");
define("_PLEASECHECKWIFICONNMSG", "Zkontrolujte své Wi-Fi připojení a zkuste to znovu.");

define("_QRCODE", "Zobrazit QR Kód");
define("_QRCODEONSCREEN", "QR Kód na Obrazovce");
define("_QRCODEDELIMITER", "Oddělovač QR kódu");
define("_INVALIDDELIMITERCHARACTER", "Znak oddělovače QR kódu je neplatný, bílý znak není přijatelný, délka znaku musí být minimálně 1 a maximálně 3, platné znaky 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");

define("_LOCATION", "Umístění");
define("_INDOOR", "Krytý");
define("_OUTDOOR", "Venkovní");
define("_POWEROPTIMIZEREXTERNALMETER", "Externí měřič");
define("_OPERATIONMODE", "Operační Mód");
define("_AUTOSELECTED", "Automaticky vybráno");
define("_NOTSELECTED", "Nevybraný");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "Výběr Režimu Nabíjení a Konfigurace Optimalizátoru Výkonu");

define("_USERINTERACTION", "Interakce uživatele");
define("_STANDBYLEDBEHAVIOUR", "Pohotovostní chování LED");
define("_OFF", "Vypnuto");
define("_ON", "Na");

define("_LOADSHEDDINGMINIMUMCURRENT", "Minimální proud pro odlehčení zátěže");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Maximální proud detekce nevyváženého zatížení");

define("_SCHEDULEDCHARGING", "Plánované nabíjení");
define("_OFFPEAKCHARGING", "Nabíjení mimo špičku");
define("_OFFPEAKCHARGINGWEEKENDS", "Nabíjecí víkendy mimo špičku");
define("_OFFPEAKCHARGINGPERIODS", "Období nabíjení mimo špičku");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Pokračujte v nabíjení po skončení špičkového intervalu");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Pokračujte v nabíjení bez opětovného ověření po výpadku napájení");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Randomizované zpoždění Maximální <br> trvání (v sekundách)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Randomised Delay Maximum Duration is required!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Randomizované zpoždění Je vyžadováno maximální trvání!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Randomizované zpoždění Maximální trvání by mělo být mezi 0 a 1800");
define("_OFFPEAKCHARGINGPERIODSERROR", "* Jsou vyžadovány doby nabíjení mimo špičku!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Čas začátku a konce nabíjení mimo špičku nemůže být stejný!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Druhé období nabíjení mimo špičku");
define("_OFFPEAKDISABLEDCONFIRM", "Nabíjení mimo špičku bude zakázáno. Potvrzujete?");

define("_SHOWSERVICECONTACTINFO", "Zobrazit další kontaktní informace služby");
define("_EXTRASERVICECONTACTINFORMATION", "Servisní kontaktní informace jsou zobrazeny na obrazovkách Připojení nabíjecího kabelu, Příprava na nabíjení, Inicializace a Čekání na připojení");

define("_LOADSHEDDINGSTATUS", "Stav uvolnění zátěže: ");
define("_ACTIVE", "Aktivní");
define("_INACTIVE", "Neaktivní");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Chcete-li v Modbusu používat možnost správy zátěže,<br>nejprve musíte deaktivovat celkový proudový limit Power Optimizer<br>v &#39Výběr režimu nabíjení a Konfigurace Power Optimizer&#39.");
define("_MODBUSALERT", "Pokud chcete povolit externí měřič Power Optimizer,<br>nejprve musíte deaktivovat Modbus<br>z &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Pokud chcete použít možnost řízení zátěže v režimu Master/Slave,<br>nejprve musíte deaktivovat Optimizér<br>výkonu z &#39Výběr režimu nabíjení a konfigurace Optimizéru výkonu&#39.");
define("_DLMALERT", "Pokud chcete aktivovat svůj Optimalizátor výkonu,<br>musíte nejprve deaktivovat Master/Slave<br>v &#39Místním řízení zátěže&#39.");

define("_DLMALERTFOLLOWTHESUN", "Pokud chcete aktivovat Následuj slunce,<br>musíte nejprve deaktivovat Master/Slave<br>v &#39Místním řízení zátěže&#39.");
define("_FOLLOWTHESUNDLMENABLEALERT", "Pokud chcete použít možnost řízení zátěže v režimu Master/Slave,<br>nejprve musíte deaktivovat Následuj slunce<br> z &#39Výběr režimu nabíjení a konfigurace Optimizéru výkonu&#39.");

define("_RESETUSERPASSWORD", "Obnovit <br> uživatelské heslo");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Chcete-li zakázat možnost Chyba instalace Povolit,<br>nejprve musíte nastavit systém uzemnění z &#39Nastavení instalace&#39 na IT/Split Phase..");
define("_EARTHINGSYSTEMCONFIRM", "Pokud chcete nastavit systém uzemnění na TN/TT,<br>nejprve musíte v &#39OCPP Settings&#39 povolit volbu Installation Error Enable.");

define("_AUTHKEYMAXLIMIT", "délka by měla být maximálně 40 znaků.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Pole Authorization Key je prázdné.<br>Potvrzujete změny?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Náhodné zpoždění na konci špičky");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Bezpečný proud");
define("_FAILSAFECURRENTERROR", "Je vyžadován bezpečný proud!");
define("_FAILSAFECURRENTLESSTHAN0", "* Hodnota Failsafe Current nesmí být menší než 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Failsafe Aktuální hodnota nesmí být větší než 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Failsafe Aktuální hodnota nesmí být větší než 50!");

define("_LOCALCHARGESESSION", "Místní Nabíjecí Sezení");
define("_ROWNUMBER", "Řádek č.");
define("_SESSIONUUID", "ID poplatku");
define("_AUTHORIZATIONUID", "RFID kód");
define("_STARTTIME", "Čas Začátku");
define("_STOPTIME", "Čas Konce");
define("_TOTALTIME", "Celkový čas");
define("_STATUS", "Stav");
define("_CHARGEPOINTIDS", "Číslo zásuvky");
define("_INITIALENERGY", "Počáteční Energie(kWh)");
define("_LASTENERGY", "Poslední Energie(kWh)");
define("_TOTALENERGY", "Celková energie (kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Úplný protokol relace v CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Souhrnné přihlášení do CSV");
define("_STARTDATE", "Datum zahájení");
define("_ENDDATE", "datum ukončení");
define("_RFIDSELECTION", "RFID výběr");
define("_CLEAR", "Průhledná");

define("_FALLBACKCURRENT", "Záložní proud");
define("_FALLBACKRANGE", "Záložní proud musí být 0 nebo v rozmezí ");
define("_DOWNLOADEEBUSLOGS", "EEBUS Logs");
define("_PAIRINGENERGYMANAGER", "Povoleno pro párování");
define("_PAIR", "Pair Enable");
define("_UNPAIR", "Unpair");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Verze firmwaru");
define("_EEBUSDISCOVERY", "Objevená zařízení");
define("_REFRESH", "Refresh");
define("_CPROLEMASTERREQUIREDFIELD", "Chcete-li aktualizovat nastavení skupiny správy zátěže, role nabíjecího bodu musí být uložena jako &#39Master&#39 z obecných nastavení správy zátěže.");

define("_LISTOFSLAVES", "Seznam otroků");
define("_NUMBEROFSLAVES", "Počet otroků");
define("_LISTOFCONNECTOR", "Seznam konektorů");
define("_AVAILABLECURRENT", "Dostupná aktuální fáze");

define("_DLMINTERFACE", "Rozhraní DLM");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "Povolte WiFi ze síťových rozhraní!");

define("_MUSTBEINTEGER", "musí být celé číslo!");

define("_GRIDBUFFER", "Procento ochranné marže mřížky");
define("_CHARGINGSTATUSALERT", "Ve stavu nabíjení nelze hodnotu aktualizovat!");
define("_READUNDERSTAND", "Přečetl jsem, rozumím");

define("_MORETHAN10", "Před uložením těchto nastavení musíte zvýšit Maximální proud sítě nebo snížit procento ochranného okraje sítě. Limit maximálního proudu sítě nemůže být nižší než 10A při použití procenta okraje ochrany sítě.");

define("_CLUSTERMAXCURRENT", "Max. proud clusteru");
define("_CLUSTERFAILSAFECURRENT", "Cluster Failsafe Current");
define("_CLUSTERMAXCURRENTERROR", "Je vyžadován maximální proud clusteru!");
define("_CLUSTERFAILSAFECURRENTERROR", "Cluster Failsafe Current je vyžadován!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Cluster Failsafe Aktuální hodnota nesmí být menší než 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Hodnota klastru Failsafe Current musí být menší než Maximum Grid Current!");
define("_CLUSTERFAILSAFE", "Cluster Failsafe Mode");

define("_CLUSTERMAXCURRENTLESSTHAN10", "Max. aktuální hodnota clusteru nesmí být menší než 10");
define("_CLUSTERMAXCURRENTMORETHAN", "Maximální aktuální hodnota clusteru musí být rovna nebo menší než tato hodnota:");
