<?php
include_once "access_control.php";
define("_LOGIN", "ZALOGUJ SIĘ");
define("_USERNAME", "Nazwa użytkownika:");
define("_PASSWORD", "Hasło:");
define("_CHANGEPASSWORD", "Zmień hasło");
define("_CURRENTPASSWORD", "Bieżące hasło:");
define("_NEWPASSWORD", "Nowe hasło:");
define("_CONFIRMNEWPASSWORD", "Potwierdź hasło:");
define("_SUBMIT", "Wyślij");
define("_CURRENTPASSWORDREQUIRED", "Wymagane jest bieżące hasło");
define("_PASSWORDREQUIRED", "Hasło jest wymagane");
define("_USERNAMEREQUIRED", "Nazwa użytkownika jest wymagana");
define("_USERAUTHFAILED", "Uwierzytelnienie użytkownika nie powiodło się!");
define("_USERNAMEORCURRENTPASSWORDWRONG", "Nazwa użytkownika lub aktualne hasło są nieprawidłowe!");
define("_DBACCESSFAILURE", "Brak dostępu do bazy danych!");
define("_CHANGEPASSWORDERROR", "Należy najpierw zmienić hasło!");
define("_SAMEPASSWORDERROR", "Nowe hasło powinno się różnić od bieżącego!");
define("_PASSWORDMATCHERROR", "Hasła nie pasują!");
define("_CURRENTPASSWORDWRONG", "Bieżące hasło jest nieprawidłowe!");
define("_PASSWORDERRORLEVEL2", "Hasło jest nieprawidłowe, długość znaków musi wynosić 20 i zawierać co najmniej dwie litery [A-Za-z], dwie cyfry [0-9] i dwa znaki specjalne [!%&/()=?*#+-_]");
define("_PASSWORDERRORLEVEL3", "Hasło jest nieprawidłowe, długość znaków musi wynosić co najmniej 12, maksymalnie 32 znaki i zawiera co najmniej dwie małe litery [a-z] i dwie duże litery [A-Z], dwie cyfry [0-9] i co najmniej dwa znaki specjalne [!%&/()=?*#+-_].");
define("_LOGINLOCKOUT", "Za dużo nieudanych prób. Spróbuj po 1800 sekundach.");

define("_MAINPAGE", "Strona główna");
define("_GENERAL", "Ustawienia główne");
define("_OCPPSETTINGS", "Ustawienia OCPP");
define("_NETWORKINTERFACES", "Interfejsy sieciowe");

define("_OCPPCONNINTERFACE", "Interfejs połączenia OCPP : ");
define("_CONNECTIONSTATE", "Status połączenia : ");
define("_DISCONNECTED", "Rozłączony");
define("_NEEDTOLOGINFIRST", "Należy się najpierw zalogować!");
define("_CONNECTED", "Połączony");
define("_CPSERIALNUMBER", "Numer seryjny CP : ");
define("_HMISOFTWAREVERSION", "Wersja oprogramowania HMI : ");
define("_OCPPSOFTWAREVERSION", "Wersja oprogramowania OCPP : ");
define("_POWERBOARDSOFTWAREVERSION", "Wersja oprogramowania karty sterowania : ");
define("_OCPPDEVICEID", "Numer seryjny urządzenia OCPP : ");
define("_DURATIONAFTERPOWERON", "Czas trwania po włączeniu : ");
define("_LOGOUT", "Wyloguj");
define("_PRESET", "Zestawy wstępne:");

define("_OCPPCONNECTION", "Połączenie OCPP");
define("_ENABLED", "Włączone");
define("_DISABLED", "Wyłączone");
define("_CONNECTIONSETTINGS", "Ustawienia połączenia");
define("_CENTRALSYSTEMADDRESS", "Adres systemu centralnego ");
define("_CHARGEPOINTID", "Identyfikator punktu ładowania ");
define("_OCPPVERSION", "Wersja OCPP");
define("_SAVE", "Zapisz");
define("_SAVESUCCESSFUL", "Zapisane pomyślnie.");
define("_CENTRALSYSTEMADDRESSERROR", "Wymagany adres systemu centralnego!");
define("_CHARGEPOINTIDERROR", "Wymagany Identyfikator punktu ładowania!");
define("_SECONDS", "Sekundy");
define("_ADD", "Dodaj");
define("_REMOVE", "Usuń");
define("_SAVECAPITAL", "ZAPISZ");
define("_CANCEL", "Anuluj");

define("_CELLULAR", "Komórkowy");
define("_INTERFACEIPADDRESS", "Adres IP interfejsu: ");
define("_ICCID", "ICCID: ");
define("_IMSI", "IMSI: ");
define("_IMEI", "IMEI: ");
define("_APNNAME", "Nazwa APN: ");
define("_APNUSERNAME", "Nazwa użytkownika APN: ");
define("_APNPASSWORD", "Hasło APN: ");
define("_IPSETTING", "Ustawienie IP: ");
define("_IPADDRESS", "Adres IP: ");
define("_NETWORKMASK", "Maska sieciowa: ");
define("_DEFAULTGATEWAY", "Brama domyślna: ");
define("_PRIMARYDNS", "Podstawowy DNS: ");
define("_SECONDARYDNS", "Zapasowy DNS: ");
define("_WIFI", "WLAN");
define("_SECURITY", "Zabezpieczenie: ");
define("_SECURITYTYPE", "Wybierz rodzaj zabezpieczenia");
define("_NONE", "Brak");
define("_SELECTMODE", "Wybierz tryb!");
define("_RFIDLOCALLIST", "Lokalna Lista RFID");
define("_ACCEPTALLRFIDS", "Akceptuj wszystkie RFID");
define("_MANAGERFIDLOCALLIST", "Zarządzaj lokalną listą RFID:");
define("_AUTOSTART", "Automatyczny Start");
define("_PROCESSING", "Przetwarzanie... Zaczekaj...");
define("_MACADDRESS", "Adres MAC: ");
define("_WIFIHOTSPOT", "Hotspot Wi-Fi");
define("_TURNONDURINGBOOT", "Włącz podczas rozruchu: ");
define("_AUTOTURNOFFTIMEOUT", "Limit czasu automatycznego wyłączenia: ");
define("_AUTOTURNOFF", "Automatyczne wyłączanie: ");
define("_HOTSPOTALERTMESSAGE", "Zmiany ustawień hotspotu zaczną obowiązywać po następnym włączeniu urządzenia. ");
define("_HOTSPOTREBOOTMESSAGE", "Czy chcesz teraz zrestartować komputer? ");

define("_DOWNLOADACLOGS", "Ściągnij logi AC");
define("_DOWNLOADCELLULARLOGS", "Ściągnij logi modułu komórkowego");
define("_DOWNLOADPOWERBOARDLOGS", "Ściągnij logi karty sterowania");
define("_PASSWORDRESETSUCCESSFUL", "Twoje hasło zostało pomyślnie zresetowane.");
define("_DBOPENEDSUCCESSFULLY", "Pomyślne otwarcie bazy danych\n");
define("_WSSCERTSSETTINGS", "Ustawienia certyfikatów WSS ");
define("_CONFKEYS", "Klucze konfiguracyjne");
define("_KEY", "Klucz");
define("_STATIC", "Statyczny");
define("_TIMEZONE", "Strefa czasowa");
define("_PLEASESELECTTIMEZONE", "Wybierz strefę czasową");
define("_DISPLAYSETTINGS", "Ustawienia ekranu");
define("_DISPLAYLANGUAGE", "Język ekranu");
define("_BACKLIGHTDIMMING", "Jasność podświetlenia : ");
define("_PLEASESELECT", "Proszę wybrać");
define("_TIMEBASED", "Czasowy");
define("_SENSORBASED", "Sensoryczny ");
define("_BACKLIGHTDIMMINGLEVEL", "Poziom jasności podświetlenia : ");
define("_BACKLIGHTTHRESHOLD", "Próg podświetlenia : ");
define("_SETMIDTHRESHOLD", "Ustaw próg średni");
define("_SETHIGHTHRESHOLD", "Ustaw próg wysoki");
define("_LOCALLOADMANAGEMENT", "Lokalne zarządzanie obciążeniem");
define("_MINIMUMCURRENT", "Minimalny prąd: ");
define("_FIFOPERCENTAGE", "Procent FIFO: ");
define("_GRIDMAXCURRENT", "Maksymalny prąd sieci: ");
define("_MASTERIPADDRESS", "Adres IP Master: ");
define("_BACKLIGHTTIMESETTINGS", "Ustawienia czasu podświetlenia: ");
define("_SHOULDSELECTTIMEZONE", "* Należy wybrać strefę czasową!");
define("_MINIMUMCURRENTREQUIRED", "* Wymagany jest minimalny prąd!");
define("_CURRENTMUSTBENUMERIC", "* Wartość bieżąca musi być liczbą!");
define("_FIFOPERCREQUIRED", "* Wymagana jest wartość procentowa FIFO!");
define("_FIFOPERCSHOULDBETWEEN", "* Wartość procentowa FIFO musi wynosić od 0 do 100!");
define("_PERCMUSTBENUMERIC", "* Wartość procentowa musi być liczbą!");
define("_GRIDMAXCURRENTREQUIRED", "* Wymagany jest maksymalny prąd sieci!");
define("_GRIDCURRENTMUSTBENUMERIC", "* Prąd sieci musi być liczbą!");
define("_IPADDRESSOFMASTERREQUIRED", "* Wymagany jest główny adres IP!");
define("_INVALIDIPADDRESS", "* Podałeś nieprawidłowy adres IP!");
define("_SAMENETWORKLAN", "* Wprowadziłeś adres IP w tej samej sieci co LAN!");
define("_SAMENETWORKWLAN", "* Wprowadziłeś adres IP w tej samej sieci z WLAN!");
define("_APNISREQUIRED", "Wymagany jest APN!");
define("_IPADDRESSREQUIRED", "Wymagany jest adres IP!");
define("_NETWORKMASKREQUIRED", "Wymagana jest maska sieciowa!");
define("_INVALIDNETWORKMASK", "* Podałeś nieprawidłową maskę sieci!");
define("_DEFAULTGATEWAYREQUIRED", "Wymagana jest brama domyślna!");
define("_INVALIDGATEWAY", "Wprowadziłeś nieprawidłową bramę domyślną!");
define("_PRIMARYDNSREQUIRED", "Wymagany jest podstawowy DNS!");
define("_INVALIDDNS", "Podałeś nieprawidłowy DNS!");
define("_SELECTIPSETTING", "Wybierz ustawienie IP.");
define("_SSIDREQUIRED", "Wymagany jest SSID!");
define("_PASSWORDISREQUIRED", "Hasło jest wymagane!");
define("_WIFIPASSWORDERROR", "Hasło jest nieprawidłowe, długość znaków musi wynosić co najmniej 8, a maksymalnie 63 <br> poprawne znaki a..z A..Z 0..9 .,:;!#^ $%&/(){[]}=*?-_@<>|");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL2", "&#8226; Hasło jest nieprawidłowe, długość znaków musi wynosić 20,<br>&#8226; Hasło musi zawierać co najmniej dwie litery [A-Za-z],<br>&#8226; Hasło musi zawierać co najmniej dwie cyfry [0-9],<br>&#8226; Hasło musi zawierać co najmniej dwa znaki specjalne [!%&/()=?*#+-_]");
define("_WIFIHOTSPOTPASSWORDERRORLEVEL3", "&#8226; Hasło jest nieprawidłowe, długość znaków musi wynosić co najmniej 12, maksymalnie 32<br>&#8226; Hasło musi zawierać co najmniej dwie małe litery [a-z], <br>&#8226; Hasło musi zawierać co najmniej dwie wielkie litery [A-Z], <br>&#8226; Hasło musi zawierać co najmniej dwie cyfry [0-9],<br>&#8226; Hasło musi zawierać co najmniej dwa znaki specjalne [!%&/()=?*#+-_]");
define("_WIFISSIDERROR", "SSID jest nieprawidłowy, prawidłowe znaki a..z A..Z 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");
define("_SELECTSECURITYTYPE", "Wybierz rodzaj zabezpieczenia");
define("_HOSTIPREQUIRED", "* Wymagany jest adres IP hosta!");
define("_CERTMANREQUIRED", "* Wymagane jest zarządzanie certyfikatami!");
define("_OCPPENABLEALERT", "Jeśli chcesz korzystać ze Stacji ładującej w trybie autonomicznym,<br>najpierw musisz wyłączyć połączenie OCPP w menu ustawień OCPP");
define("_NOTSAVEDALERT", "Strona nie została zapisana.");
define("_SAVEQUESTION", "Czy chcesz zapisać zmiany?");
define("_OKBUTTON", "OK");
define("_LTECONNECTIONCONFIRM", "Połączenie komórkowe zostanie wyłączone. Potwierdzasz?");
define("_WIFICONNECTIONCONFIRM", "Połączenie Wi-Fi zostanie wyłączone. Potwierdzasz?");
define("_DHCPSERVERCONNECTIONCONFIRM", "Jeśli chcesz włączyć LAN DHCP Server,<br>najpierw musisz wyłączyć Wi-Fi Hotspot z &#39Wi-Fi Hotspot&#39.");
define("_WIFIHOTSPOTCONNECTIONCONFIRM", "Jeśli chcesz włączyć Wi-Fi Hotspot,<br>najpierw musisz wyłączyć LAN DHCP Server w &#39LAN IP Setting&#39.");

define("_DYNAMIC", "Dynamiczny");
define("_DIAGNOSTICS", "Diagnostyka");
define("_LOCALLOAD", "Zarządzanie obciążeniem");
define("_DOWNLOAD", "Pobierz");
define("_STARTDATE", "Data rozpoczęcia");
define("_ENDDATE", "Data zakończenia");
define("_CLEAREVENTLOGS", "Wyczyść wszystkie dzienniki zdarzeń");
define("_CLEAREVENTLOGSINFO", "To spowoduje wyczyszczenie wszystkich dzienników zdarzeń!");
define("_DOWNLOADEVENTLOGSINFO", "Pobierz dzienniki zdarzeń urządzenia na maksymalnie 5 dni");
define("_DEVICEEVENTLOGS", "Dzienniki zdarzeń urządzenia");
define("_DEVICECHANGELOGS", "Dzienniki zmian urządzenia");
define("_LOGSDATEERROR", "Proszę wybrać daty na maksymalnie 5 dni.");
define("_DOWNLOACHANGELOGS", "Pobierz dzienniki zmian urządzenia");
define("_VPNFUNCTIONALITY", "Funkcjonalność VPN: ");
define("_CERTMANAGEMENT", "Zarządzanie certyfikatami: ");
define("_NAME", "Nazwa: ");
define("_CONNECTIONINTERFACE", "Interfejs połączenia ");
define("_ANY", "Każdy");
define("_OCPPCONNPARAMETERS", "Parametry konfiguracyjne OCPP");
define("_SETDEFAULT", "Ustaw na domyślne ");
define("_STANDALONEMODE", "Tryb autonomiczny");
define("_STANDALONEMODETITLE", "Tryb autonomiczny:");
define("_STANDALONEMODENOTSELECTED", "* Nie można wybrać trybu autonomicznego, ponieważ OCPP jest włączony.");
define("_CHARGERWEBUI", "Sieciowy interfejs użytkownika ładowarki");
define("_SYSTEMMAINTENANCE", "Konserwacja systemu");
define("_HOSTIP", "Adres IP hosta: ");
define("_PASSWORDERRORLEVEL1", "Hasło jest nieprawidłowe, długość znaków musi wynosić minimum 6 znaków i zawierać co najmniej 1 małą literę, 1 dużą literę i 1 cyfrę!");
define("_SELECTBACKLIGHTDIMMING", "* Musisz wybrać jasność podświetlenia!");
define("_ISREQUIRED", "jest wymagane");
define("_ISNOTVALID", "nie jest ważne!");
define("_ISDUPLICATED", "jest zduplikowany!");
define("_MUSTBENUMERIC", "musi być liczbą!");
define("_VPNFUNCTIONALITYREQUIRED", "* Wymagana jest funkcjonalność VPN!");
define("_VPNNAMEREQUIRED", "* Nazwa VPN jest wymagana!");
define("_VPNPASSWORDREQUIRED", "* Wymagane jest hasło VPN!");
define("_EXPLANATION", "Wskazuje wymagane pole.");
define("_FIRMWAREUPDATE", "Aktualizacje oprogramowania sprzętowego");
define("_BACKUPRESTORE", "Kopia zapasowa i przywracanie konfiguracji");
define("_SYSTEMRESET", "Reset systemu");
define("_CHANGEADMINPASSWORD", "Hasło administratora");
define("_FACTORYRESET", "Ustawienia fabryczne");
define("_FACTORYRESETBUTTON", "Przywrócenie ustawień fabrycznych");
define("_FACTORYDEFAULTCONFIGURATION", "Domyślna konfiguracja fabryczna");
define("_LOGFILES", "Pliki logów");
define("_BACKUPFILE", "Plik kopii zapasowej");
define("_RESTOREFILE", "Przywróć plik konfiguracyjny");
define("_FREEMODEMAXCHARACTER", "musi mieć maksymalnie 32 znaki!");
define("_RESTOREMESSAGE", "Czy potwierdzasz zastosowanie zmian i ponowne uruchomienie teraz?");

define("_TURKISH", "Türkçe");
define("_ROMANIAN", "Română");
define("_ENGLISH", "English");
define("_GERMAN", "Deutsch");
define("_FRENCH", "Français");
define("_SPANISH", "Español");
define("_ITALIAN", "Italiano");
define("_FINNISH", "Suomi");
define("_NORWEGIAN", "Norsk");
define("_SWEDISH", "Svenska");
define("_DUTCH", "Nederlands");
define("_HEBREW", "עב&#39ת");
define("_DANISH", "Dansk");
define("_CZECH", "Čeština");
define("_POLISH", "Polski");
define("_HUNGARIAN", "Magyar");
define("_SLOVAK", "Slovák");
define("_BULGARIAN", "български");
define("_GREEK", "Ελληνικά");
define("_MONTENEGRIN", "црногорски");
define("_BOSNIAN", "босански");
define("_SERBIAN", "Srpski Jezik");
define("_CROATIAN", "Hrvatski");

define("_PASSWORDTYPEEXPLANATION", "Twoje hasło musi mieć 6 znaków i zawierać co najmniej jedną wielką
literę, jedna mała literę, jedna cyfrę.");
define("_PASSWORDTYPEEXPLANATIONLEVEL2", "Twoje hasło musi mieć 20 znaków i zawierać co najmniej dwa
litery, dwie cyfry i dwa znaki specjalne.");
define("_PASSWORDTYPEEXPLANATIONLEVEL3", "Twoje hasło musi mieć minimum 12, maksymalnie 32 znaki i zawierać przynajmniej
dwie wielkie litery, dwie małe litery, dwie cyfry i dwa znaki specjalne.");

define("_BACKTOLOGIN", "Powrót do logowania");
define("_CHANGE", "Change");
define("_SYSTEMADMINISTRATION", "Administracja systemu");
define("_UPDATE", "Aktualizacja");
define("_CONFIRM", "Potwierdź");
define("_FACTORYDEFAULTCONFIRM", "Czy na pewno chcesz przywrócić ustawienia fabryczne?");
define("_FILENAME", "Nazwa pliku");
define("_UPLOAD", "Załaduj");
define("_SELECTFIRMWARE", "Wybierz plik aktualizacji oprogramowania układowego z komputera");
define("_FIRMWAREFILESIZE", "Sprawdź rozmiar pliku oprogramowania układowego.");
define("_FIRMWAREFILETYPE", "Sprawdź typ pliku oprogramowania układowego.");

define("_LESSTHANOREQUAL4", "musi wynosić od 1 do 4");
define("_LESSTHANOREQUAL20", "musi być mniejsze lub równe 20");
define("_LESSTHANOREQUAL65000", "musi być mniejsze lub równe 65000");
define("_LESSTHANOREQUAL300", "musi być mniejsze lub równe 300");
define("_LESSTHANOREQUAL86500", "musi być mniejsze lub równe 86500");
define("_LESSTHANOREQUAL10000", "musi być mniejsze lub równe 10000");
define("_LESSTHANOREQUAL22", "musi być mniejsze lub równe 22");
define("_LESSTHANOREQUAL10", "musi być mniejsze lub równe 10");
define("_LESSTHANOREQUAL600", "musi być mniejsze lub równe 600");
define("_LESSTHANOREQUAL120", "musi być mniejsze lub równe 120");
define("_HIGHTHANOREQUAL0", "musi być większa lub równa 0");
define("_CHANGEPASSWORDSUGGESTION", "Zalecamy zmianę domyślnego hasła z menu konserwacji systemu");

define("_FILESIZE", "Sprawdź rozmiar pliku.");
define("_FILETYPE", "Sprawdź rodzaj pliku.");

define("_BACKUPVERSIONCHECK", "Wersja tego pliku nie jest odpowiednia dla urządzenia.");
define("_HARDRESETCONFIRM", "Czy na pewno chcesz wykonać twardy reset?");
define("_SOFTRESETCONFIRM", "Czy na pewno chcesz wykonać miękki reset?");
define("_NEWSETUP", "Skorzystaj z instrukcji użytkownika do nowej konfiguracji.");

define("_LOGOSETTINGS", "Ustawienia logo");
define("_USELOGO", "Wybierz plik logo z komputera");
define("_LOGOTYPE", "Wybierz logo w formacie png.");
define("_LOGODIMENSION", "Maksymalny dopuszczalny rozmiar logo to 80 x 80, wybierz logo o odpowiednim rozmiarze.");

define("_SERVICECONTACTINFO", "Informacje kontaktowe serwisu wyświetlacza");
define("_SERVICECONTACTINFOCHARACTER", "Informacje kontaktowe serwisu wyświetlacza mogą mieć maksymalnie 25 znaków!<br>Prawidłowe znaki a..z 0..9 .+@*");

define("_SCREENTHEME", "Motyw wyświetlacza");
define("_DARKBLUE", "Ciemnoniebieski");
define("_ORANGE", "Pomarańczowy");
define("_PLEASEENTERRFIDLOCALLIST", "Wprowadź lokalną listę RFID!");

define("_LOADMANAGEMENT", "Zarządzanie obciążeniem");
define("_CPROLE", "Rola punktu ładowania");
define("_GRIDSETTINGS", "Ustawienia siatki");
define("_LOADMANAGEMENTMODE", "Tryb zarządzania obciążeniem");
define("_LOADMANAGEMENTGROUP", "Grupa zarządzania obciążeniem");
define("_LOADMANAGEMENTOPTION", "Opcja zarządzania obciążeniem");
define("_ALARMS", "Alarmy");

define("_MASTER", "Master");
define("_SLAVE", "Slave");
define("_TOTALCURRENTLIMIT", "Całkowity limit prądu na fazę");
define("_SUPPLYTYPE", "Rodzaj dostawy");
define("_FIFOPERCANTAGE", "Procent FIFO");
define("_TIC", "TIC");
define("_EQUALLYSHARED", "Równo współdzielone");
define("_COMBINED", "Łączny");
define("_TOTALCURRENTLIMITERROR", "Wymagany jest całkowity limit prądu na fazę!");
define("_LESSTHAN1024", "musi być mniejsza niż 1024");
define("_ATLEAST0","musi wynosić co najmniej 0");
define("_MORETHAN12", "musi być więcej niż 12");
define("_CHOOSEONE", "Wybierz jeden");
define("_SLAVEMINCHCURRENT", "Bezpieczne ustawienie prądu ładowania w trybie offline");
define("_SERIALNO", "Numer seryjny");
define("_CONNECTORSTATE", "Stan złącza");
define("_NUMBEROFPHASES", "Liczba faz");
define("_PHASECONSEQUENCE", "Sekwencja połączeń fazowych");
define("_VIP", "Ładowarka VIP");
define("_CPMODE", "CP Mode");
define("_VIPERROR", "Wymagane jest ładowanie VIP");
define("_PHASECONSEQUENCEERROR", "Wymagana jest sekwencja połączeń fazowych!");
define("_CPMODEERROR", "Tryb CP jest wymagany!");
define("_SUPPORTEDCURRENT", "Obsługiwany prąd");
define("_INSTANTCURPERPHASE", "Natychmiastowa Faza Bieżąca");
define("_FIFOCHARGINGPERCENTAGE", "Procent ładowania FIFO");
define("_MINIMUMCURRENT1P", "Minimalny prąd ładowania 1-fazowy");
define("_MINIMUMCURRENT3P", "Minimalny prąd ładowania 3-fazowy");
define("_MAXIMUMCURRENT", "Maksymalny prąd ładowania");
define("_STEP", "Stopień");
define("_UPDATEDLMGROUP", "Zaktualizuj grupę DLM");
define("_MAINCIRCUITCURRENT", "Maksymalny prąd sieci");
define("_MAINCIRCUITCURRENTERROR", "Wymagany jest maksymalny prąd sieci!");
define("_DLMMAXCURRENT", "Całkowity limit prądu DLM na fazę");
define("_DLMMAXCURRENTERROR", "Całkowity limit prądu DLM na fazę jest wymagany!");
define("_DLMMAXCURRENTMORETHANMAIN", "Całkowity limit prądu DLM powinien być większy niż połowa prądu wyłącznika głównego");
define("_DLMMAXCURRENTLESSTHANMAIN", "Całkowity limit prądu DLM powinien być mniejszy niż prąd wyłącznika głównego");

define("_DHCPSERVER", "Serwer DHCP");
define("_DHCPCLIENT", "Klient DHCP");

define("_MAXDHCPADDRRANGE", "Końcowy adres IP serwera DHCP");
define("_MINDHCPADDRRANGE", "Początkowy adres IP serwera DHCP");

define("_MAXDHCPADDRRANGEERROR", "Wymagany jest końcowy adres IP serwera DHCP!");
define("_MINDHCPADDRRANGEERROR", "Wymagany jest początkowy adres IP serwera DHCP!");
define("_DIFFERENCEBETWEENMAXANDMINADDRRANGE", "Końcowy adres IP serwera DHCP powinien być większy niż początkowy adres IP serwera DHCP");
define("_IPADDRESSRANGE", "Adres IP nie może przyjmować wartości pomiędzy początkowym i końcowym adresem IP serwera DHCP");
define("_INVALIDSUBNET", "Adres IP nie znajduje się w prawdziwej podsieci");

define("_CONNECTIONSTATUS", "Status połączenia");

define("_INSTALLATIONSETTINGS", "Ustawienia instalacji");
define("_EARTHINGSYSTEM", "System uziemienia");
define("_CURRENTLIMITERSETTINGS", "Ustawienia ogranicznika prądu");
define("_CURRENTLIMITERPHASE", "Faza ogranicznika prądu");
define("_CURRENTLIMITERVALUE", "Wartość ogranicznika prądu");
define("_UNBALANCEDLOADDETECTION", "Wykrywanie niezrównoważonego obciążenia");
define("_EXTERNALENABLEINPUT", "Zewnętrzne wejście Enable");
define("_LOCKABLECABLE", "Zamykany przewód");
define("_POWEROPTIMIZERTOTALCURRENTLIMIT", "Całkowity limit prądu optymalizatora mocy");
define("_POWEROPTIMIZER", "Optymalizatora mocy");
define("_TNORTT", "TN/TT");
define("_SPLITPHASE", "IT/Split Phase");
define("_ONEPHASE", "Jednofazowy");
define("_THREEPHASE", "Trójfazowy");
define("_POWEROPTIMIZERTOTALCURRENTLIMITMORETHANOREQUAL16", "Całkowity limit prądu <br> optymalizatora mocy musi <br> być większy lub równy 16");
define("_POWEROPTIMIZERTOTALCURRENTLIMITLESSTHANOREQUAL100", "Całkowity limit prądu <br> optymalizatora mocy musi <br> być mniejszy lub równy 100");
define("_FOLLOWTHESUN", "Podążaj za słońcem");
define("_FOLLOWTHESUNMODE", "Postępuj zgodnie z trybem słońca");
define("_AUTOPHASESWITCHING", "Automatyczne przełączanie faz");
define("_MAXHYBRID", "Max hybryda");
define("_SUNONLY", "Tylko słońce");
define("_SUNHYBRID", "Hybryda słoneczna");

define("_DISPLAYBACKLIGHTSETTINGS", "Ustawienia jasności ekranu");
define("_BACKLIGHTLEVEL", "Poziom jasności");
define("_SUNRISETIME", "Wschód słońca ");
define("_SUNSETTIME", "Zachód słońca");

define("_HIGH", "Wysoki");
define("_MID", "Średni");
define("_LOW", "Niski");

define("_A", " (A)");

define("_CURRENTLIMITERVALUELESSTHAN8", "* Gdy usługa EVReadySupport jest włączona, a faza limitu prądu jest jednofazowa, wartość limitu prądu nie może być mniejsza niż 8!");
define("_CURRENTLIMITERVALUELESSTHAN14", "* Gdy usługa EVReadySupport jest włączona, a faza limitu prądu jest trójfazowa, wartość limitu prądu nie może być mniejsza niż 14!");
define("_LEDDIMMINGSETTINGS", "Ustawienia przyciemniania diody Led");
define("_LEDDIMMINGLEVEL", "Poziom ściemniania Led");
define("_VERYLOW", "Bardzo niski");

define("_CELLULARGATEWAYCONFIRM", "Brama komórkowa zostanie wyłączona.");

define("_ETHERNETIP", "IP interfejsu Ethernet:");
define("_WLANIP", "IP interfejsu WLAN:");
define("_STRENGTH", "Wytrzymałość");
define("_WIFIFREQ", "Częstotliwość");
define("_WIFILEVEL", "Poziom");
define("_CELLULARIP", "IP interfejsu komórkowego:");
define("_CELLULAROPERCODE" , "Operator");
define("_CELLULARTECH" , "Technologia");
define("_APPLICATIONRESTART", "Ta zmiana wymaga ponownego uruchomienia aplikacji.");
define("_ACCEPTQUESTION", "Czy akceptujesz zmiany?");
define("_POWEROPTIMIZEREXTERNALMETER", "Licznik Zewnętrzny");
define("_OPERATIONMODE", "Tryb Pracy");
define("_AUTOSELECTED", "Wybrano automatycznie");
define("_NOTSELECTED", "Nie zaznaczone");
define("_CHARGINGMODESELECTIONANDPOWEROPTIMIZERCONF", "Wybór trybu ładowania i konfiguracja optymalizatora mocy");
define("_SCANNETWORKS" , "Skanowanie Sieci");
define("_AVAILABLENETWORKS" , "Dostępne Sieci");
define("_NETWORKSTATUS" , "Status Sieci");
define("_PLEASEWAITMSG" , "Proszę czekać...");
define("_SCANNINGWIFIMSG" , "Skanowanie sieci Wi-Fi");
define("_NOWIFIFOUNDMSG" , "Nie znaleziono sieci Wi-Fi");
define("_PLEASECHECKWIFICONNMSG" , "Proszę sprawdzić połączenie Wi-Fi i spróbować ponownie.");

define("_USERINTERACTION", "Interakcja z użytkownikiem");
define("_STANDBYLEDBEHAVIOUR", "Zachowanie diody LED w trybie gotowości");
define("_OFF", "Wyłączony");
define("_ON", "Ne");
define("_QRCODE", "Kod QR Ekranu");
define("_QRCODEONSCREEN", "Kod QR na Ekranie");
define("_QRCODEDELIMITER", "Ogranicznik kodu QR");
define("_INVALIDDELIMITERCHARACTER", "Ogranicznik kodu QR jest nieprawidłowy, spacje są niedopuszczalne, długość znaków musi wynosić co najmniej 1, a maksymalnie 3 znaków, prawidłowe znaki 0..9 .,:;!#^+$%&/(){[]}=*?-_@<>|");

define("_LOCATION", "Lokalizacja");
define("_INDOOR", "Wnętrz");
define("_OUTDOOR", "Na wolnym powietrzu");

define("_LOADSHEDDINGMINIMUMCURRENT", "Minimalny prąd zrzucania obciążenia");
define("_UNBALANCEDLOADDETECTIONMAXCURRENT", "Maksymalny prąd wykrywania niesymetrycznego obciążenia");

define("_SCHEDULEDCHARGING", "Zaplanowane ładowanie");
define("_OFFPEAKCHARGING", "Ładowanie poza szczytem");
define("_OFFPEAKCHARGINGWEEKENDS", "Weekendy ładowania poza szczytem");
define("_OFFPEAKCHARGINGPERIODS", "Okresy ładowania poza szczytem");
define("_CONTINUECHARGINGENDPEAKINTERVAL", "Kontynuuj ładowanie po zakończeniu okresu szczytowego");
define("_CONTINUECHARGINGWITHOUTREAUTHAFTERPOWERLOSS", "Kontynuuj ładowanie bez ponownej autoryzacji po utracie zasilania");
define("_RANDOMISEDDELAYMAXIMUMDURATION", "Maksymalny czas trwania losowego opóźnienia <br> (sekundy)");
define("_RANDOMISEDDELAYMAXIMUMDURATIONERROR", "* Wymagany jest maksymalny czas trwania losowego opóźnienia!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONBENUMERIC", "* Maksymalny czas trwania losowego opóźnienia musi być liczbą całkowitą!");
define("_RANDOMISEDDELAYMAXIMUMDURATIONLIMIT", "* Maksymalny czas trwania losowego opóźnienia powinien wynosić od 0 do 1800");
define("_OFFPEAKCHARGINGPERIODSERROR", "* Okresy ładowania poza szczytem są wymagane!");
define("_OFFPEAKCHARGINGPERIODSSAMETIMEERROR", "* Czas rozpoczęcia i zakończenia ładowania poza szczytem nie może być taki sam!");
define("_OFFPEAKCHARGINGSECONDTIMEPERIOD", "Drugi okres ładowania poza szczytem");
define("_OFFPEAKDISABLEDCONFIRM", "Ładowanie poza szczytem zostanie wyłączone. Potwierdzasz?");
define("_SHOWSERVICECONTACTINFO", "Pokaż dodatkowe informacje kontaktowe dotyczące usług");
define("_EXTRASERVICECONTACTINFORMATION", "Informacje kontaktowe serwisu są wyświetlane na ekranach Podłącz kabel ładujący, Przygotowanie do ładowania, Inicjowanie i Oczekiwanie na połączenie");

define("_LOADSHEDDINGSTATUS", "Stan zrzucania obciążenia:");
define("_ACTIVE", "Aktywny");
define("_INACTIVE", "Nieaktywny");
define("_POWEROPTIMIZEREXTERNALMETERENABLEALERT", "Jeśli chcesz korzystać z opcji zarządzania obciążeniem w sieci Modbus,<br>najpierw musisz wyłączyć Całkowity limit prądu funkcji Power Optimizer<br>w &#39Wybór trybu ładowania i Konfiguracja optymalizatora mocy&#39.");
define("_MODBUSALERT", "Jeśli chcesz włączyć swój zewnętrzny miernik Power Optimizer,<br>najpierw musisz dezaktywować Modbus<br>w &#39Local Load Management&#39.");
define("_POWEROPTIMIZERDLMENABLEALERT", "Jeśli chcesz używać opcji zarządzania obciążeniem w trybie Master/Slave,<br>najpierw musisz wyłączyć Optymalizator<br>mocy w &#39Wyborze trybu ładowania i konfiguracji optymalizatora mocy&#39.");
define("_DLMALERT", "Jeśli chcesz włączyć Optymalizator mocy,<br>najpierw musisz wyłączyć Master/Slave<br>w &#39Lokalnym Zarządzaniu Obciążeniem&#39.");

define("_FOLLOWTHESUNDLMENABLEALERT", "Jeśli chcesz używać opcji zarządzania obciążeniem w trybie Master/Slave,<br>najpierw musisz wyłączyć Podążaj <br>za słońcem w &#39Wyborze trybu ładowania i konfiguracji optymalizatora mocy&#39.");
define("_DLMALERTFOLLOWTHESUN", "Jeśli chcesz włączyć Podążaj za słońcem,<br>najpierw musisz wyłączyć Master/Slave<br>w &#39Lokalnym Zarządzaniu Obciążeniem&#39.");

define("_RESETUSERPASSWORD", "Zresetuj hasło <br> użytkownika");
define("_INSTALLATIONERRORENABLEDCONFIRM", "Jeśli chcesz wyłączyć Włącz błąd instalacji,<br>najpierw musisz ustawić system uziemienia z &#39Ustawienia instalacji&#39 na fazę IT/Split.");
define("_EARTHINGSYSTEMCONFIRM", "Jeśli chcesz ustawić system uziemienia na TN/TT,<br>najpierw musisz włączyć opcję Włącz błąd instalacji w &#39OCPP Settings&#39.");

define("_AUTHKEYMAXLIMIT", "długość powinna wynosić maksymalnie 40 znaków.");
define("_AUTHORIZATIONKEYEMPTYCONFIRM", "Pole Authorization Key jest puste.<br>Czy potwierdzasz zmiany?");

define("_RANDOMISEDDELAYATOFFPEAKEND", "Losowe opóźnienie na końcu poza szczytem");
define("_FIFO", "FIFO");
define("_FAILSAFECURRENT", "Bezpieczny prąd");
define("_FAILSAFECURRENTERROR", "Wymagany jest prąd awaryjny!");
define("_FAILSAFECURRENTLESSTHAN0", "* Failsafe Bieżąca wartość nie może być mniejsza niż 0!");
define("_FAILSAFECURRENTMORETHAN32", "* Failsafe Aktualna wartość nie może być większa niż 32!");
define("_FAILSAFECURRENTMORETHAN50", "* Failsafe Aktualna wartość nie może być większa niż 50!");

define("_LOCALCHARGESESSION", "Lokalne sesje opłat");
define("_ROWNUMBER", "Nr wiersza");
define("_SESSIONUUID", "opłat-ID");
define("_AUTHORIZATIONUID", "kod RFID");
define("_STARTTIME", "Czas Rozpoczęcia");
define("_STOPTIME", "Czas Zakończenia");
define("_TOTALTIME", "CałkowityCzas");
define("_STATUS", "Status");
define("_CHARGEPOINTIDS", "Numer gniazda");
define("_INITIALENERGY", "Początkowa energia(kWh)");
define("_LASTENERGY", "Ostatnia Energia(kWh)");
define("_TOTALENERGY", "Całkowita energia(kWh)");
define("_DOWNLOADLOCALCHARGESESSIONLOGS", "Pełny dziennik sesji w pliku CSV");
define("_DOWNLOADFULLSESSIONLOGS", "Podsumowanie dziennika w pliku CSV");
define("_STARTDATE", "Data rozpoczęcia");
define("_ENDDATE", "Data końcowa");
define("_RFIDSELECTION", "wybór RFID");
define("_CLEAR", "jasne");

define("_FALLBACKCURRENT", "Prąd rezerwowy");
define("_FALLBACKRANGE", "Prąd rezerwowy musi wynosić 0 lub mieścić się w zakresie ");
define("_DOWNLOADEEBUSLOGS", "Dzienniki EEBUS");
define("_PAIRINGENERGYMANAGER", "Włączono do parowania");
define("_PAIR", "Parowanie włączone");
define("_UNPAIR", "Rozłącz");
define("_EEBUS", "EEBUS");
define("_FIRMWAREVERSION", "Wersja oprogramowania");
define("_EEBUSDISCOVERY", "Odkryte urządzenia");
define("_REFRESH", "Odśwież");
define("_CPROLEMASTERREQUIREDFIELD", "Jeśli chcesz zaktualizować ustawienia grupy zarządzania obciążeniem, rolę punktu ładowania należy zapisać jako &#39Master&#39 w ogólnych ustawieniach zarządzania obciążeniem.");

define("_LISTOFSLAVES", "Lista niewolników");
define("_NUMBEROFSLAVES", "Liczba niewolników");
define("_LISTOFCONNECTOR", "Lista złączy");
define("_AVAILABLECURRENT", "Dostępna faza prądu");

define("_DLMINTERFACE", "Interfejs DLM");
define("_ETHERNET", "Ethernet");
define("_DLMINTERFACEERROR", "Włącz Wi-Fi z interfejsów sieciowych!");

define("_MUSTBEINTEGER", "musi być liczbą całkowitą!");
define("_GRIDBUFFER", "Procent marginesu ochrony sieci");
define("_CHARGINGSTATUSALERT", "W stanie ładowania wartość nie może zostać zaktualizowana!");
define("_READUNDERSTAND", "Przeczytałem, rozumiem");

define("_MORETHAN10", "Musisz zwiększyć Maksymalny Prąd Sieciowy lub zmniejszyć Margines Ochrony Sieci w Procentach przed zapisaniem tych ustawień. Limit Maksymalnego Prądu Sieciowego nie może być niższy niż 10A przy użyciu Marginesu Ochrony Sieci w Procentach.");

define("_CLUSTERMAXCURRENT", "Maksymalny prąd klastra");
define("_CLUSTERFAILSAFECURRENT", "Bieżący tryb awaryjny klastra");
define("_CLUSTERMAXCURRENTERROR", "Wymagany jest maksymalny prąd klastra!");
define("_CLUSTERFAILSAFECURRENTERROR", "Wymagany jest prąd awaryjny klastra!");
define("_CLUSTERFAILSAFECURRENTLESSTHAN0", "Bieżąca wartość klastra Failsafe nie może być mniejsza niż 0!");
define("_CLUSTERFAILSAFECURRENTMORETHAN", "Wartość prądu bezpiecznego klastra musi być mniejsza niż maksymalny prąd sieci!");
define("_CLUSTERFAILSAFE", "Tryb awaryjny klastra");

define("_CLUSTERMAXCURRENTLESSTHAN10", "Maksymalna wartość bieżąca klastra nie może być mniejsza niż 10");
define("_CLUSTERMAXCURRENTMORETHAN", "Maksymalna wartość bieżąca klastra musi być równa lub mniejsza od tej wartości:");